### PR TITLE
[IBFT] Introduce quorum calculation switch 

### LINKED ISSUE #547: failed to write bulk sync blocks: failed to verify the header: not enough seals to seal block
### Description
- We pulled in latest develop changes to one of our validator and are seeing this error.

### Your environment

* OS and version: `Ubuntu 20`
* version of the Polygon Edge: `dd1d9af9d602fe1c88ce473c09259a038d07a16d`
* branch that causes this issue: `develop`

### Steps to reproduce

- Create a validator node with latest develop changes

### Logs

```
May 11 14:57:23 ip-172-31-4-5 main[579319]: 2022-05-11T14:57:23.511Z [ERROR] polygon.consensus.ibft: failed to bulk sync: err="failed to write bulk sync blocks: failed to verify the header: not enough seals to seal block"
```

we suspect [https://github.com/0xPolygon/polygon-edge/pull/513](https://github.com/0xPolygon/polygon-edge/pull/513) this PR might have introduced this error

### PR DESCRIPTION
**Pull request by dbrajovic**
# Description

This PR enables users to specify a block number after which QuorumOptimal (`2/3 * N`) will be used to calculate the required number of messages for the given network size (`N`).

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

1. Setup a 6-node cluster on commit 805f9ef4da0d30d142c0e4850f95f27da77243b5
2. Start 3 of the nodes
3. Start a non-validator node on this branch
4. Observe that the non-validator is unable to sync with the network
5. Run `ibft quorum --from XX --chain your_genesis_file.json` to specify the block number after which quorum optimal calculation will be used
6. Restart all (6) nodes with the binary built from this branch and the chain grow
7. Run the non-validator node and observe it is able to sync up with the network 

# Documentation update

TODO

# Additional comments

PR #513 introduced a new calculation for quorum size of a given validator set. In practical terms, this means the number of votes required for reaching consensus became more constrained. Consequentially, the PR implemented a breaking change for existing chains, as any new node joining the network would not be able to verify previously sealed blocks. 

By specifying a `--from` value for the `ibft quorum` command, new nodes syncing with the chain will be able to correctly verify seals from older blocks. Old blocks (up until the value specified) will be verified using the old formula (`LegacyQuorumSize`) and all subsequent blocks with the new (`OptimalQuorumSize`).

How-to: applying the flag for existing chains

1. Update all nodes to a version of Polygon-Edge that includes this PR
2. Modify your genesis file by running: `polygon-edge ibft quorum --from [your_quorum_switch_block_num] --chain [your_genesis_file]`. Make sure that after `your_quorum_switch_block_num` an `OptimalQuorumSize` of validators are signing the blocks
3. Observe that all (new) nodes are able to sync with the running network

Fixes EDGE-556

### CODE REVIEW

File: command/ibft/ibft.go [hunk 1]
```diff
@@ -35,5 +36,7 @@ func registerSubcommands(baseCmd *cobra.Command) {
 		candidates.GetCommand(),
 		// ibft switch
 		_switch.GetCommand(),
+		//	ibft quorum
```
Comment (zivkovicmilos) [inline command/ibft/ibft.go]: Really a mega nitpick:
There is a space and a tab after the `//`. Please fix this formatting 🙏

File: command/ibft/quorum/ibft_quorum.go [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+	return ibftQuorumCmd
+}
+
+func setFlags(cmd *cobra.Command) {
+	cmd.Flags().StringVar(
+		&params.genesisPath,
+		chainFlag,
+		fmt.Sprintf("./%s", command.DefaultGenesisFileName),
+		fmt.Sprintf(
+			"the genesis file to update. Default: ./%s",
```
Comment (zivkovicmilos) [inline command/ibft/quorum/ibft_quorum.go]: No need to put the `. Default:` section here, Cobra will auto-generate it for you  👍

File: command/ibft/quorum/params.go [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+	return nil
+}
+
+func (p *quorumParams) getResult() command.CommandResult {
+	result := &IBFTQuorumResult{
+		Chain: p.genesisPath,
+		From:  common.JSONNumber{Value: p.from},
+	}
+
+	return result
```
Comment (zivkovicmilos) [inline command/ibft/quorum/params.go]: This can be inlined

File: consensus/ibft/ibft.go [hunk 4]
```diff
@@ -1249,13 +1249,31 @@ func (i *Ibft) VerifyHeader(parent, header *types.Header) error {
...
+	cfgQuorumSizeBlockNum, ok := rawUint64.(float64)
+	if !ok {
+		panic("invalid block number format")
+	}
+
+	if blockNumber < uint64(cfgQuorumSizeBlockNum) {
+		return LegacyQuorumSize
+	} else {
+		return OptimalQuorumSize
+	}
```
Comment (zivkovicmilos) [inline consensus/ibft/ibft.go]: You can drop the `else` here, just have a 

`return OptimalQuorumSize`

File: consensus/ibft/ibft.go [hunk 5]
```diff
@@ -1249,13 +1249,31 @@ func (i *Ibft) VerifyHeader(parent, header *types.Header) error {
...
 	// verify the committed seals
-	if err := verifyCommitedFields(snap, header); err != nil {
+	if err := verifyCommitedFields(snap, header, i.quorumSize(header.Number)); err != nil {
 		return err
 	}
 
 	return nil
 }
 
+func (i *Ibft) quorumSize(blockNumber uint64) QuorumImplementation {
```
Comment (zivkovicmilos) [inline consensus/ibft/ibft.go:1276]: Can you please add some comment as to what this method does? 🙏

File: consensus/ibft/ibft.go [hunk 6]
```diff
@@ -1249,13 +1249,31 @@ func (i *Ibft) VerifyHeader(parent, header *types.Header) error {
...
+	rawUint64, ok := i.config.Config["quorumSizeBlockNum"]
+	if !ok {
+		return OptimalQuorumSize
+	}
+
+	cfgQuorumSizeBlockNum, ok := rawUint64.(float64)
+	if !ok {
+		panic("invalid block number format")
```
Comment (zivkovicmilos) [inline consensus/ibft/ibft.go]: The more I'm thinking about this `panic`, the more I think it's fine if we just assume that an invalid cast results in it being `0`.

@Kourin1996 what do you think?

**Review by zivkovicmilos — APPROVED** [review]
Looks great 💯 

I've left some minor nitpick comments, nothing major 👍 

Great work on this PR 👏

File: consensus/ibft/ibft.go (hunk 6 above)
Comment (Kourin1996) [reply consensus/ibft/ibft.go]: I guess you need to check before starting consensus. You will load config on factory or Start method and this method just read field in IBFT field
@dbrajovic

**Review by Kourin1996 — COMMENTED** [review]
LGTM. I will approve after the fixes for @zivkovicmilos's reviews are pushed

File: command/ibft/ibft.go (hunk 1 above)
Comment (dbrajovic) [reply command/ibft/ibft.go]: [Resolved](https://github.com/0xPolygon/polygon-edge/pull/549/commits/ce06e14ba253949d38f843f83ce1c43f7657d16f)

File: command/ibft/quorum/ibft_quorum.go (hunk 2 above)
Comment (dbrajovic) [reply command/ibft/quorum/ibft_quorum.go]: [Removed](https://github.com/0xPolygon/polygon-edge/pull/549/commits/f6534cdc3fbdfcc85db3a0fc2de7a26605df6c4c)

File: command/ibft/quorum/params.go (hunk 3 above)
Comment (dbrajovic) [reply command/ibft/quorum/params.go]: [Inlined](https://github.com/0xPolygon/polygon-edge/pull/549/commits/86d631d49a1aed37dc888dc6f5b3be768625e6db)

File: consensus/ibft/ibft.go (hunk 4 above)
Comment (dbrajovic) [reply consensus/ibft/ibft.go]: [Dropped](https://github.com/0xPolygon/polygon-edge/pull/549/commits/bdc844ddce828e630c441dfb5c29a32b0e417e64)

File: consensus/ibft/ibft.go (hunk 5 above)
Comment (dbrajovic) [reply consensus/ibft/ibft.go:1276]: [Added description](https://github.com/0xPolygon/polygon-edge/pull/549/commits/22e04571a284c2f404fd0bdc1c47a8f09e458d54)

File: command/ibft/quorum/ibft_quorum.go (hunk 2 above)
Comment (zivkovicmilos) [reply command/ibft/quorum/ibft_quorum.go]: You forgot the `./%s`. Cobra will fill it like `flag description (default: ...)`

File: command/ibft/quorum/params.go [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+
+	return nil
+}
+
+func (p *quorumParams) initRawParams() error {
+	if err := p.initChain(); err != nil {
+		return err
+	}
+
+	return nil
```
Comment (0xAleksaOpacic) [inline command/ibft/quorum/params.go]: Just a suggestion,nothing important. Here we can just return p.initChain();

**Review by 0xAleksaOpacic — APPROVED** [review]
LGTM!

File: command/ibft/quorum/ibft_quorum.go (hunk 2 above)
Comment (dbrajovic) [reply command/ibft/quorum/ibft_quorum.go]: Got it. 👍 

[Removed](https://github.com/0xPolygon/polygon-edge/pull/549/commits/da6b48688e0dc6bd07bc6a4b9a583e841046ed2f)

File: command/ibft/quorum/params.go (hunk 7 above)
Comment (dbrajovic) [reply command/ibft/quorum/params.go]: Good catch

[Simplified](https://github.com/0xPolygon/polygon-edge/pull/549/commits/78ac602703bc607ed2e91bb5bec5ce1b65ff2631)

File: consensus/ibft/ibft.go (hunk 6 above)
Comment (dbrajovic) [reply consensus/ibft/ibft.go]: What do you think about this approach ?

[fb17482](https://github.com/0xPolygon/polygon-edge/pull/549/commits/fb17482ce8845ec3b58956b1a9998f4fdc8eaf28)

Comment (zivkovicmilos) [reply consensus/ibft/ibft.go]: Looks great 💯

**Review by Kourin1996 — APPROVED** [review]

**Review by zivkovicmilos — APPROVED** [review]
Approving, again 💯
