### PR TITLE
Remove WebSocket subscription of which closed connection

### LINKED ISSUE #486: Recurring `Unable to process flush` WS error messages on premature client exit
### Description

If fixed this would definitely help to minimize unnecessary error logs.

When a node has an open web-socket connection to a client that exits prematurely, we see the the recurring errors below that spam our logs until we perform a restart:

```
2022-04-01T21:30:38.017Z [ERROR] polygon.filter: Unable to process flush, writev tcp 555.555.555.555:10002->555.555.555.555:38176: use of closed network connection
```

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon Edge `v0.3.2`
* branch that causes this issue `develop`

### Steps to reproduce

1. Connect a client directly to a node + subscribe to a WS connected (e.g. Blockscout explorer)
2. Terminate the client process 
3. Observe recurring `Unable to process flush` on the host node 

### Expected behaviour

I would only expect an initial error indicating an issue with the WS connection, rather than seeing the same error persist requiring a node restart.

### Actual behaviour

The same error persists requiring a node restart.

### Logs

See above.

### Proposed solution

Perhaps after the same WS filter has been attempted to be flushed 5 times - if we still encounter errors on flushing, we should simply discard this filter from the FileManager.

### PR DESCRIPTION
**Pull request by Kourin1996**
# Description

Relevant Issue: https://github.com/0xPolygon/polygon-edge/issues/486

This PR fixes the issue that errors are repeating after WebSocket subscription was closed from client-side without calling unsubscribe method

```bash
2022-04-03T20:58:58.023+0300 [ERROR] polygon.jsonrpc: Unable to write WS message, websocket: close sent
2022-04-03T20:58:58.023+0300 [ERROR] polygon.filter: Unable to process flush, websocket: close sent
2022-04-03T20:59:00.016+0300 [ERROR] polygon.jsonrpc: Unable to write WS message, websocket: close sent
2022-04-03T20:59:00.016+0300 [ERROR] polygon.filter: Unable to process flush, websocket: close sent
```

The error which returned when sending to a closed connection was not checked. This PR removes the filter when FilterManager notices the connection is closed on sending.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

1. Run Polygon Edge nodes under latest `develop` branch
2. Connect to node by WebSocket and call `eth_subscribe` to subscribe events

```json
{
    "jsonrpc": "2.0",
    "method": "eth_subscribe",
    "params": [
        "newHeads"
    ],
    "id": 1
}
```

3. Close WebSocket connection from cient side without `eth_uninstallFilter` or `eth_unsubscribe`

4. Check logs of the nodes the client connected to and the errors like below are outputting forever

```bash
2022-04-03T20:58:58.023+0300 [ERROR] polygon.jsonrpc: Unable to write WS message, websocket: close sent
2022-04-03T20:58:58.023+0300 [ERROR] polygon.filter: Unable to process flush, websocket: close sent
2022-04-03T20:59:00.016+0300 [ERROR] polygon.jsonrpc: Unable to write WS message, websocket: close sent
2022-04-03T20:59:00.016+0300 [ERROR] polygon.filter: Unable to process flush, websocket: close sent
2022-04-03T20:59:02.016+0300 [ERROR] polygon.jsonrpc: Unable to write WS message, websocket: close sent
2022-04-03T20:59:02.016+0300 [ERROR] polygon.filter: Unable to process flush, websocket: close sent
```

5. Checkout the branch of this PR and try to check if such errors no longer appear

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

File: jsonrpc/filter_manager.go [hunk 1]
```diff
@@ -146,8 +147,8 @@ type FilterManager struct {
 
 	subscription blockchain.Subscription
 
-	filters map[string]*Filter
-	lock    sync.Mutex
+	filters     map[string]*Filter
+	filtersLock sync.RWMutex
```
Comment (zivkovicmilos) [inline jsonrpc/filter_manager.go]: Honestly, I think it's fine if we embed this instead of having it as a field.

What do you think?

File: jsonrpc/filter_manager.go [hunk 2]
```diff
@@ -227,23 +228,22 @@ func (f *FilterManager) Run() {
 }
 
 func (f *FilterManager) nextTimeoutFilter() *Filter {
-	f.lock.Lock()
+	f.filtersLock.RLock()
```
Comment (zivkovicmilos) [inline jsonrpc/filter_manager.go]: I think it just complicates the logic having to lock the entire filters manager to read the size of the filters. What do you think about having it as an atomic counter?

File: jsonrpc/filter_manager.go [hunk 3]
```diff
@@ -296,37 +296,62 @@ func (f *FilterManager) dispatchEvent(evnt *blockchain.Event) error {
 		}
 	}
 
+	closedFilterIDs := make([]string, 0)
+
 	// flush all the websocket values
-	for _, filter := range f.filters {
+	for id, filter := range f.filters {
 		if filter.isWS() {
```
Comment (zivkovicmilos) [inline jsonrpc/filter_manager.go]: Isn't it just easier to continue if it's _not_ a WS filter?

File: jsonrpc/filter_manager.go [hunk 4]
```diff
@@ -296,37 +296,62 @@ func (f *FilterManager) dispatchEvent(evnt *blockchain.Event) error {
...
+
 	return nil
 }
 
 func (f *FilterManager) Exists(id string) bool {
-	f.lock.Lock()
+	f.filtersLock.RLock()
 	_, ok := f.filters[id]
-	f.lock.Unlock()
+	f.filtersLock.RUnlock()
```
Comment (zivkovicmilos) [inline jsonrpc/filter_manager.go]: Why not defer?

File: jsonrpc/filter_manager.go [hunk 5]
```diff
@@ -341,8 +366,17 @@ func (f *FilterManager) GetFilterChanges(id string) (string, error) {
 }
 
 func (f *FilterManager) Uninstall(id string) bool {
-	f.lock.Lock()
+	f.filtersLock.Lock()
+
+	removed := f.removeFilterByID(id)
+
+	f.filtersLock.Unlock()
```
Comment (zivkovicmilos) [inline jsonrpc/filter_manager.go]: Why not defer?

File: jsonrpc/filter_manager.go [hunk 6]
```diff
@@ -341,8 +366,17 @@ func (f *FilterManager) GetFilterChanges(id string) (string, error) {
 }
 
 func (f *FilterManager) Uninstall(id string) bool {
```
Comment (zivkovicmilos) [inline jsonrpc/filter_manager.go]: Why do we need the feedback if it was uninstalled?

File: jsonrpc/filter_manager.go [hunk 7]
```diff
@@ -341,8 +366,17 @@ func (f *FilterManager) GetFilterChanges(id string) (string, error) {
...
+	f.filtersLock.Lock()
+
+	removed := f.removeFilterByID(id)
+
+	f.filtersLock.Unlock()
 
+	return removed
+}
+
+// removeFilterByID removes a filter with given ID, unsafe agarint race condition
```
Comment (zivkovicmilos) [inline jsonrpc/filter_manager.go]: Typo here, `agarint`

**Review by zivkovicmilos — APPROVED** [review]
Looks good 💯 

I've left a few comments. Thank you for taking up fixing this 🙏

File: jsonrpc/filter_manager.go (hunk 1 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: I can't agree with that. Embedding mutex to a small struct that has only 1-2 fields would be good.

File: jsonrpc/filter_manager.go (hunk 2 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: What do you mean? There will be race conditions for timers as well. Should lock whole method

File: jsonrpc/filter_manager.go (hunk 6 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: https://github.com/0xPolygon/polygon-edge/blob/876489ae0cef41dab883463cffe74ebb6e658a34/jsonrpc/dispatcher.go#L195

https://github.com/0xPolygon/polygon-edge/blob/876489ae0cef41dab883463cffe74ebb6e658a34/jsonrpc/dispatcher.go#L167

File: jsonrpc/filter_manager.go (hunk 5 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Fixed for you :) 6f2fe32ceefcf128da94084513b34f02e1eacef0

File: jsonrpc/filter_manager.go (hunk 7 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Thank you for your kind alert. Fixed at dcb2346b957ab539d3e52daf2a313d1fec859913

File: jsonrpc/filter_manager.go (hunk 4 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Fixed for you :) https://github.com/0xPolygon/polygon-edge/commit/6f2fe32ceefcf128da94084513b34f02e1eacef0

File: jsonrpc/filter_manager.go (hunk 3 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Nice catch. I fixed at dcb2346b957ab539d3e52daf2a313d1fec859913

File: jsonrpc/filter_manager.go (hunk 6 above)
Comment (zivkovicmilos) [reply jsonrpc/filter_manager.go]: Jesus Christ 🤦 

Resolving because we will clean this trash up later...

File: jsonrpc/filter_manager.go (hunk 2 above)
Comment (zivkovicmilos) [reply jsonrpc/filter_manager.go]: Aha, so we need to hold the lock while fetching an item from the `f.timer`?

File: jsonrpc/filter_manager.go (hunk 1 above)
Comment (zivkovicmilos) [reply jsonrpc/filter_manager.go]: We can probably simplify the FM to have this behavior (be a 1 - 2 field struct).

Resolving as this is not part of this task 🙂

File: jsonrpc/filter_manager.go (hunk 2 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Yes

Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Closing because I refactored the code. Please review again 🙏

File: jsonrpc/filter_manager.go [hunk 8]
```diff
@@ -15,57 +16,61 @@ import (
 	"github.com/hashicorp/go-hclog"
 )
 
-type Filter struct {
-	id string
+var ErrFilterDoesNotExists = errors.New("filter does not exists")
 
-	// block filter
-	block *headElem
+// defaultTimeout is the timeout to remove the filters that doesn't have web socket stream
```
Comment (dbrajovic) [inline jsonrpc/filter_manager.go]: Typo here: `that don't have a web socket stream`

File: jsonrpc/filter_manager.go [hunk 9]
```diff
@@ -83,48 +89,110 @@ func (f *Filter) sendMessage(msg string) error {
...
 }
 
-var defaultTimeout = 1 * time.Minute
+// takeLogUpdates returns all saved logs in filter and set new log slice
+func (f *logFilter) takeLogUpdates() []*Log {
+	f.Lock()
+	defer f.Unlock()
+
+	logs := f.logs
+	f.logs = []*Log{} // create brand new slice so that prevent new logs from being added to current logs
```
Comment (dbrajovic) [inline jsonrpc/filter_manager.go:170]: Why do we need to safeguard this?

File: jsonrpc/filter_manager.go [hunk 10]
```diff
@@ -15,57 +16,61 @@ import (
...
-	// log filter
-	res, err := json.Marshal(f.logs)
-	if err != nil {
-		return "", err
+// newFilterBase initializes filterBase with unique ID
+func newFilterBase(ws wsConn) filterBase {
+	return filterBase{
+		id:        uuid.New().String(),
+		ws:        ws,
+		heapIndex: -1,
```
Comment (dbrajovic) [inline jsonrpc/filter_manager.go]: Can we extract out the -1 to a constant?

**Review by zivkovicmilos — APPROVED** [review]
Looks good 🚀

File: jsonrpc/filter_manager.go [hunk 11]
```diff
@@ -226,197 +296,300 @@ func (f *FilterManager) Run() {
...
-	if !ok {
-		return "", errFilterDoesNotExists
-	}
+	filter, ok := f.filters[id]
 
-	if item.isWS() {
-		// we cannot get updates from a ws filter with getFilterChanges
-		return "", errFilterDoesNotExists
+	// we cannot get updates from a ws filter with getFilterChanges
+	if !ok || filter.isWS() {
```
Comment (dbrajovic) [inline jsonrpc/filter_manager.go]: Can we split this conditional into 2 separate errors? I think we'll find it easier to debug in the long run

File: jsonrpc/filter_manager.go (hunk 9 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go:170]: Because want to add new logs to current slice since this line. New logs will be saved into new slice.

File: jsonrpc/filter_manager.go (hunk 11 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Fixed at b0728d05324cea09366d9761c7661205e4e6dcac

File: jsonrpc/filter_manager.go (hunk 10 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Added at b0728d05324cea09366d9761c7661205e4e6dcac

File: jsonrpc/filter_manager.go (hunk 8 above)
Comment (Kourin1996) [reply jsonrpc/filter_manager.go]: Fixed at b0728d05324cea09366d9761c7661205e4e6dcac

**Review by dbrajovic — APPROVED** [review]
