### PR TITLE
fixed txpool maxEnqueued issue

### LINKED ISSUE #1782: Txpool problem
When one account sent above 128 transaction all capacity of wallet reached
and we got [ERROR] polygon.txpool: failed to add broadcast tx: err="maximum number of enqueued transactions reached"

the only way to solve problem is stop all nodes and start all again
If I stop adding new transactions again I got [ERROR] polygon.txpool: failed to add broadcast tx: err="maximum number of enqueued transactions reached"

if blockchain work in public how cloud we do stop all nodes and start them again to clear enqueued transactions
we should have command to clear enqueued transactions or if we stop new transaction remain 128 transaction most be handled by txpool and pool most be got clean

I think this is bug.

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

### PR DESCRIPTION
**Pull request by rachit77**
# Description

Currently, the Txpool refuses to process transactions for a specific address once the `maxEnqueued` limit for that address is reached. This situation results in a stagnant state for the address, preventing it from accommodating any further transactions, including those with the `nextNonce`. With the introduction of this PR, addresses will have the capability to accept transactions with the `nextNonce`,  even when the `maxEnqueued` limit for an account has been reached.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [ ] I have tested this code manually

### CODE REVIEW

File: txpool/txpool.go [hunk 1]
```diff
@@ -814,7 +814,7 @@ func (p *TxPool) addTx(origin txOrigin, tx *types.Transaction) error {
 
 		slotsFree += slotsRequired(oldTxWithSameNonce) // add old tx slots
 	} else {
-		if account.enqueued.length() == account.maxEnqueued {
+		if account.enqueued.length() == account.maxEnqueued && tx.Nonce != accountNonce {
 			return ErrMaxEnqueuedLimitReached
```
Comment (Stefan-Ethernal) [inline txpool/txpool.go:818]: Basically, we are going to return the error only in case the max enqueued limit is reached and the nonce-gapped transaction is submitted. I'm wondering do we then even need the `maxEnqueued` parameter in this case, and if not is it safe to remove it (though not sure if it is a desirable change and how to protect from spammers in that case)?

File: txpool/txpool_test.go [hunk 2]
```diff
@@ -768,6 +768,43 @@ func TestEnqueueHandler(t *testing.T) {
...
+	t.Run(
+		"accept new tx with nextNonce when enqueued is full",
+		func(t *testing.T) {
+			t.Parallel()
+
+			pool, err := newTestPool()
+			assert.NoError(t, err)
+			pool.SetSigner(&mockSigner{})
+
+			//	mock full enqueued
```
Comment (Stefan-Ethernal) [inline txpool/txpool_test.go]:
```suggestion
			// mock full enqueued
```

File: txpool/txpool.go (hunk 1 above)
Comment (rachit77) [reply txpool/txpool.go:818]: If `maxEnqueued` parameter is not present there than how will you check the number of nonce-gapped transaction for a address and return error accordingly.

**Review by Stefan-Ethernal — APPROVED** [review]

**Review by begmaroman — APPROVED** [review]
