### PR TITLE
[Github] Max fee per gas issue

### LINKED ISSUE #1885: latest development branch - max fee per gas less than block base fee
# [ Subject of the issue ]
## Description
build from source, latest commit https://github.com/0xPolygon/polygon-edge/commit/b467a12202060ae929d81ab0c736a7806f0211c3

started using ./scripts/cluster polybft
blockchain starts, but unable to send any transaction via metamask and this is in error log:

```
2023-09-07T08:40:05.243Z [DEBUG] polygon.server.dispatcher: request: method=eth_call id=0
2023-09-07T08:40:05.243Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 233998548"
2023-09-07T08:40:05.243Z [DEBUG] polygon.server.dispatcher: request: method=eth_call id=1
2023-09-07T08:40:05.243Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 233998548"
2023-09-07T08:40:05.243Z [DEBUG] polygon.server.dispatcher: request: method=eth_call id=2
2023-09-07T08:40:05.243Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 61964075"
2023-09-07T08:40:05.243Z [DEBUG] polygon.server.dispatcher: request: method=eth_call id=3
2023-09-07T08:40:05.243Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 61964075"
2023-09-07T08:40:05.243Z [DEBUG] polygon.server.dispatcher: request: method=eth_call id=4
2023-09-07T08:40:05.243Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 16408423"
2023-09-07T08:40:05.243Z [DEBUG] polygon.server.dispatcher: request: method=eth_call id=5
2023-09-07T08:40:05.243Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 16408423"
2023-09-07T08:40:05.243Z [DEBUG] polygon.server.jsonrpc: handle: response="[{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32600,\"message\":\"max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 233998548\"}},{\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32600,\"message\":\"max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 233998548\"}},{\"jsonrpc\":\"2.0\",\"id\":2,\"error\":{\"code\":-32600,\"message\":\"max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 61964075\"}},{\"jsonrpc\":\"2.0\",\"id\":3,\"error\":{\"code\":-32600,\"message\":\"max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 61964075\"}},{\"jsonrpc\":\"2.0\",\"id\":4,\"error\":{\"code\":-32600,\"message\":\"max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 16408423\"}},{\"jsonrpc\":\"2.0\",\"id\":5,\"error\":{\"code\":-32600,\"message\":\"max fee per gas less than block base fee: address 0x0000000000000000000000000000000000000000, GasFeeCap: 0, BaseFee: 16408423\"}}]"
2023-09-07T08:40:05.243Z [DEBUG] polygon.server.jsonrpc: handle: request="[{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a082310000000000000000000000000000000000000000000000000000000000000105\",\"to\":\"0x0000000000000000000000000000000000001010\"},\"0xB\"]},{\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a082310000000000000000000000000000000000000000000000000000000000000105\",\"to\":\"0x0000000000000000000000000000000000001010\"},\"0x15\"]},{\"id\":2,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a082310000000000000000000000000000000000000000000000000000000000000105\",\"to\":\"0x0000000000000000000000000000000000001010\"},\"0x1F\"]},{\"id\":3,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a0823100000000000000000000000000000000000000000000000000000000deadbeef\",\"to\":\"0x0000000000000000000000000000000000001010\"},\"0xB\"]},{\"id\":4,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a0823100000000000000000000000000000000000000000000000000000000deadbeef\",\"to\":\"0x0000000000000000000000000000000000001010\"},\"0x15\"]},{\"id\":5,\"jsonrpc\":\"2.0\",\"method\":\"eth_call\",\"params\":[{\"data\":\"0x70a0823100000000000000000000000000000000000000000000000000000000deadbeef\",\"to\":\"0x0000000000000000000000000000000000001010\"},\"0x1F\"]}]"

```

## Your environment
- OS and version: ubuntu 22.04
- The version of the Polygon Edge.    
latest development, https://github.com/0xPolygon/polygon-edge/commit/b467a12202060ae929d81ab0c736a7806f0211c3

p.s. even tried starting using

`./polygon-edge server --data-dir ./test-chain-1 --chain genesis.json   --grpc-address :10000 --libp2p :30301 --jsonrpc :10002 --relayer   --num-block-confirmations 2 --seal --log-level DEBUG --price-limit 10000000000000`

still the same

### PR DESCRIPTION
**Pull request by begmaroman**
# Description

eth_call and eth_estimateGas endpoints are simulating transaction execution.
Transaction execution process has tx price so price-related fields should be provided in order to get transaction executed.
Currently, those two endpoints use a transaction object with an empty tx price so the simulation immediately fails.

This PR introduces a logic to apply gas price if a zero value is provided.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### CODE REVIEW

File: docker/local/polygon-edge.sh [hunk 1]
```diff
@@ -2,13 +2,6 @@
 
 set -e
 
-# Check if jq is installed. If not exit and inform user.
-if ! command -v jq >/dev/null 2>&1; then
-  echo "The jq utility is not installed or is not in the PATH. Please install it and run the script again."
-  exit 1
-fi
-
-
```
Comment (Stefan-Ethernal) [inline docker/local/polygon-edge.sh:11]: Why have you removed this check? Does it not make sense when run in a Docker environment?

Comment (begmaroman) [reply docker/local/polygon-edge.sh:11]: It does not make sense because this script runs inside docker container that already has JQ according to the docker file.

File: jsonrpc/eth_endpoint.go [hunk 2]
```diff
@@ -393,23 +393,53 @@ func (e *Eth) GetStorageAt(
...
+		return nil
+	}
+
+	estimatedGasPrice, err := e.getGasPrice()
+	if err != nil {
+		return err
+	}
+
+	if tx.Type == types.DynamicFeeTx {
+		tx.GasFeeCap = new(big.Int).SetUint64(estimatedGasPrice)
```
Comment (rachit77) [inline jsonrpc/eth_endpoint.go:437]: Do we need to assign any value to GasTipCap as well for the checks ?

Comment (begmaroman) [reply jsonrpc/eth_endpoint.go:437]: Nope, no needed

**Review by vcastellm — APPROVED** [review]

**Review by goran-ethernal — APPROVED** [review]
