### PR TITLE
Revise and fix cluster script when ran in docker mode

### LINKED ISSUE #1518: Polygon Supernets Docker Build Fails for v0.8.1 and v0.9.0
# Polygon Supernets Docker Build Fails for v0.8.1 and v0.9.0

## Your environment
- Ubuntu 22
- Edge / Supernets Version v0.8.1 and v0.9.0  
- The branch that causes this issue.
- Locally hosted
- Validators are dockerized

## Steps to reproduce
First, the build error says that `core-contracts/articles` location is not available. This happens because it is not cloned along with the repository and instead needs to be cloned separately. After cloning the core-contracts repo inside the root folder of the Supernets project, the following error is received:

image

### PR DESCRIPTION
**Pull request by begmaroman**
# Description

Revise and fix cluster script when ran in docker mode

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [x] I have tested this code manually

### CODE REVIEW

File: command/rootchain/supernet/stakemanager/stake_manager_deploy.go [hunk 1]
```diff
@@ -143,7 +143,7 @@ func runCommand(cmd *cobra.Command, _ []string) error {
 			contractAddress, err := deployContract(txRelayer, deployerKey,
 				contractsapi.StakeManager, "StakeManager")
 			if err != nil {
-				return err
+				return fmt.Errorf("faield to deploy stake manager: %w", err)
```
Comment (Stefan-Ethernal) [inline command/rootchain/supernet/stakemanager/stake_manager_deploy.go]: Seems to me we are good with returning error without wrapping it, because already the one propagated from `deployContracts` is enough descriptive.

File: command/rootchain/supernet/stakemanager/stake_manager_deploy.go [hunk 2]
```diff
@@ -168,7 +168,7 @@ func runCommand(cmd *cobra.Command, _ []string) error {
 				contractAddress, err := deployContract(txRelayer, deployerKey,
 					contractsapi.RootERC20, "MockERC20StakeToken")
 				if err != nil {
-					return err
+					return fmt.Errorf("faield to deploy mock ERC20 stake token: %w", err)
```
Comment (Stefan-Ethernal) [inline command/rootchain/supernet/stakemanager/stake_manager_deploy.go]: Seems to me we are good with returning error without wrapping it, because already the one propagated from deployContracts is enough descriptive.

File: docker/local/polygon-edge.sh [hunk 3]
```diff
@@ -8,51 +8,125 @@ CHAIN_CUSTOM_OPTIONS=$(tr "\n" " " << EOL
...
-                --consensus ibft \
-                --ibft-validators-prefix-path data- \
-                --bootnode "/dns4/node-1/tcp/1478/p2p/$(echo "$secrets" | jq -r '.[0] | .node_id')" \
-                --bootnode "/dns4/node-2/tcp/1478/p2p/$(echo "$secrets" | jq -r '.[1] | .node_id')"
-         fi
+          "ibft")
+              if [ -f "$GENESIS_PATH" ]; then
+                  echo "Secrets have already been generated."
+              else
+                  echo "Generating iBFT secrets..."
```
Comment (Stefan-Ethernal) [inline docker/local/polygon-edge.sh]:
```suggestion
                  echo "Generating IBFT secrets..."
```

File: docker/local/polygon-edge.sh [hunk 4]
```diff
@@ -8,51 +8,125 @@ CHAIN_CUSTOM_OPTIONS=$(tr "\n" " " << EOL
...
+                  secrets=$("$POLYGON_EDGE_BIN" secrets init --insecure --num 4 --data-dir /data/data- --json)
+                  echo "Secrets have been successfully generated"
+
+                  rm -f /data/genesis.json
+
+                  echo "Generating iBFT Genesis file..."
```
Comment (Stefan-Ethernal) [inline docker/local/polygon-edge.sh]:
```suggestion
                  echo "Generating IBFT Genesis file..."
```

File: docker/local/polygon-edge.sh [hunk 5]
```diff
@@ -8,51 +8,125 @@ CHAIN_CUSTOM_OPTIONS=$(tr "\n" " " << EOL
...
+                --reward-wallet 0xDEADBEEF:1000000 \
                 --bootnode "/dns4/node-1/tcp/1478/p2p/$(echo "$secrets" | jq -r '.[0] | .node_id')" \
-                --bootnode "/dns4/node-2/tcp/1478/p2p/$(echo "$secrets" | jq -r '.[1] | .node_id')"
+                --bootnode "/dns4/node-2/tcp/1478/p2p/$(echo "$secrets" | jq -r '.[1] | .node_id')" \
+                --bootnode "/dns4/node-3/tcp/1478/p2p/$(echo "$secrets" | jq -r '.[2] | .node_id')" \
+                --bootnode "/dns4/node-4/tcp/1478/p2p/$(echo "$secrets" | jq -r '.[3] | .node_id')"
+
+              echo "Deploying stake manager..."
+              "$POLYGON_EDGE_BIN" polybft stake-manager-deploy \
+                --jsonrpc http://$ROOTCHAIN_IP:8545 \
```
Comment (Stefan-Ethernal) [inline docker/local/polygon-edge.sh]: I was running the following command:
```bash
stefan@Stefan:~/go/src/polygon-edge/docker/local$ docker-compose build && docker-compose up -d
```
...and encountered an error here:
`faield to send local transaction: dialing to the given TCP address timed out`

Is it possible that provided rootchain IP address is not correct?

P.s. the same result is when running 
```bash
scripts/cluster polybft --docker
```

File: docker/local/polygon-edge.sh (hunk 4 above)
Comment (begmaroman) [reply docker/local/polygon-edge.sh]: Fixed

File: docker/local/polygon-edge.sh (hunk 3 above)
Comment (begmaroman) [reply docker/local/polygon-edge.sh]: Fixed

File: command/rootchain/supernet/stakemanager/stake_manager_deploy.go (hunk 2 above)
Comment (begmaroman) [reply command/rootchain/supernet/stakemanager/stake_manager_deploy.go]: Agree

File: command/rootchain/supernet/stakemanager/stake_manager_deploy.go (hunk 1 above)
Comment (begmaroman) [reply command/rootchain/supernet/stakemanager/stake_manager_deploy.go]: Agree

**Comment by Stefan-Ethernal** [comment]
Also thinking out loud… does it make sense and is it feasible merging ‘polygon-edge.sh’ and ‘cluster’ script into the one?

File: docker/local/polygon-edge.sh (hunk 5 above)
Comment (begmaroman) [reply docker/local/polygon-edge.sh]: Yeah, the rootchain address is not correct but it works on my local env. Did you use the latest version of it?

Comment (Stefan-Ethernal) [reply docker/local/polygon-edge.sh]: Indeed it was the latest version… Not sure, worth that somebody else tries out.

Comment (begmaroman) [reply docker/local/polygon-edge.sh]: Try now

Comment (Stefan-Ethernal) [reply docker/local/polygon-edge.sh]: Working fine now.

Comment (Stefan-Ethernal) [reply docker/local/polygon-edge.sh]: Working fine now.

**Review by Stefan-Ethernal — APPROVED** [review]

**Review by Stefan-Ethernal — APPROVED** [review]

**Review by vcastellm — APPROVED** [review]
