### PR TITLE
Expand fallback errors in tx relayer when dynamic fee tx sending fails

### LINKED ISSUE #1997: Error: failed sending StakeManager contract deploy transaction: failed to get max priority fee per gas: {"code":-32601,"message":"Method not found"}
# Error on `polygon-edge polybft stake-manager-deploy`

## Description
I'm trying to deploy the stake manager contract on my Layer 1 (Besu) with the command `polygon-edge polybft stake-manager-deploy` but I'm getting the following error:

```Error: failed sending StakeManager contract deploy transaction: failed to get max priority fee per gas: {"code":-32601,"message":"Method not found"}```

Full command:

```bash
    polygon-edge polybft stake-manager-deploy \
        --private-key "${L1_ACCOUNT_PK}" \
        --genesis ${OUT_FOLDER}/genesis.json \
        --jsonrpc ${RPC_URL} \
        --stake-token ${STAKE_TOKEN_ADDRESS} \
        --proxy-contracts-admin ${L2_ACCOUNT_ADDRESS} \
        --json
```

Can this be related to the new tx pool implementation on Besu? 
Ref: https://github.com/hyperledger/besu/releases/tag/23.10.0

EDIT: 
> Tested it on different Besu versions, one with new and another with legacy tx pool. Same error.

## Your environment
- MacOs
- polygon-edge 1.3.1
- besu 23.10.0

### PR DESCRIPTION
**Pull request by Stefan-Ethernal**
# Description

This PR adds a "method not found" error which also triggers the fallback mechanism from sending dynamic fee tx to legacy tx in tx relayer. This was due to the fact that the Besu client does not yet implement the `eth_maxPriorityFeePerGas` function and therefore sends dynamic fee tx when bootstrapping Supernets fails. This is a mitigation measure to try by sending legacy tx as a fallback.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [ ] I have tested this code manually

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

File: txrelayer/txrelayer.go [hunk 1]
```diff
@@ -90,13 +95,18 @@ func (t *TxRelayerImpl) Call(from ethgo.Address, to ethgo.Address, input []byte)
...
-			// downgrade transaction to legacy tx type and resend it
-			txn.Type = ethgo.TransactionLegacy
-			txn.GasPrice = 0
-
-			return t.SendTransaction(txn, key)
+		if txn.Type != ethgo.TransactionLegacy {
+			for _, fallbackErr := range dynamicFeeTxFallbackErrs {
+				if strings.Contains(
+					strings.ToLower(fallbackErr.Error()),
+					strings.ToLower(err.Error())) {
```
Comment (refl3ction) [inline txrelayer/txrelayer.go:102]:
```suggestion
					strings.ToLower(err.Error()),
					strings.ToLower(fallbackErr.Error())) {
```

File: txrelayer/txrelayer.go [hunk 2]
```diff
@@ -90,13 +95,18 @@ func (t *TxRelayerImpl) Call(from ethgo.Address, to ethgo.Address, input []byte)
...
+					// "downgrade" transaction to the legacy tx type and resend it
```
Comment (0xDones) [inline txrelayer/txrelayer.go]:
```suggestion
				if strings.Contains(
					strings.ToLower(err.Error()),
					strings.ToLower(fallbackErr.Error())) {
					// "downgrade" transaction to the legacy tx type and resend it
```
I think the order of the arguments is inverted.

**Review by goran-ethernal — APPROVED** [review]

**Review by dusan-maksimovic — APPROVED** [review]
