### PR TITLE
Fix incorrect call to decreaseSlots() when no tx was deleted

### LINKED ISSUE #231: `addImpl` in txpool.go incorrectly reports that the pool is full, even if empty, due to overflow
### Description
`addImpl` in txpool.go incorrectly reports that the pool is full, even if empty, causing broadcast failures. This causes downstream txn delays.

```
2021-11-19T16:22:26.745-0500 [ERROR] polygon.txpool: failed to add broadcasted txn: err="txpool is full"
```

It looks like the `txpool.slot` variable seems to have overflowed (see logs below). So this is two potentially related issues:

1. Node is incorrectly reporting txpool is full as a result of below
2. `txpool.slot` is overflowing

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 6efebc6a92f885082620ed2a8d59e37d4d27074c
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
Start a cluster with 4 nodes. Send a basic transaction (send 10 ETH) to the fourth node. Observe that on the other nodes, in `addImpl`, an error will be reported that the txpool is full.
* Where the issue is, if you know <br />

https://github.com/0xPolygon/polygon-sdk/blob/develop/txpool/txpool.go#L589 is an overflow if `t.slots = 0`

* Which commands triggered the issue, if any

### Expected behaviour

Node should accept valid gossiped non-local transaction

### Actual behaviour

Node rejects valid gossiped non-local transaction

### Logs

image

image

image

### Proposed solution

It looks like the discard function does not correctly consider the case with remoteTxns length = 0

### PR DESCRIPTION
**Pull request by dbrajovic**
# Description

This PR addresses the issue [#231](https://github.com/0xPolygon/polygon-sdk/issues/231). The bug was occurring specifically due to a second call to decreaseSlots() (during ResetWithHeader()) for a transaction that was popped previously, thus resulting in an underflow of t.slots.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [ ] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Essentially, the underflow of `t.slots` happens exclusively when a node is a proposer - here’s the flow:

Proposer running in `AcceptState` calls `buildBlock()`, so the first `Pop()` of the transaction happens implicitly calling `decreaseSlots(0`.
Afterwards, proposer moves into `ValidateState` where it reaches `insertBlock()`. Inside, a call to TxPool's `ResetWithHeader()` is made which leads to clearing out the mined transactions.
This is where the second call to `Pop()` (`decreaseSlots()`) happens, but the transaction was already gone. `t.pendingQueue.Delete(tx)` doesn’t do delete at this point (since the tx was gone already), but the decrease in slots happens anyhow resulting in the underflow.

### CODE REVIEW

**Review by zivkovicmilos — APPROVED** [review]
Lookin' good 💯

File: txpool/txpool.go [hunk 1]
```diff
@@ -841,14 +842,17 @@ func (t *txPriceHeap) Length() uint64 {
 	return uint64(len(t.index))
 }
 
-func (t *txPriceHeap) Delete(tx *types.Transaction) {
+func (t *txPriceHeap) Delete(tx *types.Transaction) *types.Transaction {
```
Comment (brkomir) [inline txpool/txpool.go]: Maybe we should return a boolean value here instead of transaction, so we can do if statement with an "ok" check

**Review by brkomir — APPROVED** [review]
I have left a comment, nothing major. Overall looks ok.
Have you tried to add some tests for this?

**Review by Kourin1996 — APPROVED** [review]
Looks good apart from @brkomir's comment

File: txpool/txpool.go (hunk 1 above)
Comment (dbrajovic) [reply txpool/txpool.go]: [Changed](https://github.com/0xPolygon/polygon-sdk/pull/251/commits/5aa22e1de9f29b6cb1dded78f184a018649569c6)

File: txpool/txpool.go [hunk 2]
```diff
@@ -841,14 +842,19 @@ func (t *txPriceHeap) Length() uint64 {
...
-func (t *txPriceHeap) Delete(tx *types.Transaction) {
+func (t *txPriceHeap) Delete(tx *types.Transaction) bool {
 	t.lock.Lock()
 	defer t.lock.Unlock()
 
-	if item, ok := t.index[tx.Hash]; ok {
-		heap.Remove(t.heap, item.index)
-		delete(t.index, tx.Hash)
+	item, ok := t.index[tx.Hash]
+	if !ok {
```
Comment (brkomir) [inline txpool/txpool.go:850]: you can simplify this additionally since you basically return value of the ok
if ok {
// do delete and heap.remove
}

return ok

**Review by brkomir — APPROVED** [review]

**Review by lazartravica — APPROVED** [review]
