### PR TITLE
Fix multiple addresses issue with same libp2p id

### LINKED ISSUE #166: Panic due to libp2p addresses conversion causes node crash
### Description

After running a node on a testchain for a while, randomly the node panics with the same error as in https://github.com/0xPolygon/polygon-sdk/issues/160

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 18e93179d1303356b4f77b1b50cc46390d61b25c
* branch that causes this issue `fix/sync-issue`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Logs

```


2021-09-27T21:28:24.149Z | Sep 27 21:28:22 ip-172-31-44-61 web: 2021-09-27T21:28:22.058Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=816768 hash=0xc565431ff24d2860a3752b65a3ff06520cc1c7396b87939891d784cdfffe6212
-- | --
  | 2021-09-27T21:28:24.149Z | Sep 27 21:28:24 ip-172-31-44-61 web: 2021-09-27T21:28:24.021Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=816769 hash=0x1754444b09e71fc569b62a960a08d38ea7d05847ff5be90b20caaba4a6543e6d
  | 2021-09-27T21:28:24.149Z | Sep 27 21:28:24 ip-172-31-44-61 web: 2021-09-27T21:28:24.023Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=816769 hash=0x1754444b09e71fc569b62a960a08d38ea7d05847ff5be90b20caaba4a6543e6d
  | 2021-09-27T21:28:24.149Z | Sep 27 21:28:24 ip-172-31-44-61 web: 2021-09-27T21:28:24.023Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=816769 hash=0x1754444b09e71fc569b62a960a08d38ea7d05847ff5be90b20caaba4a6543e6d
  | 2021-09-27T21:28:25.399Z | Sep 27 21:28:24 ip-172-31-44-61 web: 2021-09-27T21:28:24.025Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=816769 hash=0x1754444b09e71fc569b62a960a08d38ea7d05847ff5be90b20caaba4a6543e6d
  | 2021-09-27T21:28:25.399Z | Sep 27 21:28:25 ip-172-31-44-61 web: 2021-09-27T21:28:25.332Z [DEBUG] polygon.jsonrpc: handle: request={"method":"eth_blockNumber","params":[],"id":55,"jsonrpc":"2.0"}
  | 2021-09-27T21:28:25.399Z | Sep 27 21:28:25 ip-172-31-44-61 web: 2021-09-27T21:28:25.332Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=55
  | 2021-09-27T21:28:26.150Z | Sep 27 21:28:25 ip-172-31-44-61 web: 2021-09-27T21:28:25.332Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":55,"result":"0xc6ee6"}
  | 2021-09-27T21:28:26.150Z | Sep 27 21:28:26 ip-172-31-44-61 web: 2021-09-27T21:28:26.022Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=816770 hash=0x515634a2ab038cbd6228e1dd23cec46ae57e207905dc5c906e5c618bfd5635b0
  | 2021-09-27T21:28:26.150Z | Sep 27 21:28:26 ip-172-31-44-61 web: 2021-09-27T21:28:26.036Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=816770 hash=0x515634a2ab038cbd6228e1dd23cec46ae57e207905dc5c906e5c618bfd5635b0
  | 2021-09-27T21:28:26.150Z | Sep 27 21:28:26 ip-172-31-44-61 web: 2021-09-27T21:28:26.039Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=816770 hash=0x515634a2ab038cbd6228e1dd23cec46ae57e207905dc5c906e5c618bfd5635b0
  | 2021-09-27T21:28:27.400Z | Sep 27 21:28:26 ip-172-31-44-61 web: 2021-09-27T21:28:26.040Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=816770 hash=0x515634a2ab038cbd6228e1dd23cec46ae57e207905dc5c906e5c618bfd5635b0
  | 2021-09-27T21:28:27.400Z | Sep 27 21:28:27 ip-172-31-44-61 web: 2021-09-27T21:28:27.204Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232328811,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T21:28:27.400Z | Sep 27 21:28:27 ip-172-31-44-61 web: 2021-09-27T21:28:27.204Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.681811232328811e+15
  | 2021-09-27T21:28:28.151Z | Sep 27 21:28:27 ip-172-31-44-61 web: 2021-09-27T21:28:27.204Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232328811,"result":"0xc6ee6"}
  | 2021-09-27T21:28:28.151Z | Sep 27 21:28:28 ip-172-31-44-61 web: 2021-09-27T21:28:28.019Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=816771 hash=0xb37a2cb263b2a3d902bba22a2bc6b68704b9d59900609e3f97a3d4086363457c
  | 2021-09-27T21:28:28.151Z | Sep 27 21:28:28 ip-172-31-44-61 web: 2021-09-27T21:28:28.020Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=816771 hash=0xb37a2cb263b2a3d902bba22a2bc6b68704b9d59900609e3f97a3d4086363457c
  | 2021-09-27T21:28:28.151Z | Sep 27 21:28:28 ip-172-31-44-61 web: 2021-09-27T21:28:28.022Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=816771 hash=0xb37a2cb263b2a3d902bba22a2bc6b68704b9d59900609e3f97a3d4086363457c
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:28 ip-172-31-44-61 web: 2021-09-27T21:28:28.026Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=816771 hash=0xb37a2cb263b2a3d902bba22a2bc6b68704b9d59900609e3f97a3d4086363457c
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: panic: Not supported
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: goroutine 23514 [running]:
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: github.com/0xPolygon/polygon-sdk/network.AddrInfoToString(0xc003d65a98)
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/network/server.go:594 +0xa7
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: github.com/0xPolygon/polygon-sdk/network.(*discovery).FindPeers(0xc0004a4300, {0x10f0fb0, 0xc0043c9800}, 0xc0034d2280)
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/network/discovery.go:255 +0x30d
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: github.com/0xPolygon/polygon-sdk/network/proto._Discovery_FindPeers_Handler.func1({0x10f0fb0, 0xc0043c9800}, {0xd399c0, 0xc0034d2280})
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/network/proto/discovery_grpc.pb.go:82 +0x78
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: github.com/0xPolygon/polygon-sdk/network/grpc.interceptor({0x10f0d80, 0xc0036f3950}, {0xd399c0, 0xc0034d2280}, 0xc003d65bb8, 0xc0042cf200)
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/network/grpc/grpc.go:53 +0xef
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: github.com/0xPolygon/polygon-sdk/network/proto._Discovery_FindPeers_Handler({0xd513e0, 0xc0004a4300}, {0x10f0d80, 0xc0036f3950}, 0xc004c33c20, 0x1006ed8)
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/network/proto/discovery_grpc.pb.go:84 +0x138
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003508c0, {0x10ff4f0, 0xc00013b800}, 0xc001c3af00, 0xc00048b800, 0x197d360, 0x0)
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/vendor/google.golang.org/grpc/server.go:1217 +0xc8f
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: google.golang.org/grpc.(*Server).handleStream(0xc0003508c0, {0x10ff4f0, 0xc00013b800}, 0xc001c3af00, 0x0)
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/vendor/google.golang.org/grpc/server.go:1540 +0xa2a
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: google.golang.org/grpc.(*Server).serveStreams.func1.2()
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/vendor/google.golang.org/grpc/server.go:878 +0x98
  | 2021-09-27T21:28:30.404Z | Sep 27 21:28:30 ip-172-31-44-61 web: created by google.golang.org/grpc.(*Server).serveStreams.func1
  | 2021-09-27T21:28:30.654Z | Sep 27 21:28:30 ip-172-31-44-61 web: /var/app/staging/polygon-sdk/vendor/google.golang.org/grpc/server.go:876 +0x294


```

### Proposed solution

I found this same error in the linked issue. Perhaps a node is somehow managing to set two addresses or something?

### PR DESCRIPTION
**Pull request by Kourin1996**
# Description

This PR fixes the issue that node throws panic if peer reconnect with same ID but different IP.
This issue happens after following steps:
(1) node disconnects from peer
(2) the peer change IP and reconnect to the node
(3) the node throw panic

PolygonSDK currently doesn't support multiple addresses and node keep an address after disconnected. So there will be multiple addresses per one ID when peer change IP (e.g. using NAT feature) and connect to node again.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

File: network/dial_queue_test.go [hunk 1]
```diff
@@ -46,3 +50,111 @@ func TestDialQueue(t *testing.T) {
 		t.Fatal("timeout")
 	}
 }
+
+func TestDel(t *testing.T) {
+	type task struct {
+		id     string
+		action string // "add"/"delete"/"pop"
```
Comment (zivkovicmilos) [inline network/dial_queue_test.go]: I would take this 1 step further and make sure these values: `add`, `delete` and `pop` are constants (in a sense enums), so whenever we reference them in code, we know exactly which value we're hitting

File: network/server_test.go [hunk 2]
```diff
@@ -14,6 +14,21 @@ import (
...
+	key, err := ReadLibp2pKey(dir)
+	assert.NoError(t, err)
+	t.Cleanup(func() {
+		// remove directory after test is done
+		assert.NoError(t, os.RemoveAll(dir))
+	})
+
+	return key, dir
+}
+
```
Comment (zivkovicmilos) [inline network/server_test.go]: @Kourin1996 
Do you think we should maybe move this out to the `helper` package, or leave it here?

Just a thought

**Review by zivkovicmilos — APPROVED** [review]
Awesome work on the coverage tests 💯 

Lookin' good 👍

File: network/dial_queue_test.go (hunk 1 above)
Comment (Kourin1996) [reply network/dial_queue_test.go:57]: I tried but there will be a cyclic dependency (because `ReadLibp2pKey` is defined in network package)

Comment (zivkovicmilos) [reply network/dial_queue_test.go]: I see 🧐

What about declaring it within the test file?

File: network/server_test.go (hunk 2 above)
Comment (Kourin1996) [reply network/server_test.go]: I tried but there will be a cyclic dependency (because ReadLibp2pKey is defined in network package)

File: network/dial_queue_test.go (hunk 1 above)
Comment (Kourin1996) [reply network/dial_queue_test.go]: Fixed in https://github.com/0xPolygon/polygon-sdk/pull/156/commits/99afa50917c33cb3dd8d8d4d705af45cc56a7776

**Review by lazartravica — APPROVED** [review]

**Review by munna0908 — APPROVED** [review]
LGTM 🚀

**Comment by lazartravica** [comment]
@Kourin1996 you can merge this PR 👍
