### PR TITLE
Apply trace patch for CALL trace issue

### LINKED ISSUE #1590: Tracer bugs related to `SSTORE` and `CALL`/`STATICCALL`
Tracer bugs related to `SSTORE` and `CALL`/`STATICCALL`

## Description
* For `SSTORE` tracer has permuted `key` and `value` reading from the stack
* `CALL` instruction is not correctly traced. New environment (stack/memory/storage) need to be created for message call, and at the moment they are mixed. `CALL` captures memory/storage, then external call overwrites these, and eventually on `ExecuteState` `CALL` reads random values for stack/memory/storage.

## Your environment
- Ubuntu 20.04/22.04
- 0.8

## Steps to reproduce
- Trace any block with smart contracts performing `CALL` to other smart contract
- Examine the trace for `CALL`

## Proposed solution
Solution implemented for the need of our project fixing `SSTORE` and using array for memory/storage/stack to create new environment for every `CALL` trace [HERE](https://github.com/topos-network/polygon-edge/commit/5a51279d93b1fabb9190ab4b1d056339f050fc38)

### PR DESCRIPTION
**Pull request by vcastellm**
# Description

There's a mismatch in the `debug_traceTransaction` endpoint output between geth and Edge, specifically:

- For SSTORE tracer has permuted key and value reading from the stack
- CALL instruction is not correctly traced. New environment (stack/memory/storage) need to be created for message call, and at the moment they are mixed.

This PR fixes both issues, permuting the order of SSTORE ops output in the trace, and creating a new EVM environment for each sub CALL in the tracing output.

Fixes #1590 

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [x] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it

### CODE REVIEW

**Comment by vcastellm** [comment]
This is the diff before and after the changes for a sample contract call:

image

File: state/runtime/tracer/structtracer/tracer.go [hunk 1]
```diff
@@ -55,17 +55,22 @@ type StructTracer struct {
 	consumedGas uint64
 	output      []byte
 	err         error
-	storage     map[types.Address]map[types.Hash]types.Hash
 
-	currentMemory []byte
-	currentStack  []*big.Int
+	storage       []map[types.Address]map[types.Hash]types.Hash
+	currentMemory []([]byte)
```
Comment (igorcrevar) [inline state/runtime/tracer/structtracer/tracer.go:60]: why using parenthesis, why not just 	`currentMemory [][]byte ` ?
same goes for `currentStack  []([]*big.Int)`

Comment (vcastellm) [reply state/runtime/tracer/structtracer/tracer.go:60]: It was just for readability I guess, I'm ok with both forms

**Review by goran-ethernal — APPROVED** [review]

**Review by Stefan-Ethernal — APPROVED** [review]
