### PR TITLE
Return Revert result as Data

### LINKED ISSUE #1350: Custom solidity errors (introduced in 0.8.4) not supported
# Custom solidity errors (introduced in solidity 0.8.4) not supported
## Description
Hi,

I haven't been capable of receiving proper error data when interacting with some contracts deployed to Edge chains. These contracts leverage solidity >0.8.4 custom errors, used with revert in the `revert MyError(myData)` manner.

Thinking the problem was on the js client side, I jumped on an older `ethers` issue. Investigating with their team, it seems the problem is coming from Edge which is not returning the error data at all.

Please find the details of my setup at the very bottom of the issue on `ethers`:
https://github.com/ethers-io/ethers.js/issues/1493

## Your environment
- macOS v13.2.1.
- Edge v0.8.0.
- Local docker setup with docker image built from `/docker/local`

## Steps to reproduce
- Run a polygon-edge chain
- Deploy the contract provided [here](https://github.com/ethers-io/ethers.js/issues/1493#issuecomment-1490610951)
- Interact with the contract to trigger the `revert`
- Notice that your js client (`ethers` or `web3`) is not parsing any information from the error (we only know that the call reverted)

## Expected behavior
- The explicit error should be returned

### PR DESCRIPTION
**Pull request by vcastellm**
# Description

This allows returning custom revert errors from solidity, they are ABI encoded functions that can represent rich and gas efficient revert messages.

Details of custom errors: https://blog.soliditylang.org/2021/04/21/custom-errors/

This is the implementation expected by ethers.js and web3.js and the format go-ethereum chose https://github.com/ethereum/go-ethereum/issues/19027#issuecomment-640500608

image

This PR implements it following this format.

Fixes https://github.com/0xPolygon/polygon-edge/issues/1350

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [ ] I have tested this code manually

### CODE REVIEW

File: jsonrpc/codec.go [hunk 1]
```diff
@@ -93,6 +93,26 @@ func (e *ObjectError) Error() string {
 	return string(data)
 }
 
+func (e *ObjectError) MarshalJSON() ([]byte, error) {
+	var ds string
+
+	if data, ok := e.Data.([]byte); ok {
+		if len(data) > 0 {
```
Comment (igorcrevar) [inline jsonrpc/codec.go]: neatpick: `ok && len(data) > 0`

File: jsonrpc/codec.go [hunk 2]
```diff
@@ -93,6 +93,26 @@ func (e *ObjectError) Error() string {
...
+			ds = "0x" + string(data)
```
Comment (goran-ethernal) [inline jsonrpc/codec.go]:
```suggestion
			ds = types.EncodeBytes(data)
```

**Review by Stefan-Ethernal — APPROVED** [review]

**Review by goran-ethernal — APPROVED** [review]

**Review by igorcrevar — APPROVED** [review]

File: jsonrpc/codec.go (hunk 2 above)
Comment (vcastellm) [reply jsonrpc/codec.go]: No because `EncodeBytes` hex encode the data, and the data is already hex encoded.

File: jsonrpc/codec.go (hunk 1 above)
Comment (vcastellm) [reply jsonrpc/codec.go]: https://github.com/0xPolygon/polygon-edge/pull/1566/commits/7faef92dad92e19e77160809aff06f8594198637
