### PR TITLE
Fix loadbot gas metric collection

### LINKED ISSUE #494: Loadbot crash: concurrent map writes
### Description

Sometimes (1 of many times) such error log might be generated.

### Your environment

* Fedora 32
* v0.1.0 (f59d3ca12586a910b3f8744ffbefdbbaa19a9e02)
* develop

### Steps to reproduce

Run Loadbot in plain value transactions mode (parameters: 3000 txs, value 0x100, 600 tps).

### Expected behaviour

Something like:
```
=====[LOADBOT RUN]=====

[COUNT DATA]
Transactions submitted = 3000
Transactions failed    = 0

[APPROXIMATE TPS]
Approximate number of transactions per second = 111

[TURN AROUND DATA]
Average transaction turn around = 11.161490s
Fastest transaction turn around = 2.002610s
Slowest transaction turn around = 22.024990s
Total loadbot execution time    = 27.030140s
...
```

### Actual behaviour

Tell us what happens instead

```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 6185 [running]:
runtime.throw(0x1a6b012, 0x15)
        /usr/lib/golang/src/runtime/panic.go:1117 +0x72 fp=0xc0044e1ea8 sp=0xc0044e1e78 pc=0x439012
runtime.mapassign_fast64(0x16bb2c0, 0xc00059d5c0, 0x155, 0xc004486000)
        /usr/lib/golang/src/runtime/map_fast64.go:176 +0x325 fp=0xc0044e1ee8 sp=0xc0044e1ea8 pc=0x414925
github.com/0xPolygon/polygon-edge/command/loadbot.(*Loadbot).calculateGasMetrics.func1(0x100000000000000, 0xc00024a690)
        /root/polygon-edge/command/loadbot/helper.go:92 +0xfe fp=0xc0044e1f78 sp=0xc0044e1ee8 pc=0x150f7be
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0035a69c0, 0xc0035a6b70)
        /root/polygon-edge/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59 fp=0xc0044e1fd0 sp=0xc0044e1f78 pc=0xf5e2d9
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0044e1fd8 sp=0xc0044e1fd0 pc=0x46f581
created by golang.org/x/sync/errgroup.(*Group).Go
        /root/polygon-edge/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

### Logs

Full log of my experiment (running loadbot sequentially on 37 nodes, one by one).
[hetzner-37-cpx51.log](https://github.com/0xPolygon/polygon-edge/files/8459576/hetzner-37-cpx51.log)

### Proposed solution

First 24 runs succeeded, 25th run failed with this error.

### PR DESCRIPTION
**Pull request by zivkovicmilos**
# Description

This PR fixes a minor issue with concurrent loadbot gas metrics calculation.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

Regular loadbot deployment tests.

### CODE REVIEW

File: command/loadbot/execution.go [hunk 1]
```diff
@@ -102,29 +111,44 @@ type Loadbot struct {
...
+			Blocks: make(map[uint64]GasMetrics),
+		},
+	}
+}
+
+func (l *Loadbot) needsContractMetrics() bool {
+	return l.cfg.GeneratorMode == deploy ||
+		l.cfg.GeneratorMode == erc20 ||
+		l.cfg.GeneratorMode == erc721
 }
```
Comment (Kourin1996) [inline command/loadbot/execution.go]: Why separate to 2 methods `initContractMetrics` and `needsContractMetrics`?
How about adding a keyword to `initContractMetrics` so that it may initialize contract metrics
`mightInitContractMetrics`, `initContractMetricsIfNeeded`

File: command/loadbot/helper.go [hunk 2]
```diff
@@ -72,58 +70,94 @@ func calculateAvgBlockUtil(gasData map[uint64]GasMetrics) float64 {
...
+func getBlockGasMetrics(
+	jsonClient *jsonrpc.Client,
+	blockNums map[uint64]struct{},
+) (*BlockGasMetrics, error) {
+	var (
+		errors          = make([]error, 0)
+		blockGasMetrics = &BlockGasMetrics{
+			Blocks: make(map[uint64]GasMetrics),
+		}
+		errorsLock sync.Mutex
```
Comment (Kourin1996) [inline command/loadbot/helper.go]: Why not swap the order between `blockGasMetrics` and `errorsLock`?

Comment (zivkovicmilos) [reply command/loadbot/helper.go]: You're right, it makes more sense to bundle them 👍 

Fixed:

[09a7e48](https://github.com/0xPolygon/polygon-edge/pull/497/commits/09a7e489dd31e869163596a27abb7e13c9849b10)

File: command/loadbot/execution.go (hunk 1 above)
Comment (zivkovicmilos) [reply command/loadbot/execution.go]: Fixed 👍 

[773dcd1](https://github.com/0xPolygon/polygon-edge/pull/497/commits/773dcd1fd3f245769c16491b3f09df9188aec227)

**Review by Kourin1996 — APPROVED** [review]
LGTM

File: command/loadbot/helper.go [hunk 3]
```diff
@@ -72,58 +70,94 @@ func calculateAvgBlockUtil(gasData map[uint64]GasMetrics) float64 {
...
+	addError := func(fetchErr error) {
+		errorsLock.Lock()
+		defer errorsLock.Unlock()
+
+		errors = append(errors, fetchErr)
+	}
+
+	// For each block number, fetch the corresponding
+	// block info data
+	for blockNum := range blockNums {
```
Comment (dbrajovic) [inline command/loadbot/helper.go:126]: Commit suggestion:

```
	queryBlockInfo := func(
		blockNum uint64,
	) {

		//	query node for block
		blockInfo, err := jsonClient.Eth().GetBlockByNumber(
			web3.BlockNumber(blockNum),
			false,
		)
		if err != nil {
			addError(fmt.Errorf("could not fetch block %d by number, %w", blockNum, err))

			return
		}

		//	update metrics
		blockGasMetrics.AddBlockMetric(
			blockNum,
			GasMetrics{
				GasUsed:     blockInfo.GasUsed,
				GasLimit:    blockInfo.GasLimit,
				Utilization: calculateBlockUtilization(blockInfo.GasUsed, blockInfo.GasLimit),
			},
		)
	}

	// For each block number, fetch the corresponding
	// block info data
	for blockNum := range blockNums {
		wg.Add(1)

		go func(blockNum uint64) {
			defer wg.Done()

			queryBlockInfo(blockNum)
		}(blockNum)
	}

	wg.Wait()
```

**Review by dbrajovic — APPROVED** [review]

File: command/loadbot/helper.go (hunk 3 above)
Comment (zivkovicmilos) [reply command/loadbot/helper.go:126]: Added 👍 

[97ede57](https://github.com/0xPolygon/polygon-edge/pull/497/commits/97ede57f37122e24a2d71d60ed24c8ed00dcaeea)
