### PR TITLE
Fix/ibft syncer issue

### LINKED ISSUE #152: Error `polygon.consensus.syncer: failed to notify` after adding + removing peers/validators
### Description

I've seen many occurrences of this new error after adding and removing peers and validators to the original validator set:
```
2021-09-10T16:32:00.056Z [ERROR] polygon.consensus.syncer: failed to notify: err="rpc error: code = Unavailable desc = connection error: desc = "transport: failed to write client preface: stream reset""
```

It seems as if the active nodes may somehow still maintain a reference to old (removed) peers and/or validators even so they are no longer visible when running the SDK commands:

```
./main peers list
```
and
```
./main ibft snapshot
```

I've made sure to run `./main ibft propose --vote drop` on greater than 50% of active validators (removing it from the list that `ibft snapshot` returns, as expected) but it seems I only see an even greater frequency of the same error -- for reference below, validators were removed at 12:08 and 12:14:
Screen Shot 2021-09-10 at 12 40 42 PM

### Your environment

* OS and version `OSX Big Sur 11.5.2 (20G95)`
* version of the Polygon SDK `0b2cc26`
* branch that causes this issue `develop`

### Steps to reproduce

1. Run `ibft server` for 4 bootnodes
2. Add peer `new_node1` using `peers add`
3. Vote in new validator `new_node1` using `ibft propose --vote auth`
4. Vote in new validator `new_node2` using `ibft propose --vote auth`
5. Stop validators `new_node1`, `new_node2`
6. Drop both new validators `new_node1`, `new_node2` using `ibft propose --vote drop`
7. Verify that `peers list` shows 3 peers for each node (as expected for 4 bootnodes)
8. Verify that `ibft snapshot` shows 4 validator addresses total (as expected for 4 bootnodes)
9. See new errors in logs

### Expected behaviour

I shouldn't any of these errors.

### Actual behaviour

I see many of these errors in the logs on all 4 bootnodes.

I initially suspected that the validators were stopped prematurely without being dropped by the active validators but when attempting to remove them from the validator list, it seems that I only see more of the same error in the logs.

### PR DESCRIPTION
**Pull request by munna0908**
# Description

This PR resolves issue #152 

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

File: protocol/syncer.go [hunk 1]
```diff
@@ -315,6 +326,8 @@ func (s *Syncer) BestPeer() *syncPeer {
 
 // HandleUser is a helper method that is used to handle new user connections within the Syncer
 func (s *Syncer) HandleUser(peerID peer.ID, conn *grpc.ClientConn) error {
+	s.peersLock.Lock()
+	defer s.peersLock.Unlock()
```
Comment (Kourin1996) [inline protocol/syncer.go]: There is a lag until you get the status from peer. So it might be a good idea to lock after you get response from peer.

**Review by Kourin1996 — CHANGES_REQUESTED** [review]

File: protocol/syncer.go [hunk 2]
```diff
@@ -144,7 +144,8 @@ type Syncer struct {
 	logger     hclog.Logger
 	blockchain blockchainShim
 
-	peers map[peer.ID]*syncPeer // TODO: Remove
+	peers     map[peer.ID]*syncPeer
+	peersLock sync.RWMutex
```
Comment (zivkovicmilos) [inline protocol/syncer.go]: I think we can improve performance here even more than with using a RW mutex.

Since our peers are inside of a map, we currently have only 1 mutex that, when you grab it, you hold the access to the entire map.
This means that if I'm accessing the `syncPeer` at key value `peerID1` (not actual peer.ID), I'll be holding up any process that wants to access the `syncPeer` at key value `peerID2`.

I have two suggestions:
1. Create a separate mux map, where you would map the peer.ID -> mux. This way, you hold the mux to a single entry, not the entire map
2. Use `sync.Map` to accomplish the behavior mentioned in the first suggestion. [Godoc](https://pkg.go.dev/sync#Map). This is definitely the better route, as this solution takes into account any optimizations that we might miss.

**Review by zivkovicmilos — CHANGES_REQUESTED** [review]
Please check out the proposed changes, otherwise it looks good 💯

File: protocol/syncer.go [hunk 3]
```diff
@@ -219,15 +220,18 @@ const syncerV1 = "/syncer/0.1"
...
+	s.peersLock.RUnlock()
 	if ok {
 		p.appendBlock(b)
 	}
 }
 
 // Broadcast broadcasts a block to all peers
 func (s *Syncer) Broadcast(b *types.Block) {
+	s.peersLock.RLock()
+	defer s.peersLock.RUnlock()
```
Comment (Vuksan) [inline protocol/syncer.go]: Please, only lock+unlock around the statements that actually use the resource.
In this case that would be around the for loop on L249.

Although in human time initialization is fast, there is no need to have a resource lock and a thread waiting when the resource is not yet demanded.

File: protocol/syncer.go [hunk 4]
```diff
@@ -296,7 +306,8 @@ func (s *Syncer) Start() {
 func (s *Syncer) BestPeer() *syncPeer {
 	var bestPeer *syncPeer
 	var bestTd *big.Int
-
+	s.peersLock.RLock()
+	defer s.peersLock.RUnlock()
```
Comment (Vuksan) [inline protocol/syncer.go]: Please move `RUnlock()` call to ~L316, just after the for loop. (no need for `defer` then)

File: protocol/syncer.go (hunk 1 above)
Comment (Vuksan) [reply protocol/syncer.go]: I agree with Yoshiki.

Please, only lock+unlock around the statements that actually use the resource.
In this case that would be around the statement on L342.

File: protocol/syncer_test.go [hunk 5]
```diff
@@ -0,0 +1,142 @@
...
+	go sync1.Start()
+	go sync2.Start()
+
+	network.MultiJoin(t, srv0, srv1, srv0, srv2, srv1, srv2)
+	time.Sleep(1 * time.Second)
+	//Disconnect peer2
+	srv1.Disconnect(srv2.AddrInfo().ID, "testing")
+	time.Sleep(1 * time.Second)
+	//server1 syncer should not have disconnected peer
+	assert.NotContains(t, sync1.peers, srv2.AddrInfo().ID)
```
Comment (Vuksan) [inline protocol/syncer_test.go]: You meant `should have disconnected` right? Without `not`?
```suggestion
	// server1 syncer should have disconnected from server2 peer
	assert.NotContains(t, sync1.peers, srv2.AddrInfo().ID)
```

**Review by Vuksan — CHANGES_REQUESTED** [review]
GJ on the test. 👏 
As for comments, all of them are concentrate on lowering the area in which certain resource is under lock.

File: protocol/syncer.go (hunk 1 above)
Comment (zivkovicmilos) [reply protocol/syncer.go]: Irrelevant after commit 9593ada

File: protocol/syncer.go (hunk 3 above)
Comment (zivkovicmilos) [reply protocol/syncer.go]: Irrelevant after commit 9593ada

File: protocol/syncer.go (hunk 4 above)
Comment (zivkovicmilos) [reply protocol/syncer.go]: Irrelevant after commit 9593ada

File: protocol/syncer_test.go (hunk 5 above)
Comment (zivkovicmilos) [reply protocol/syncer_test.go]: I've refactored the entire test 👍 

9593ada

**Review by zivkovicmilos — APPROVED** [review]

**Review by Kourin1996 — APPROVED** [review]
LGTM!

File: protocol/syncer.go [hunk 6]
```diff
@@ -245,17 +247,17 @@ const syncerV1 = "/syncer/0.1"
 func (s *Syncer) enqueueBlock(peerID peer.ID, b *types.Block) {
 	s.logger.Debug("enqueue block", "peer", peerID, "number", b.Number(), "hash", b.Hash())
 
-	p, ok := s.peers[peerID]
+	foundPeer, ok := s.peers.Load(peerID)
```
Comment (lazartravica) [inline protocol/syncer.go]: Be consistent in naming. I suggest calling it simply `peer` instead of `foundPeer`

File: protocol/syncer.go [hunk 7]
```diff
@@ -245,17 +247,17 @@ const syncerV1 = "/syncer/0.1"
...
+		foundPeer.(*syncPeer).appendBlock(b)
 	}
 }
 
 func (s *Syncer) updatePeerStatus(peerID peer.ID, status *Status) {
 	s.logger.Debug("update peer status", "peer", peerID, "latest block number", status.Number, "latest block hash", status.Hash, "difficulty", status.Difficulty)
 
-	if p, ok := s.peers[peerID]; ok {
-		p.updateStatus(status)
+	if p, ok := s.peers.Load(peerID); ok {
```
Comment (lazartravica) [inline protocol/syncer.go]: Be consistent in naming. I suggest calling it simply `peer` instead of `p`

File: protocol/syncer.go [hunk 8]
```diff
@@ -275,11 +277,19 @@ func (s *Syncer) Broadcast(b *types.Block) {
 			Value: b.MarshalRLP(),
 		},
 	}
-	for _, p := range s.peers {
-		if _, err := p.client.Notify(context.Background(), req); err != nil {
+
+	s.peers.Range(func(peerID, foundPeer interface{}) bool {
```
Comment (lazartravica) [inline protocol/syncer.go]: Be consistent in naming. I suggest calling it simply `peer` instead of `foundPeer`

File: protocol/syncer.go [hunk 9]
```diff
@@ -334,19 +344,25 @@ func (s *Syncer) BestPeer() *syncPeer {
 	var bestPeer *syncPeer
 	var bestTd *big.Int
 
-	for _, p := range s.peers {
-		status := p.status
+	s.peers.Range(func(peerID, foundPeer interface{}) bool {
```
Comment (lazartravica) [inline protocol/syncer.go]: Be consistent in naming. I suggest calling it simply `peer` instead of `foundPeer`

File: protocol/syncer_test.go [hunk 10]
```diff
@@ -0,0 +1,209 @@
...
+
+	// wait until gossip protocol builds the mesh network (https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md)
+	waitCtx, cancelWait := context.WithTimeout(context.Background(), time.Second*10)
+	defer cancelWait()
+
+	numPeers, err := WaitUntilSyncPeersNumber(waitCtx, syncers[1], 2)
+	if err != nil {
+		t.Fatalf("Unable to add sync peers, %v", err)
+	}
+	assert.Equal(t, int64(len(servers)-1), numPeers)
```
Comment (lazartravica) [inline protocol/syncer_test.go:206]: Please provide message for assert

File: protocol/syncer_test.go [hunk 11]
```diff
@@ -0,0 +1,209 @@
...
+	peerToDisconnect := servers[2].AddrInfo().ID
+	servers[1].Disconnect(peerToDisconnect, "testing")
+
+	waitCtx, cancelWait = context.WithTimeout(context.Background(), time.Second*10)
+	defer cancelWait()
+	numPeers, err = WaitUntilSyncPeersNumber(waitCtx, syncers[1], 1)
+	if err != nil {
+		t.Fatalf("Unable to disconnect sync peers, %v", err)
+	}
+	assert.Equal(t, int64(len(servers)-2), numPeers)
```
Comment (lazartravica) [inline protocol/syncer_test.go:220]: Please provide message for assert

File: protocol/syncer_test.go [hunk 12]
```diff
@@ -0,0 +1,209 @@
...
+
+	// server1 syncer should have disconnected from server2 peer
+	_, found := syncers[1].peers.Load(peerToDisconnect)
+	assert.False(t, found)
```
Comment (lazartravica) [inline protocol/syncer_test.go:227]: Please provide message for assert

**Review by lazartravica — CHANGES_REQUESTED** [review]
Good job on how the test is setup.

I have left minor naming and message related comments.

I don't like the implementation with the `sync.Map` and `sync/atomic.LoadInt64`. It's harder to understand what's going on than a `RWMutex` and we are using 2 synchronization primitives instead of one.

The most critical thing about using `sync.Map` and `sync/atomic.LoadInt64` is that they are 2 atomic operations, not one as it could be if we were using the RWMutex. In this case I don't see how it could affect us in a bad way, but in some other scenario if somebody was to implement the same method for updating a map and the length something like this could happen:

Thread A: Add entry to map
Thread B: Get map
Thread B: Get the length variable
Thread A: Increase the length variable by 1

This would result in Thread B working with a map of N elements, but with a length variable with a value of N-1.

File: protocol/syncer.go (hunk 6 above)
Comment (zivkovicmilos) [reply protocol/syncer.go]: Fixed 👍 

1943ea5

File: protocol/syncer.go (hunk 7 above)
Comment (zivkovicmilos) [reply protocol/syncer.go]: Fixed 👍 

1943ea5

File: protocol/syncer.go (hunk 8 above)
Comment (zivkovicmilos) [reply protocol/syncer.go]: Fixed 👍 

1943ea5

File: protocol/syncer.go (hunk 9 above)
Comment (zivkovicmilos) [reply protocol/syncer.go]: Fixed 👍 

1943ea5

File: protocol/syncer_test.go (hunk 10 above)
Comment (zivkovicmilos) [reply protocol/syncer_test.go:206]: Fixed 👍 

d89d88e

File: protocol/syncer_test.go (hunk 11 above)
Comment (zivkovicmilos) [reply protocol/syncer_test.go:220]: Fixed 👍 

d89d88e

File: protocol/syncer_test.go (hunk 12 above)
Comment (zivkovicmilos) [reply protocol/syncer_test.go:227]: Fixed 👍 

d89d88e

**Review by lazartravica — APPROVED** [review]

**Review by Vuksan — APPROVED** [review]
👏
