### PR TITLE
Fix block synchronization issue in IBFT

### LINKED ISSUE #162: Bootnode validator not able to sync up to latest block
### Description

It seems our 5-validator testnet got stuck and encountered a state where some of our node's latest block numbers fell out of sync, preventing the network from generating new blocks (as 4 validators are required).

`node-4` in our case crashed at block 0xb60d1 and couldn't sync up to 0xb60d7, the latest block on `node-1`.

While investigating, I tried to completely wipe everything within the data-dir of `node-4` hoping that it'll be able to sync up to the latest block on `node-1` (0xb60d7) from a clean slate:

```
rm -rf blockchain keystore trie consensus/metadata consensus/snapshots
```

However upon doing so and re-running `server` on `node-4`, the logs show the node to keep falling back into `RoundChangeState`:
```
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.362Z [INFO]  polygon.blockchain: genesis: hash=0x24d80debadd21a42ae8bcc3b28d39a0e2e2cbf9d7fee3507c1e38a33995fc3f5
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.363Z [INFO]  polygon: GRPC server running: addr=0.0.0.0:10000
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.363Z [INFO]  polygon.jsonrpc: http server started: addr=0.0.0.0:10002
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [DEBUG] polygon.consensus.ibft: state change: new=SyncState
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [DEBUG] polygon.consensus.ibft: current sequence: sequence=1
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=1 round=0
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=1
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [INFO]  polygon.consensus.ibft: current snapshot: validators=4 votes=0
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x4FAC0232243D2C863EF7787e0cb9c9118048d60e block=1
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.350Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh: [/ip4/3.215.13.226/tcp/10001]}"
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.384Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW: [/ip4/204.236.222.207/tcp/10001]}"
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.384Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x: [/ip4/34.207.228.138/tcp/10001]}"
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.390Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU: [/ip4/3.84.231.38/tcp/10001]}"
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.395Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
Sep 22 18:19:07 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:07.353Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAkwhNtm8iXMoWR7hmVCK3on6Rhz2DM8V6VhQm9bkdUwq1d: [/ip4/54.167.213.167/tcp/10001]}"
Sep 22 18:19:07 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:07.378Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Sep 22 18:19:07 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:07.378Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=1 round=0
Sep 22 18:19:07 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:07.378Z [DEBUG] polygon.consensus.ibft: local round change: round=1
```

I then attempted to reset our non-bootnode (`node-5`) back to block 0 to test out whether or not the bug exists in the actual syncing and upon restarting, I could immediately see `node-5` attempt to sync up to `node-1`:
```
Sep 22 18:13:04 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:04.993Z [INFO]  polygon.blockchain: genesis: hash=0x24d80debadd21a42ae8bcc3b28d39a0e2e2cbf9d7fee3507c1e38a33995fc3f5
Sep 22 18:13:04 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:04.994Z [INFO]  polygon: GRPC server running: addr=0.0.0.0:10000
Sep 22 18:13:04 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:04.995Z [INFO]  polygon.jsonrpc: http server started: addr=0.0.0.0:10002
Sep 22 18:13:10 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:10.005Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
Sep 22 18:13:10 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:10.014Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
Sep 22 18:13:11 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:11.012Z [INFO]  polygon.blockchain: write blocks: num=10 from=1 to=10 parent=0x24d80debadd21a42ae8bcc3b28d39a0e2e2cbf9d7fee3507c1e38a33995fc3f5
Sep 22 18:13:11 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:11.031Z [INFO]  polygon.blockchain: new block: number=1 hash=0x0b0278e54850e679e866e14dd7e238208c16e4abed2b8f0d5ea5c82a29ce9ff9 txns=0 generation_time_in_sec=1630687894
```

I'm not sure why `node-4` crashed in the first place but based on what I observed above, it seems that there is in issue when trying to sync up nodes that are within the genesis.json. 

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `4afea94 `
* branch that causes this issue `develop`

### Steps to reproduce

1.  Have 5 nodes running as validators (4 bootnodes + 1 non-bootnode)
2. Kill one of the 4 bootnodes (e.g. `node-4`)
3. Vote off the non-bootnode so that it is no longer a validator
4. Start up `node-4` and observe that it cannot sync up to the latest block
5. Attempt to clear the history of `node-4` and attempt to sync, observing the same issue

### Expected behaviour

Nodes (within or outside the bootnode validator set) should be able to sync up to the latest block when they fall behind (due to a crash).

### Actual behaviour

One of the 4 bootnode validators could not sync up to the latest block (it remained in `RoundChangeState`).

### Logs

See Description

### LINKED ISSUE #167: Block writing stopping but gossiping continuing on non-sealing nodes
### Description

We've had several instances of blocks stopping writing, some during the sync process, and some during operation. We can see in both cases blocks are still be gossiped on the channel, but writing is stopped.

All of these cases are on non-sealing nodes, i.e., not participating in consensus. 

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 18e93179d1303356b4f77b1b50cc46390d61b25c
* branch that causes this issue `fix/sync-issue`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
This seems to only happen in non-sealing nodes, or we've only seen it in non-sealing nodes, maybe because they don't participate in the IBFT scheme. Currently have a 5 node cluster participating in consensus. It seems to be the most reproducible when a node starts and enters bulk sync for a bit to catch up.
* Where the issue is, if you know <br />

It seems that after bulk sync completes, `WatchSyncWithPeer` is waiting indefinitely on `peer.popBlock()` or the `WatchSyncWithPeer` handler is returning false and existing the loop, but based on the logs in Case 1 it doesn't look like it gets past `popBlock()`.

If you're a validator/sealing node however, it does seem to skip this step b/c of this line https://github.com/0xPolygon/polygon-sdk/blob/develop/consensus/ibft/ibft.go#L321

Probably why we only see this issue on non-sealing nodes

We've added extra logging in `WatchSyncWithPeer`,  `BulkSyncWithPeer` and `enqueueBlock` for Log 1 context. See below:

```go
// enqueueBlock adds the specific block to the peerID queue
func (s *Syncer) enqueueBlock(peerID peer.ID, b *types.Block) {
	s.logger.Debug("enqueue block", "peer", peerID, "number", b.Number(), "hash", b.Hash())
	p, ok := s.peers[peerID]
	s.logger.Debug("enqueue block", "ok", ok, "peer", p.peer)
	if ok {
		p.appendBlock(b)
	}
}
```

```go
func (s *Syncer) WatchSyncWithPeer(p *syncPeer, handler func(b *types.Block) bool) {
	s.logger.Debug("Watch sync with peer")
	// purge from the cache of broadcasted blocks all the ones we have written so far
	header := s.blockchain.Header()
	s.logger.Debug("Header number", header.Number)
	p.purgeBlocks(header.Hash)
	s.logger.Debug("Blocks purged")

	// listen and enqueue the messages
	for {
		b := p.popBlock()

		if err := s.blockchain.WriteBlocks([]*types.Block{b}); err != nil {
			s.logger.Error("failed to write block", "err", err)
			break
		}
		if !handler(b) {
			break
		}
	}
}
```

```go
func (s *Syncer) BulkSyncWithPeer(p *syncPeer) error {
	// find the common ancestor
	ancestor, fork, err := s.findCommonAncestor(p.client, p.status)
	if err != nil {
		return err
	}

	// find in batches
	s.logger.Debug("fork found", "ancestor", ancestor.Number)

	startBlock := fork

	var lastTarget uint64

	// sync up to the current known header
	for {
		// update target
		target := p.status.Number
		if target == lastTarget {
			s.logger.Debug("No more changes to pull!", "target", target, "lastTarget", lastTarget, "Breaking.")
			// there are no more changes to pull for now
			break
		}

		for {
			s.logger.Debug("sync up to block", "from", startBlock.Number, "to", target)

			// start to synchronize with it
			sk := &skeleton{
				span: 10,
				num:  5,
			}

			if err := sk.build(p.client, startBlock.Hash); err != nil {
				return fmt.Errorf("failed to build skeleton: %v", err)
			}

			// fill skeleton
			for indx := range sk.slots {
				sk.fillSlot(uint64(indx), p.client) //nolint
			}

			// sync the data
			for _, slot := range sk.slots {
				if err := s.blockchain.WriteBlocks(slot.blocks); err != nil {
					return fmt.Errorf("failed to write bulk sync blocks: %v", err)
				}
			}

			// try to get the next block
			startBlock = sk.LastHeader()

			if startBlock.Number >= uint64(target) {
				s.logger.Debug("startBlock.Number", startBlock.Number, "target", target, "Breaking.")
				break
			}
		}

		lastTarget = target
	}
	return nil
}
```

```go
// appendBlock adds a new block to the block queue
func (s *syncPeer) appendBlock(b *types.Block) {
	s.enqueueLock.Lock()
	defer s.enqueueLock.Unlock()
	fmt.Println(("Got enqueue lock"))

	if len(s.enqueue) == maxEnqueueSize {
		// pop first element
		s.enqueue = s.enqueue[1:]
	}
	// append to the end
	s.enqueue = append(s.enqueue, b)

	// update the number and hash
	s.number = b.Number()
	s.hash = b.Hash()

	fmt.Println("New sync peer number", s.number)
	fmt.Println("New sync peer hash", s.hash)

	select {
	case s.enqueueCh <- struct{}{}:
	default:
	}
}
```

* Which commands triggered the issue, if any 
`./main server --chain genesis.json --jsonrpc 0.0.0.0:5000 --libp2p 0.0.0.0:1478 --log-level debug --nat $IP`

### Expected behaviour

Gossip'd blocks should continue to be written to state and processed normally after bulk sync

### Actual behaviour

Block writing suddenly stops, causing `eth_blockNumber` to return incorrect values and have all JSON-RPC endpoints return stale data. 

### Logs

Case 1 (with added logs from above)

```
2021-09-30T13:56:29.341Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.161Z [INFO] polygon: Data dir: path=./test-chain
-- | --
  | 2021-09-30T13:56:29.341Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.163Z [INFO] polygon.network: LibP2P server running: addr=/ip4/18.232.150.56/tcp/1478/p2p/16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C
  | 2021-09-30T13:56:29.341Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.196Z [INFO] polygon.consensus.ibft: validator key: addr=0xc256390D56BEa528C273Ac318B58022c19798445
  | 2021-09-30T13:56:29.341Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.197Z [INFO] polygon.blockchain: Current header: hash=0x7a771b5d2e3665a50bb857a431ff5dd4375019b4385a0741057b6837a914d890 number=872890
  | 2021-09-30T13:56:29.341Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.197Z [INFO] polygon.blockchain: genesis: hash=0x24d80debadd21a42ae8bcc3b28d39a0e2e2cbf9d7fee3507c1e38a33995fc3f5
  | 2021-09-30T13:56:29.341Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.198Z [INFO] polygon: GRPC server running: addr=127.0.0.1:9632
  | 2021-09-30T13:56:29.341Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.198Z [INFO] polygon.jsonrpc: http server started: addr=0.0.0.0:5000
  | 2021-09-30T13:56:29.341Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.198Z [INFO] polygon.consensus.ibft: snapshot was not found, restore snapshot at beginning of current epoch: current epoch=8
  | 2021-09-30T13:56:33.887Z | Sep 30 13:56:29 ip-172-31-24-192 web: 2021-09-30T13:56:29.199Z [INFO] polygon.consensus.ibft: syncing past snapshots: from=800000 to=872890
  | 2021-09-30T13:56:34.343Z | Sep 30 13:56:34 ip-172-31-24-192 web: 2021-09-30T13:56:34.176Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh: [/ip4/3.215.13.226/tcp/10001]}"
  | 2021-09-30T13:56:34.343Z | Sep 30 13:56:34 ip-172-31-24-192 web: 2021-09-30T13:56:34.186Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW: [/ip4/204.236.222.207/tcp/10001]}"
  | 2021-09-30T13:56:34.343Z | Sep 30 13:56:34 ip-172-31-24-192 web: 2021-09-30T13:56:34.190Z [INFO] polygon.network: Peer connected: id=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:56:34.343Z | Sep 30 13:56:34 ip-172-31-24-192 web: 2021-09-30T13:56:34.197Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x: [/ip4/34.207.228.138/tcp/10001]}"
  | 2021-09-30T13:56:34.343Z | Sep 30 13:56:34 ip-172-31-24-192 web: 2021-09-30T13:56:34.201Z [INFO] polygon.network: Peer connected: id=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:56:34.343Z | Sep 30 13:56:34 ip-172-31-24-192 web: 2021-09-30T13:56:34.207Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU: [/ip4/3.84.231.38/tcp/10001]}"
  | 2021-09-30T13:56:34.343Z | Sep 30 13:56:34 ip-172-31-24-192 web: 2021-09-30T13:56:34.211Z [INFO] polygon.network: Peer connected: id=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:34 ip-172-31-24-192 web: 2021-09-30T13:56:34.221Z [INFO] polygon.network: Peer connected: id=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: 2021-09-30T13:56:35.036Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872894 hash=0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: 2021-09-30T13:56:35.036Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: New sync peer number 872894
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: New sync peer hash 0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: 2021-09-30T13:56:35.037Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872894 hash=0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: 2021-09-30T13:56:35.038Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: New sync peer number 872894
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: New sync peer hash 0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: 2021-09-30T13:56:35.039Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872894 hash=0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: 2021-09-30T13:56:35.039Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: New sync peer number 872894
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: New sync peer hash 0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: 2021-09-30T13:56:35.041Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872894 hash=0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: 2021-09-30T13:56:35.041Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:35.093Z | Sep 30 13:56:35 ip-172-31-24-192 web: New sync peer number 872894
  | 2021-09-30T13:56:37.094Z | Sep 30 13:56:35 ip-172-31-24-192 web: New sync peer hash 0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8
  | 2021-09-30T13:56:37.094Z | Sep 30 13:56:36 ip-172-31-24-192 web: 2021-09-30T13:56:36.989Z [INFO] polygon.network: Peer connected: id=16Uiu2HAmPSdFWFTjKCyWSYUpi5jBTK1LBSbApU3SGwXP4ip6UNY2
  | 2021-09-30T13:56:39.345Z | Sep 30 13:56:36 ip-172-31-24-192 web: 2021-09-30T13:56:36.989Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAmPSdFWFTjKCyWSYUpi5jBTK1LBSbApU3SGwXP4ip6UNY2: [/ip4/52.90.232.81/tcp/10001]}"
  | 2021-09-30T13:56:43.887Z | Sep 30 13:56:39 ip-172-31-24-192 web: 2021-09-30T13:56:39.180Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAm3VD32VRQPVVU8QsGfLqmYu3bXzyPgvAhhm2nmQX3XKep: [/ip4/54.234.87.242/tcp/1478]}"
  | 2021-09-30T13:56:45.097Z | Sep 30 13:56:44 ip-172-31-24-192 web: 2021-09-30T13:56:44.181Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAkz7raWw7SMDQrySCWWSxBa4mbsC8tbRZazw6cdtXnqUZD: [/ip4/54.160.193.245/tcp/1478]}"
  | 2021-09-30T13:56:45.097Z | Sep 30 13:56:45 ip-172-31-24-192 web: 2021-09-30T13:56:45.096Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872895 hash=0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046
  | 2021-09-30T13:56:45.097Z | Sep 30 13:56:45 ip-172-31-24-192 web: 2021-09-30T13:56:45.096Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:56:45.097Z | Sep 30 13:56:45 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: New sync peer number 872895
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: New sync peer hash 0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: 2021-09-30T13:56:45.097Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872895 hash=0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: 2021-09-30T13:56:45.098Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: New sync peer number 872895
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: New sync peer hash 0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: 2021-09-30T13:56:45.100Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872895 hash=0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: 2021-09-30T13:56:45.101Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: New sync peer number 872895
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: New sync peer hash 0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: 2021-09-30T13:56:45.102Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872895 hash=0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: 2021-09-30T13:56:45.102Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:45.347Z | Sep 30 13:56:45 ip-172-31-24-192 web: New sync peer number 872895
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:45 ip-172-31-24-192 web: New sync peer hash 0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.019Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872896 hash=0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.019Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: New sync peer number 872896
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: New sync peer hash 0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.023Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872896 hash=0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.023Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: New sync peer number 872896
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: New sync peer hash 0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.023Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872896 hash=0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.023Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: New sync peer number 872896
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: New sync peer hash 0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.027Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872896 hash=0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.028Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:47.098Z | Sep 30 13:56:47 ip-172-31-24-192 web: New sync peer number 872896
  | 2021-09-30T13:56:47.348Z | Sep 30 13:56:47 ip-172-31-24-192 web: New sync peer hash 0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd
  | 2021-09-30T13:56:47.348Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.299Z [DEBUG] polygon.jsonrpc: handle: request={"method":"eth_blockNumber","params":[],"id":16913,"jsonrpc":"2.0"}
  | 2021-09-30T13:56:47.348Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.299Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=16913
  | 2021-09-30T13:56:47.348Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.300Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":16913,"result":"0xd51ba"}
  | 2021-09-30T13:56:47.348Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.320Z [DEBUG] polygon.jsonrpc: handle: request={"method":"eth_sendRawTransaction","params":["0xf86c823f6982096d8252089482d4a18c982495594a10311276b02c03df679575871c6bf52634000080820532a08b1a1407f572c49e6744502933d5ba93eb1eb86cbc1b406a445b804e4b59610ea044c7913130326a7cf1b20270cf9b147116231d9e2fffaac6bd18006d7ca75cd8"],"id":16914,"jsonrpc":"2.0"}
  | 2021-09-30T13:56:47.348Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.320Z [DEBUG] polygon.dispatcher: request: method=eth_sendRawTransaction id=16914
  | 2021-09-30T13:56:47.348Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.322Z [DEBUG] polygon.txpool: add txn: ctx=addTxn hash=0x1b010ae4942a22b553ea8cb0ad16dac67218b3a5c058b9a8f3dd0970e7c027ff from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:47 ip-172-31-24-192 web: 2021-09-30T13:56:47.322Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":16914,"result":"0x1b010ae4942a22b553ea8cb0ad16dac67218b3a5c058b9a8f3dd0970e7c027ff"}
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.026Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872897 hash=0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.026Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: New sync peer number 872897
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: New sync peer hash 0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.029Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872897 hash=0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.029Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: New sync peer number 872897
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: New sync peer hash 0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.030Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872897 hash=0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.030Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: New sync peer number 872897
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: New sync peer hash 0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.031Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872897 hash=0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.032Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:49.099Z | Sep 30 13:56:49 ip-172-31-24-192 web: New sync peer number 872897
  | 2021-09-30T13:56:49.349Z | Sep 30 13:56:49 ip-172-31-24-192 web: New sync peer hash 0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:49 ip-172-31-24-192 web: 2021-09-30T13:56:49.181Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAmLqdTjUjjqtibhoN3ZYpnyzVvyhFgUUHtLiTQJJ3uym9h: [/ip4/18.215.250.99/tcp/1478]}"
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.026Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872898 hash=0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.027Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: New sync peer number 872898
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: New sync peer hash 0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.028Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872898 hash=0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.028Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: New sync peer number 872898
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: New sync peer hash 0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.029Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872898 hash=0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.029Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: New sync peer number 872898
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: New sync peer hash 0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.030Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872898 hash=0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.031Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:56:51.100Z | Sep 30 13:56:51 ip-172-31-24-192 web: New sync peer number 872898
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: New sync peer hash 0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.153Z [DEBUG] polygon.consensus.ibft: state change: new=SyncState
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.153Z [DEBUG] polygon.consensus.ibft: current sequence: sequence=872891
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.182Z [DEBUG] polygon.consensus.syncer: fork found: ancestor=872890
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.182Z [DEBUG] polygon.consensus.syncer: sync up to block: from=872891 to=872894
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.184Z [INFO] polygon.blockchain: write blocks: num=8 from=872891 to=872898 parent=0x7a771b5d2e3665a50bb857a431ff5dd4375019b4385a0741057b6837a914d890
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.195Z [INFO] polygon.blockchain: new block: number=872891 hash=0x443d161ff8c77005e8644179487b7b93fd5bccd6b31d04b04cae2e524e8d72d6 txns=0 generation_time_in_sec=10
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.196Z [INFO] polygon.blockchain: new block: number=872892 hash=0x8fbaaed124578b20cee06374eb2f685a554c8108336d76528f7496f2d2d2d288 txns=0 generation_time_in_sec=2
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.196Z [INFO] polygon.blockchain: new block: number=872893 hash=0x9f71ab83413b748ee8bdeae03264ac169dc81f12e4566c582ae6852d73985926 txns=0 generation_time_in_sec=2
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.197Z [INFO] polygon.blockchain: new block: number=872894 hash=0x2841bdc7524be0ca56a2252af42dc45355ccd2971e7dd87fe960021fd58c7ac8 txns=0 generation_time_in_sec=2
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.197Z [INFO] polygon.blockchain: new block: number=872895 hash=0x56b4f17f45ac9bec6aaebc54691d2711c963f10f089e578b72b19b867e66d046 txns=0 generation_time_in_sec=10
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.198Z [INFO] polygon.blockchain: new block: number=872896 hash=0x706a67534fd2873b512bf730de0c8c4f3042410cc3e9e9d740b87dee7cd666bd txns=0 generation_time_in_sec=2
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.198Z [INFO] polygon.blockchain: new block: number=872897 hash=0x7d6922cf708c0f5277ba65eb3c83ce8177c3747f266af78b747471a233b18406 txns=0 generation_time_in_sec=2
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.199Z [INFO] polygon.blockchain: new block: number=872898 hash=0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821 txns=1 generation_time_in_sec=2
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.199Z [INFO] polygon.blockchain: new head: hash=0x0b545fea1ef2c7b72f47ad34c13f1a8e9a4b7cac5faf72ea0917b8750fb03821 number=872898
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.199Z [DEBUG] polygon.consensus.syncer: startBlock.Number: %!s(uint64=872898)=target %!s(uint64=872894)=Breaking.
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.199Z [DEBUG] polygon.consensus.syncer: No more changes to pull!: target=872894 lastTarget=872894 EXTRA_VALUE_AT_END=Breaking.
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.199Z [DEBUG] polygon.consensus.syncer: Watch sync with peer
  | 2021-09-30T13:56:51.350Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.199Z [DEBUG] polygon.consensus.syncer: Header number: EXTRA_VALUE_AT_END=872898
  | 2021-09-30T13:56:54.351Z | Sep 30 13:56:51 ip-172-31-24-192 web: 2021-09-30T13:56:51.199Z [DEBUG] polygon.consensus.syncer: Blocks purged
  | 2021-09-30T13:56:54.351Z | Sep 30 13:56:54 ip-172-31-24-192 web: 2021-09-30T13:56:54.183Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAmM4GFptxAkpQrNBJrdud9yTKg3LAnNQid22Lh7j4ac4bW: [/ip4/184.72.207.241/tcp/1478]}"
  | 2021-09-30T13:56:58.887Z | Sep 30 13:56:54 ip-172-31-24-192 web: 2021-09-30T13:56:54.185Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAm5pstFUEigRQB983B1vpWZ1hAwVHqP7dQHtPzK1yG1dbH: [/ip4/3.81.5.248/tcp/1478]}"
  | 2021-09-30T13:57:01.104Z | Sep 30 13:56:59 ip-172-31-24-192 web: 2021-09-30T13:56:59.186Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAkyRQYsYXUNP5BNnMHEh7pfmDz3tt3esyZ5dv5ALxtyphM: [/ip4/3.81.5.248/tcp/1478]}"
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: 2021-09-30T13:57:01.065Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872899 hash=0x227dcb55a19a45d661f4cd5b71d74222363b82ed331da189b8f5edef14c43850
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: 2021-09-30T13:57:01.065Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: New sync peer number 872899
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: New sync peer hash 0x227dcb55a19a45d661f4cd5b71d74222363b82ed331da189b8f5edef14c43850
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: 2021-09-30T13:57:01.097Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872899 hash=0x227dcb55a19a45d661f4cd5b71d74222363b82ed331da189b8f5edef14c43850
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: 2021-09-30T13:57:01.097Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:01.104Z | Sep 30 13:57:01 ip-172-31-24-192 web: New sync peer number 872899
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: New sync peer hash 0x227dcb55a19a45d661f4cd5b71d74222363b82ed331da189b8f5edef14c43850
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: 2021-09-30T13:57:01.128Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872899 hash=0x227dcb55a19a45d661f4cd5b71d74222363b82ed331da189b8f5edef14c43850
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: 2021-09-30T13:57:01.128Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: New sync peer number 872899
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: New sync peer hash 0x227dcb55a19a45d661f4cd5b71d74222363b82ed331da189b8f5edef14c43850
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: 2021-09-30T13:57:01.139Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872899 hash=0x227dcb55a19a45d661f4cd5b71d74222363b82ed331da189b8f5edef14c43850
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: 2021-09-30T13:57:01.139Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:01.355Z | Sep 30 13:57:01 ip-172-31-24-192 web: New sync peer number 872899
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:01 ip-172-31-24-192 web: New sync peer hash 0x227dcb55a19a45d661f4cd5b71d74222363b82ed331da189b8f5edef14c43850
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: 2021-09-30T13:57:03.172Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872900 hash=0x43d897b1493b2939a6532dbbd63fcfe6807d566a502df5842780451d414f9118
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: 2021-09-30T13:57:03.172Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: New sync peer number 872900
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: New sync peer hash 0x43d897b1493b2939a6532dbbd63fcfe6807d566a502df5842780451d414f9118
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: 2021-09-30T13:57:03.174Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872900 hash=0x43d897b1493b2939a6532dbbd63fcfe6807d566a502df5842780451d414f9118
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: 2021-09-30T13:57:03.174Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: New sync peer number 872900
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: New sync peer hash 0x43d897b1493b2939a6532dbbd63fcfe6807d566a502df5842780451d414f9118
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: 2021-09-30T13:57:03.218Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872900 hash=0x43d897b1493b2939a6532dbbd63fcfe6807d566a502df5842780451d414f9118
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: 2021-09-30T13:57:03.218Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: New sync peer number 872900
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: New sync peer hash 0x43d897b1493b2939a6532dbbd63fcfe6807d566a502df5842780451d414f9118
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: 2021-09-30T13:57:03.320Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872900 hash=0x43d897b1493b2939a6532dbbd63fcfe6807d566a502df5842780451d414f9118
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: 2021-09-30T13:57:03.320Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:03.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: New sync peer number 872900
  | 2021-09-30T13:57:04.356Z | Sep 30 13:57:03 ip-172-31-24-192 web: New sync peer hash 0x43d897b1493b2939a6532dbbd63fcfe6807d566a502df5842780451d414f9118
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:04 ip-172-31-24-192 web: 2021-09-30T13:57:04.188Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAmNkhfoMDCEqZ21AxaYNWvUMx6Lg21UkMS4GiLrcK2SWD5: [/ip4/3.81.5.248/tcp/10001]}"
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: 2021-09-30T13:57:05.025Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872901 hash=0x7e2753bd98ce6f0686e170cbe9537c31396e1e36719eb804acebd67e94902a1a
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: 2021-09-30T13:57:05.026Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: New sync peer number 872901
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: New sync peer hash 0x7e2753bd98ce6f0686e170cbe9537c31396e1e36719eb804acebd67e94902a1a
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: 2021-09-30T13:57:05.027Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872901 hash=0x7e2753bd98ce6f0686e170cbe9537c31396e1e36719eb804acebd67e94902a1a
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: 2021-09-30T13:57:05.027Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: New sync peer number 872901
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: New sync peer hash 0x7e2753bd98ce6f0686e170cbe9537c31396e1e36719eb804acebd67e94902a1a
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: 2021-09-30T13:57:05.028Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872901 hash=0x7e2753bd98ce6f0686e170cbe9537c31396e1e36719eb804acebd67e94902a1a
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: 2021-09-30T13:57:05.028Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: New sync peer number 872901
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: New sync peer hash 0x7e2753bd98ce6f0686e170cbe9537c31396e1e36719eb804acebd67e94902a1a
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: 2021-09-30T13:57:05.030Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872901 hash=0x7e2753bd98ce6f0686e170cbe9537c31396e1e36719eb804acebd67e94902a1a
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: 2021-09-30T13:57:05.030Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:05.106Z | Sep 30 13:57:05 ip-172-31-24-192 web: New sync peer number 872901
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:05 ip-172-31-24-192 web: New sync peer hash 0x7e2753bd98ce6f0686e170cbe9537c31396e1e36719eb804acebd67e94902a1a
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: 2021-09-30T13:57:07.027Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872902 hash=0x61d93388e964b8ae0945f41f62fc73d42ed14b79d0b13a6810387363ee4a0edd
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: 2021-09-30T13:57:07.027Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: New sync peer number 872902
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: New sync peer hash 0x61d93388e964b8ae0945f41f62fc73d42ed14b79d0b13a6810387363ee4a0edd
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: 2021-09-30T13:57:07.028Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872902 hash=0x61d93388e964b8ae0945f41f62fc73d42ed14b79d0b13a6810387363ee4a0edd
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: 2021-09-30T13:57:07.028Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: New sync peer number 872902
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: New sync peer hash 0x61d93388e964b8ae0945f41f62fc73d42ed14b79d0b13a6810387363ee4a0edd
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: 2021-09-30T13:57:07.029Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872902 hash=0x61d93388e964b8ae0945f41f62fc73d42ed14b79d0b13a6810387363ee4a0edd
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: 2021-09-30T13:57:07.029Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: New sync peer number 872902
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: New sync peer hash 0x61d93388e964b8ae0945f41f62fc73d42ed14b79d0b13a6810387363ee4a0edd
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: 2021-09-30T13:57:07.030Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872902 hash=0x61d93388e964b8ae0945f41f62fc73d42ed14b79d0b13a6810387363ee4a0edd
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: 2021-09-30T13:57:07.030Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:07.107Z | Sep 30 13:57:07 ip-172-31-24-192 web: New sync peer number 872902
  | 2021-09-30T13:57:09.376Z | Sep 30 13:57:07 ip-172-31-24-192 web: New sync peer hash 0x61d93388e964b8ae0945f41f62fc73d42ed14b79d0b13a6810387363ee4a0edd
  | 2021-09-30T13:57:13.887Z | Sep 30 13:57:09 ip-172-31-24-192 web: 2021-09-30T13:57:09.188Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAm52bbB91oJSbn4R3gsiRi8Jpx4BfZ8cTHzUtw8qfpeSUP: [/ip4/3.84.246.251/tcp/1478]}"
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:14 ip-172-31-24-192 web: 2021-09-30T13:57:14.189Z [DEBUG] polygon.network: dial: local=16Uiu2HAm7iiWLhJShny9TG5RFaazXa4zbW4qaprnfbbrpkiE7w7C addr="{16Uiu2HAmEiQZyVpQBPE3o8B4gL3bithtkYZ2Wz5sziFyL162EptF: [/ip4/35.173.248.101/tcp/1478]}"
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: 2021-09-30T13:57:17.069Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=872903 hash=0x8366fff73fb36f607d3c93ca63a3c7cc1af513a1645ca17dc13716170616a9ff
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: 2021-09-30T13:57:17.069Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: New sync peer number 872903
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: New sync peer hash 0x8366fff73fb36f607d3c93ca63a3c7cc1af513a1645ca17dc13716170616a9ff
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: 2021-09-30T13:57:17.071Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=872903 hash=0x8366fff73fb36f607d3c93ca63a3c7cc1af513a1645ca17dc13716170616a9ff
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: 2021-09-30T13:57:17.071Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: New sync peer number 872903
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: New sync peer hash 0x8366fff73fb36f607d3c93ca63a3c7cc1af513a1645ca17dc13716170616a9ff
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: 2021-09-30T13:57:17.072Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=872903 hash=0x8366fff73fb36f607d3c93ca63a3c7cc1af513a1645ca17dc13716170616a9ff
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: 2021-09-30T13:57:17.072Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: New sync peer number 872903
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: New sync peer hash 0x8366fff73fb36f607d3c93ca63a3c7cc1af513a1645ca17dc13716170616a9ff
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: 2021-09-30T13:57:17.073Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872903 hash=0x8366fff73fb36f607d3c93ca63a3c7cc1af513a1645ca17dc13716170616a9ff
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: 2021-09-30T13:57:17.073Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:17.112Z | Sep 30 13:57:17 ip-172-31-24-192 web: New sync peer number 872903
  | 2021-09-30T13:57:19.113Z | Sep 30 13:57:17 ip-172-31-24-192 web: New sync peer hash 0x8366fff73fb36f607d3c93ca63a3c7cc1af513a1645ca17dc13716170616a9ff
  | 2021-09-30T13:57:19.113Z | Sep 30 13:57:19 ip-172-31-24-192 web: 2021-09-30T13:57:19.022Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=872904 hash=0xfe1a16327a64babb1ca496353e2c926724377157ce83577888f9925d59548b5e
  | 2021-09-30T13:57:19.113Z | Sep 30 13:57:19 ip-172-31-24-192 web: 2021-09-30T13:57:19.022Z [DEBUG] polygon.consensus.syncer: enqueue block: ok=true peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU
  | 2021-09-30T13:57:19.113Z | Sep 30 13:57:19 ip-172-31-24-192 web: Got enqueue lock
  | 2021-09-30T13:57:19.113Z | Sep 30 13:57:19 ip-172-31-24-192 web: New sync peer number 872904
  | 2021-09-30T13:57:19.113Z | Sep 30 13:57:19 ip-172-31-24-192 web: New sync peer hash 0xfe1a16327a64babb1ca496353e2c926724377157ce83577888f9925d59548b5e
```

Case 2:

```


 | 2021-09-28T00:28:56.131Z | Sep 28 00:28:56 ip-172-31-92-108 web: 2021-09-28T00:28:56.058Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=819452 hash=0x723e15e0cde997de538ab7e68cd93abf67d7d0ae625d705c295a46f0b25e72db
  | 2021-09-28T00:28:56.131Z | Sep 28 00:28:56 ip-172-31-92-108 web: 2021-09-28T00:28:56.059Z [INFO] polygon.blockchain: new block: number=819452 hash=0x723e15e0cde997de538ab7e68cd93abf67d7d0ae625d705c295a46f0b25e72db txns=0 generation_time_in_sec=10
  | 2021-09-28T00:28:56.131Z | Sep 28 00:28:56 ip-172-31-92-108 web: 2021-09-28T00:28:56.059Z [INFO] polygon.blockchain: new head: hash=0x723e15e0cde997de538ab7e68cd93abf67d7d0ae625d705c295a46f0b25e72db number=819452
  | 2021-09-28T00:28:56.131Z | Sep 28 00:28:56 ip-172-31-92-108 web: 2021-09-28T00:28:56.063Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=819452 hash=0x723e15e0cde997de538ab7e68cd93abf67d7d0ae625d705c295a46f0b25e72db
  | 2021-09-28T00:28:58.131Z | Sep 28 00:28:56 ip-172-31-92-108 web: 2021-09-28T00:28:56.064Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=819452 hash=0x723e15e0cde997de538ab7e68cd93abf67d7d0ae625d705c295a46f0b25e72db
  | 2021-09-28T00:28:58.131Z | Sep 28 00:28:58 ip-172-31-92-108 web: 2021-09-28T00:28:58.023Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=819453 hash=0x48cca157251acd08ba1d0109227ca5be1c13a46a3471e52110ce07a2eab96938
  | 2021-09-28T00:28:58.131Z | Sep 28 00:28:58 ip-172-31-92-108 web: 2021-09-28T00:28:58.023Z [INFO] polygon.blockchain: write block: num=819453 parent=0x723e15e0cde997de538ab7e68cd93abf67d7d0ae625d705c295a46f0b25e72db
  | 2021-09-28T00:28:58.131Z | Sep 28 00:28:58 ip-172-31-92-108 web: 2021-09-28T00:28:58.025Z [INFO] polygon.blockchain: new block: number=819453 hash=0x48cca157251acd08ba1d0109227ca5be1c13a46a3471e52110ce07a2eab96938 txns=0 generation_time_in_sec=2
  | 2021-09-28T00:28:58.131Z | Sep 28 00:28:58 ip-172-31-92-108 web: 2021-09-28T00:28:58.025Z [INFO] polygon.blockchain: new head: hash=0x48cca157251acd08ba1d0109227ca5be1c13a46a3471e52110ce07a2eab96938 number=819453
  | 2021-09-28T00:28:58.131Z | Sep 28 00:28:58 ip-172-31-92-108 web: 2021-09-28T00:28:58.036Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=819453 hash=0x48cca157251acd08ba1d0109227ca5be1c13a46a3471e52110ce07a2eab96938
  | 2021-09-28T00:28:58.131Z | Sep 28 00:28:58 ip-172-31-92-108 web: 2021-09-28T00:28:58.037Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=819453 hash=0x48cca157251acd08ba1d0109227ca5be1c13a46a3471e52110ce07a2eab96938
  | 2021-09-28T00:29:00.132Z | Sep 28 00:28:58 ip-172-31-92-108 web: 2021-09-28T00:28:58.038Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=819453 hash=0x48cca157251acd08ba1d0109227ca5be1c13a46a3471e52110ce07a2eab96938
  | 2021-09-28T00:29:00.132Z | Sep 28 00:29:00 ip-172-31-92-108 web: 2021-09-28T00:29:00.033Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=819454 hash=0xe0e12c0443b5b53bfdb8934e25ea060798b9274305e31c0aad6d1d039e7f4bb9
  | 2021-09-28T00:29:00.132Z | Sep 28 00:29:00 ip-172-31-92-108 web: 2021-09-28T00:29:00.068Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=819454 hash=0xe0e12c0443b5b53bfdb8934e25ea060798b9274305e31c0aad6d1d039e7f4bb9
  | 2021-09-28T00:29:00.132Z | Sep 28 00:29:00 ip-172-31-92-108 web: 2021-09-28T00:29:00.073Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=819454 hash=0xe0e12c0443b5b53bfdb8934e25ea060798b9274305e31c0aad6d1d039e7f4bb9
  | 2021-09-28T00:29:00.132Z | Sep 28 00:29:00 ip-172-31-92-108 web: 2021-09-28T00:29:00.073Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=819454 hash=0xe0e12c0443b5b53bfdb8934e25ea060798b9274305e31c0aad6d1d039e7f4bb9
  | 2021-09-28T00:29:00.132Z | Sep 28 00:29:00 ip-172-31-92-108 web: 2021-09-28T00:29:00.073Z [INFO] polygon.blockchain: write block: num=819454 parent=0x48cca157251acd08ba1d0109227ca5be1c13a46a3471e52110ce07a2eab96938
  | 2021-09-28T00:29:00.132Z | Sep 28 00:29:00 ip-172-31-92-108 web: 2021-09-28T00:29:00.075Z [INFO] polygon.blockchain: new block: number=819454 hash=0xe0e12c0443b5b53bfdb8934e25ea060798b9274305e31c0aad6d1d039e7f4bb9 txns=0 generation_time_in_sec=2
  | 2021-09-28T00:29:02.633Z | Sep 28 00:29:00 ip-172-31-92-108 web: 2021-09-28T00:29:00.075Z [INFO] polygon.blockchain: new head: hash=0xe0e12c0443b5b53bfdb8934e25ea060798b9274305e31c0aad6d1d039e7f4bb9 number=819454
  | 2021-09-28T00:29:02.633Z | Sep 28 00:29:02 ip-172-31-92-108 web: 2021-09-28T00:29:02.454Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=819455 hash=0xe0dc0fbad05b4cb4fe002f5d05161a5c0bad0752fd4f438283c638e1c0050210
  | 2021-09-28T00:29:02.633Z | Sep 28 00:29:02 ip-172-31-92-108 web: 2021-09-28T00:29:02.454Z [INFO] polygon.blockchain: write block: num=819455 parent=0xe0e12c0443b5b53bfdb8934e25ea060798b9274305e31c0aad6d1d039e7f4bb9
  | 2021-09-28T00:29:02.633Z | Sep 28 00:29:02 ip-172-31-92-108 web: 2021-09-28T00:29:02.455Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=819455 hash=0xe0dc0fbad05b4cb4fe002f5d05161a5c0bad0752fd4f438283c638e1c0050210
  | 2021-09-28T00:29:02.633Z | Sep 28 00:29:02 ip-172-31-92-108 web: 2021-09-28T00:29:02.455Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=819455 hash=0xe0dc0fbad05b4cb4fe002f5d05161a5c0bad0752fd4f438283c638e1c0050210
  | 2021-09-28T00:29:02.633Z | Sep 28 00:29:02 ip-172-31-92-108 web: 2021-09-28T00:29:02.456Z [INFO] polygon.blockchain: new block: number=819455 hash=0xe0dc0fbad05b4cb4fe002f5d05161a5c0bad0752fd4f438283c638e1c0050210 txns=0 generation_time_in_sec=2
  | 2021-09-28T00:29:02.633Z | Sep 28 00:29:02 ip-172-31-92-108 web: 2021-09-28T00:29:02.456Z [INFO] polygon.blockchain: new head: hash=0xe0dc0fbad05b4cb4fe002f5d05161a5c0bad0752fd4f438283c638e1c0050210 number=819455
  | 2021-09-28T00:29:04.634Z | Sep 28 00:29:02 ip-172-31-92-108 web: 2021-09-28T00:29:02.540Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=819455 hash=0xe0dc0fbad05b4cb4fe002f5d05161a5c0bad0752fd4f438283c638e1
2021-09-28T00:29:09.386Z | Sep 28 00:29:07 ip-172-31-92-108 web: 2021-09-28T00:29:07.556Z [INFO] polygon.network: Peer disconnected: id=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x
2021-09-28T00:29:12.638Z | Sep 28 00:29:12 ip-172-31-92-108 web: 2021-09-28T00:29:12.564Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=819456 hash=0xd0f9df30b69f0fc9b2cef7eafee027e92d08933565e354952b4e9e1d1ff809cf
  | 2021-09-28T00:29:12.638Z | Sep 28 00:29:12 ip-172-31-92-108 web: 2021-09-28T00:29:12.565Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=819456 hash=0xd0f9df30b69f0fc9b2cef7eafee027e92d08933565e354952b4e9e1d1ff809cf
  | 2021-09-28T00:29:14.138Z | Sep 28 00:29:12 ip-172-31-92-108 web: 2021-09-28T00:29:12.566Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=819456 hash=0xd0f9df30b69f0fc9b2cef7eafee027e92d08933565e354952b4e9e1d1ff809cf
  | 2021-09-28T00:29:14.138Z | Sep 28 00:29:14 ip-172-31-92-108 web: 2021-09-28T00:29:14.033Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=819457 hash=0xe53d1e50303e835bf260a81bfd7975d437166f8e2f2ffea1dc81aea547c30451
  | 2021-09-28T00:29:14.138Z | Sep 28 00:29:14 ip-172-31-92-108 web: 2021-09-28T00:29:14.034Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=819457 hash=0xe53d1e50303e835bf260a81bfd7975d437166f8e2f2ffea1dc81aea547c30451
  | 2021-09-28T00:29:15.139Z | Sep 28 00:29:14 ip-172-31-92-108 web: 2021-09-28T00:29:14.035Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=819457 hash=0xe53d1e50303e835bf260a81bfd7975d437166f8e2f2ffea1dc81aea5
  2021-09-28T00:29:24.143Z | Sep 28 00:29:23 ip-172-31-92-108 web: 2021-09-28T00:29:23.987Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=819458 hash=0xe7c9d4335dc80d2b2962d7aeb198cad43d6c4f92a7c73a33180ea7de2dc7c4cd
  | 2021-09-28T00:29:24.143Z | Sep 28 00:29:23 ip-172-31-92-108 web: 2021-09-28T00:29:23.987Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=819458 hash=0xe7c9d4335dc80d2b2962d7aeb198cad43d6c4f92a7c73a33180ea7de2dc7c4cd
  | 2021-09-28T00:29:24.643Z | Sep 28 00:29:23 ip-172-31-92-108 web: 2021-09-28T00:29:23.988Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=819458 hash=0xe7c9d4335dc80d2b2962d7aeb198cad43d6c4f92a7c73a33180ea7de2d
```

The enqueue blocks pretty much go on forever, so the node is receiving blocks from other nodes but it has stopped writing for some reason.

Case 3:

During bulk syncing:

```


2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.145Z [INFO] polygon.blockchain: write blocks: num=10 from=813284 to=813293 parent=0x45483aa4b58a1382d426eeba89182975b58060b946349dac53c993f1f99b9dfe
-- | --
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.159Z [INFO] polygon.blockchain: new block: number=813284 hash=0xac72f926be0b0ce1814c5d2e12a93864eb75106cb0603fa0b8a3bea85ddfcef4 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.159Z [INFO] polygon.blockchain: new block: number=813285 hash=0xb7c9a7d5bf786cbae9d214147c21b54d7fcbb0b253560e03f2e5a62a9ee5625f txns=0 generation_time_in_sec=10
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.160Z [INFO] polygon.blockchain: new block: number=813286 hash=0x507e712b76cd8751f8d0c7917d12a199f632b49c9714238b1a060cfc87efed67 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.160Z [INFO] polygon.blockchain: new block: number=813287 hash=0x9e720843460c16015d5100a37d785efa3bdb0ef78607223c8370f381efcbad27 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.161Z [INFO] polygon.blockchain: new block: number=813288 hash=0x8421e5cd66d1d0aef47a69506228c83bdcb50a721d3f1c116a4ff8659e4a9269 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.161Z [INFO] polygon.blockchain: new block: number=813289 hash=0xde05602d6067bf8f7d7f1a92443c6824999cf78b4ef69101907e9e9780c38633 txns=0 generation_time_in_sec=10
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.162Z [INFO] polygon.blockchain: new block: number=813290 hash=0x85e7d471f9faa2de65a5f7aed689ef04f8be32b9b2f742f3b426cfd76c6edb1b txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.162Z [INFO] polygon.blockchain: new block: number=813291 hash=0x457ace51c136a33541139a26e35047ceb9063892b89efe082f822836bcef9aa8 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.163Z [INFO] polygon.blockchain: new block: number=813292 hash=0xdb102b5c45e1adfb7cfca88c3770ae2a2154aab1034a2289b24557b6a34c2094 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.163Z [INFO] polygon.blockchain: new block: number=813293 hash=0x79b15bc986bf2428c9dd575f0024695356fa1d27849c94786b5266a3273f46bf txns=0 generation_time_in_sec=10
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.163Z [INFO] polygon.blockchain: new head: hash=0x79b15bc986bf2428c9dd575f0024695356fa1d27849c94786b5266a3273f46bf number=813293
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.163Z [INFO] polygon.blockchain: write blocks: num=10 from=813294 to=813303 parent=0x79b15bc986bf2428c9dd575f0024695356fa1d27849c94786b5266a3273f46bf
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.177Z [INFO] polygon.blockchain: new block: number=813294 hash=0x6115db20b4ad1da834db8bc30bfcc83e51dd632884f79c70ef3f7e9506e7589e txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.178Z [INFO] polygon.blockchain: new block: number=813295 hash=0xf2a58399318c5984551a83d76b13211e80e7e5ab0ddfd936f4bf18b79efcf88a txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.178Z [INFO] polygon.blockchain: new block: number=813296 hash=0x5fb09cc9c05bcdde41bd81cac6f4d6013e1bc2c4292ff46ae473feebdcf368e2 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.179Z [INFO] polygon.blockchain: new block: number=813297 hash=0xb6c81b70302bb0fcd81c04bda2926a9938c11ba9aefad63425c440a00fb1b20c txns=0 generation_time_in_sec=10
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.179Z [INFO] polygon.blockchain: new block: number=813298 hash=0xe3da01b8598b031fe092ba6368751cec1a0eead36e0d55f98ea7c6caff6cf8b5 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.179Z [INFO] polygon.blockchain: new block: number=813299 hash=0x85ecf5ed95a9870dac66f348f761a40bbf435e9e060ccc1298ccfc901188e403 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.180Z [INFO] polygon.blockchain: new block: number=813300 hash=0x1a744cd3e40abf83bcb79a06b5472625573b12575ac99404a3ff790e9cbda7dd txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.180Z [INFO] polygon.blockchain: new block: number=813301 hash=0xada0fe41041d9fc352ce832019c3ab667f0680e2fcbef5785d4a51d4b19399d3 txns=0 generation_time_in_sec=10
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.181Z [INFO] polygon.blockchain: new block: number=813302 hash=0xc81a2921080a7c5f6525777627224bcf5b86fb00232f6eca09e9a147dd14596a txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.181Z [INFO] polygon.blockchain: new block: number=813303 hash=0x97561b5b1cd2c1ab03af28f6bde68848ebc0d561a2ec6daf0eb81a07e402743b txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.181Z [INFO] polygon.blockchain: new head: hash=0x97561b5b1cd2c1ab03af28f6bde68848ebc0d561a2ec6daf0eb81a07e402743b number=813303
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.181Z [DEBUG] polygon.consensus.syncer: sync up to block: from=813303 to=814788
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.195Z [INFO] polygon.blockchain: write blocks: num=10 from=813303 to=813312 parent=0xc81a2921080a7c5f6525777627224bcf5b86fb00232f6eca09e9a147dd14596a
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.225Z [INFO] polygon.blockchain: new block: number=813303 hash=0x97561b5b1cd2c1ab03af28f6bde68848ebc0d561a2ec6daf0eb81a07e402743b txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:33.395Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.226Z [INFO] polygon.blockchain: new block: number=813304 hash=0x1ef274e97e8e4a0f1a90d125157dcf8b4aa0a8abfb5aed1d26b796aff5a795e7 txns=0 generation_time_in_sec=2
  | 2021-09-27T19:10:37.693Z | Sep 27 19:10:33 ip-172-31-44-61 web: 2021-09-27T19:10:33.226Z [INFO] polygon.blockchain: new block: number=813305 hash=0x8f6b9553e65cce02fa07284438b6c3857509a9e23b6af4e696d55f70fc4db52c txns=0 generation_time_in_sec=10
  | 2021-09-27T19:11:01.162Z | Sep 27 19:11:01 ip-172-31-44-61 web: 2021-09-27T19:11:01.025Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815256 hash=0xc621bd58aa0987a1b36b2c37787f5933badc251b2806fbb3d8f3c7bfa4feedd8
  | 2021-09-27T19:11:01.162Z | Sep 27 19:11:01 ip-172-31-44-61 web: 2021-09-27T19:11:01.025Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815256 hash=0xc621bd58aa0987a1b36b2c37787f5933badc251b2806fbb3d8f3c7bfa4feedd8
  | 2021-09-27T19:11:01.162Z | Sep 27 19:11:01 ip-172-31-44-61 web: 2021-09-27T19:11:01.026Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815256 hash=0xc621bd58aa0987a1b36b2c37787f5933badc251b2806fbb3d8f3c7bfa4feedd8
  | 2021-09-27T19:11:03.663Z | Sep 27 19:11:01 ip-172-31-44-61 web: 2021-09-27T19:11:01.027Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815256 hash=0xc621bd58aa0987a1b36b2c37787f5933badc251b2806fbb3d8f3c7bfa4feedd8
  | 2021-09-27T19:11:03.663Z | Sep 27 19:11:03 ip-172-31-44-61 web: 2021-09-27T19:11:03.649Z [DEBUG] polygon.jsonrpc: handle: request={"id":"ec24f224-c8bf-49d7-bd40-7070a0121024","jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:03.663Z | Sep 27 19:11:03 ip-172-31-44-61 web: 2021-09-27T19:11:03.649Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=ec24f224-c8bf-49d7-bd40-7070a0121024
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:03 ip-172-31-44-61 web: 2021-09-27T19:11:03.649Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":"ec24f224-c8bf-49d7-bd40-7070a0121024","result":"0xc6ee6"}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.723Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232327712,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.723Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.681811232327712e+15
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.723Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232327712,"result":"0xc6ee6"}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.789Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854836,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x6aeca9a564c210bab9d40bd6c8a41683d8d9cdba","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.789Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854836e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.790Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.790Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854836,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.793Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854838,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x37a09fa7afbbb48537bf94d5609d3e2fe04fa791","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.794Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854838e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.794Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.794Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854838,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.794Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854844,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x3ed6bef5274f9f5556c5cb30ff75a45d2882bfa6","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.794Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854844e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.794Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.794Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854844,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.794Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854842,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x9005d7e31f165e1dd7f443974340baa3d45c0e55","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.795Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854842e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.795Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.795Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854842,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.793Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854840,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x7976bc88d6177d65f37a0e1fc55652f928103bd1","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.795Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.8047474685484e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.795Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.795Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854840,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.797Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854850,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x68200aa9f88d9f185e7bb7e0ea20dd3d773d1a3f","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.797Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.8047474685485e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854850,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854852,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x2adddfff3f64be2cec1af49cf90c60c8a0f51c20","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854852e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854852,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854848,"jsonrpc":"2.0","method":"eth_getBalance","params":["0xaf99678f49fbb9c15ce995d6ba6ad0dbee856304","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854848e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854848,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854846,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x51d4b51f9251912c85af18af6e526ecb976ad810","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854846e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854846,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854856,"jsonrpc":"2.0","method":"eth_getBalance","params":["0xf0d6de16e2c14e0598a18c2b43716d7d0672690c","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.798Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854856e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.799Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.799Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854856,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.800Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854854,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x2079a994e9bbc88496df03a59a0cfa2c9e2af473","0xc7098"]}
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.800Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854854e+14
  | 2021-09-27T19:11:04.914Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.801Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815256 header"
  | 2021-09-27T19:11:07.165Z | Sep 27 19:11:04 ip-172-31-44-61 web: 2021-09-27T19:11:04.801Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854854,"error":{"code":-32600,"message":"Error fetching block number 815256 header"}}"
  | 2021-09-27T19:11:07.165Z | Sep 27 19:11:07 ip-172-31-44-61 web: 2021-09-27T19:11:07.100Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232327713,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:07.165Z | Sep 27 19:11:07 ip-172-31-44-61 web: 2021-09-27T19:11:07.100Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.681811232327713e+15
  | 2021-09-27T19:11:11.167Z | Sep 27 19:11:07 ip-172-31-44-61 web: 2021-09-27T19:11:07.100Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232327713,"result":"0xc6ee6"}
  | 2021-09-27T19:11:11.167Z | Sep 27 19:11:11 ip-172-31-44-61 web: 2021-09-27T19:11:11.055Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815257 hash=0x241a7e1fdda874adce4a207c3ac3a51b93f15868b39f3bb6341ff16b5067dca3
  | 2021-09-27T19:11:11.167Z | Sep 27 19:11:11 ip-172-31-44-61 web: 2021-09-27T19:11:11.057Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815257 hash=0x241a7e1fdda874adce4a207c3ac3a51b93f15868b39f3bb6341ff16b5067dca3
  | 2021-09-27T19:11:11.167Z | Sep 27 19:11:11 ip-172-31-44-61 web: 2021-09-27T19:11:11.058Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815257 hash=0x241a7e1fdda874adce4a207c3ac3a51b93f15868b39f3bb6341ff16b5067dca3
  | 2021-09-27T19:11:13.169Z | Sep 27 19:11:11 ip-172-31-44-61 web: 2021-09-27T19:11:11.059Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815257 hash=0x241a7e1fdda874adce4a207c3ac3a51b93f15868b39f3bb6341ff16b5067dca3
  | 2021-09-27T19:11:13.169Z | Sep 27 19:11:13 ip-172-31-44-61 web: 2021-09-27T19:11:13.039Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815258 hash=0x8b0c6e253e485558d62b1148b776495e7ac91af84ad3c4f1604e4545ad018dc6
  | 2021-09-27T19:11:13.169Z | Sep 27 19:11:13 ip-172-31-44-61 web: 2021-09-27T19:11:13.040Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815258 hash=0x8b0c6e253e485558d62b1148b776495e7ac91af84ad3c4f1604e4545ad018dc6
  | 2021-09-27T19:11:13.169Z | Sep 27 19:11:13 ip-172-31-44-61 web: 2021-09-27T19:11:13.041Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815258 hash=0x8b0c6e253e485558d62b1148b776495e7ac91af84ad3c4f1604e4545ad018dc6
  | 2021-09-27T19:11:15.170Z | Sep 27 19:11:13 ip-172-31-44-61 web: 2021-09-27T19:11:13.042Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815258 hash=0x8b0c6e253e485558d62b1148b776495e7ac91af84ad3c4f1604e4545ad018dc6
  | 2021-09-27T19:11:15.170Z | Sep 27 19:11:15 ip-172-31-44-61 web: 2021-09-27T19:11:15.035Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815259 hash=0xcd149b62e4c04feef6814d9cc9be453d92f2b4f7baf728fbc9580a7f5c1100c0
  | 2021-09-27T19:11:15.170Z | Sep 27 19:11:15 ip-172-31-44-61 web: 2021-09-27T19:11:15.036Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815259 hash=0xcd149b62e4c04feef6814d9cc9be453d92f2b4f7baf728fbc9580a7f5c1100c0
  | 2021-09-27T19:11:15.170Z | Sep 27 19:11:15 ip-172-31-44-61 web: 2021-09-27T19:11:15.037Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815259 hash=0xcd149b62e4c04feef6814d9cc9be453d92f2b4f7baf728fbc9580a7f5c1100c0
  | 2021-09-27T19:11:16.421Z | Sep 27 19:11:15 ip-172-31-44-61 web: 2021-09-27T19:11:15.038Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815259 hash=0xcd149b62e4c04feef6814d9cc9be453d92f2b4f7baf728fbc9580a7f5c1100c0
  | 2021-09-27T19:11:16.421Z | Sep 27 19:11:16 ip-172-31-44-61 web: 2021-09-27T19:11:16.409Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232327714,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:16.421Z | Sep 27 19:11:16 ip-172-31-44-61 web: 2021-09-27T19:11:16.409Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.681811232327714e+15
  | 2021-09-27T19:11:17.172Z | Sep 27 19:11:16 ip-172-31-44-61 web: 2021-09-27T19:11:16.409Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232327714,"result":"0xc6ee6"}
  | 2021-09-27T19:11:17.172Z | Sep 27 19:11:17 ip-172-31-44-61 web: 2021-09-27T19:11:17.021Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815260 hash=0xfdfd284be797a50a77268024acbcc779739335654e7c78f040477ffa59836760
  | 2021-09-27T19:11:17.172Z | Sep 27 19:11:17 ip-172-31-44-61 web: 2021-09-27T19:11:17.022Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815260 hash=0xfdfd284be797a50a77268024acbcc779739335654e7c78f040477ffa59836760
  | 2021-09-27T19:11:17.172Z | Sep 27 19:11:17 ip-172-31-44-61 web: 2021-09-27T19:11:17.035Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815260 hash=0xfdfd284be797a50a77268024acbcc779739335654e7c78f040477ffa59836760
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:17 ip-172-31-44-61 web: 2021-09-27T19:11:17.036Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815260 hash=0xfdfd284be797a50a77268024acbcc779739335654e7c78f040477ffa59836760
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.449Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232327716,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.449Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.681811232327716e+15
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.449Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232327716,"result":"0xc6ee6"}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.525Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854863,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x7976bc88d6177d65f37a0e1fc55652f928103bd1","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.525Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854859,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x6aeca9a564c210bab9d40bd6c8a41683d8d9cdba","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.525Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854859e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.525Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.525Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854859,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.525Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854863e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854863,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.525Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854861,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x37a09fa7afbbb48537bf94d5609d3e2fe04fa791","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854861e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854861,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854867,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x3ed6bef5274f9f5556c5cb30ff75a45d2882bfa6","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854867e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854865,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x9005d7e31f165e1dd7f443974340baa3d45c0e55","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854865e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854865,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.526Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854867,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.529Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854869,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x51d4b51f9251912c85af18af6e526ecb976ad810","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.529Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854869e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854869,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.529Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854871,"jsonrpc":"2.0","method":"eth_getBalance","params":["0xaf99678f49fbb9c15ce995d6ba6ad0dbee856304","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854871e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854871,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854873,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x68200aa9f88d9f185e7bb7e0ea20dd3d773d1a3f","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854873e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854873,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854875,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x2adddfff3f64be2cec1af49cf90c60c8a0f51c20","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854875e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.530Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854875,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.531Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854877,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x2079a994e9bbc88496df03a59a0cfa2c9e2af473","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.531Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854877e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.531Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.531Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854877,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.531Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854879,"jsonrpc":"2.0","method":"eth_getBalance","params":["0xf0d6de16e2c14e0598a18c2b43716d7d0672690c","0xc709c"]}
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.531Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854879e+14
  | 2021-09-27T19:11:19.673Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.531Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815260 header"
  | 2021-09-27T19:11:21.674Z | Sep 27 19:11:19 ip-172-31-44-61 web: 2021-09-27T19:11:19.531Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854879,"error":{"code":-32600,"message":"Error fetching block number 815260 header"}}"
  | 2021-09-27T19:11:21.674Z | Sep 27 19:11:21 ip-172-31-44-61 web: 2021-09-27T19:11:21.642Z [DEBUG] polygon.jsonrpc: handle: request={"id":"b3f689b8-f6bb-45e2-a724-274fdf49dd56","jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:21.674Z | Sep 27 19:11:21 ip-172-31-44-61 web: 2021-09-27T19:11:21.642Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=b3f689b8-f6bb-45e2-a724-274fdf49dd56
  | 2021-09-27T19:11:24.925Z | Sep 27 19:11:21 ip-172-31-44-61 web: 2021-09-27T19:11:21.642Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":"b3f689b8-f6bb-45e2-a724-274fdf49dd56","result":"0xc6ee6"}
  | 2021-09-27T19:11:24.925Z | Sep 27 19:11:24 ip-172-31-44-61 web: 2021-09-27T19:11:24.762Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232327718,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:24.925Z | Sep 27 19:11:24 ip-172-31-44-61 web: 2021-09-27T19:11:24.762Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.681811232327718e+15
  | 2021-09-27T19:11:27.176Z | Sep 27 19:11:24 ip-172-31-44-61 web: 2021-09-27T19:11:24.762Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232327718,"result":"0xc6ee6"}
  | 2021-09-27T19:11:27.176Z | Sep 27 19:11:27 ip-172-31-44-61 web: 2021-09-27T19:11:27.061Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815261 hash=0x9d782c32a089792e5e88a8a3c2e2f41c5141c8ec83e01743e917e10b56a90017
  | 2021-09-27T19:11:27.176Z | Sep 27 19:11:27 ip-172-31-44-61 web: 2021-09-27T19:11:27.073Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815261 hash=0x9d782c32a089792e5e88a8a3c2e2f41c5141c8ec83e01743e917e10b56a90017
  | 2021-09-27T19:11:27.176Z | Sep 27 19:11:27 ip-172-31-44-61 web: 2021-09-27T19:11:27.080Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815261 hash=0x9d782c32a089792e5e88a8a3c2e2f41c5141c8ec83e01743e917e10b56a90017
  | 2021-09-27T19:11:27.426Z | Sep 27 19:11:27 ip-172-31-44-61 web: 2021-09-27T19:11:27.080Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815261 hash=0x9d782c32a089792e5e88a8a3c2e2f41c5141c8ec83e01743e917e10b56a90017
  | 2021-09-27T19:11:27.426Z | Sep 27 19:11:27 ip-172-31-44-61 web: 2021-09-27T19:11:27.186Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854881,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xc709d",false]}
  | 2021-09-27T19:11:27.426Z | Sep 27 19:11:27 ip-172-31-44-61 web: 2021-09-27T19:11:27.186Z [DEBUG] polygon.dispatcher: request: method=eth_getBlockByNumber id=1.80474746854881e+14
  | 2021-09-27T19:11:29.177Z | Sep 27 19:11:27 ip-172-31-44-61 web: 2021-09-27T19:11:27.186Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":180474746854881,"result":null}
  | 2021-09-27T19:11:29.177Z | Sep 27 19:11:29 ip-172-31-44-61 web: 2021-09-27T19:11:29.018Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815262 hash=0x13ca0b8f3f1a40e6841ea9d46175390a1c7398546baf1be51c6434417071a78d
  | 2021-09-27T19:11:29.177Z | Sep 27 19:11:29 ip-172-31-44-61 web: 2021-09-27T19:11:29.034Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815262 hash=0x13ca0b8f3f1a40e6841ea9d46175390a1c7398546baf1be51c6434417071a78d
  | 2021-09-27T19:11:29.177Z | Sep 27 19:11:29 ip-172-31-44-61 web: 2021-09-27T19:11:29.035Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815262 hash=0x13ca0b8f3f1a40e6841ea9d46175390a1c7398546baf1be51c6434417071a78d
  | 2021-09-27T19:11:31.178Z | Sep 27 19:11:29 ip-172-31-44-61 web: 2021-09-27T19:11:29.036Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815262 hash=0x13ca0b8f3f1a40e6841ea9d46175390a1c7398546baf1be51c6434417071a78d
  | 2021-09-27T19:11:31.178Z | Sep 27 19:11:31 ip-172-31-44-61 web: 2021-09-27T19:11:31.020Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815263 hash=0x059865df300285b231df3e29528ec73403c4d3778007986385f089b9686ff36b
  | 2021-09-27T19:11:31.178Z | Sep 27 19:11:31 ip-172-31-44-61 web: 2021-09-27T19:11:31.021Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815263 hash=0x059865df300285b231df3e29528ec73403c4d3778007986385f089b9686ff36b
  | 2021-09-27T19:11:31.178Z | Sep 27 19:11:31 ip-172-31-44-61 web: 2021-09-27T19:11:31.040Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815263 hash=0x059865df300285b231df3e29528ec73403c4d3778007986385f089b9686ff36b
  | 2021-09-27T19:11:33.179Z | Sep 27 19:11:31 ip-172-31-44-61 web: 2021-09-27T19:11:31.044Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815263 hash=0x059865df300285b231df3e29528ec73403c4d3778007986385f089b9686ff36b
  | 2021-09-27T19:11:33.179Z | Sep 27 19:11:33 ip-172-31-44-61 web: 2021-09-27T19:11:33.024Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815264 hash=0x1dd43d65c280abc183069b309216b04dbdcff71ef7c24d604447f47971cce11d
  | 2021-09-27T19:11:33.179Z | Sep 27 19:11:33 ip-172-31-44-61 web: 2021-09-27T19:11:33.024Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815264 hash=0x1dd43d65c280abc183069b309216b04dbdcff71ef7c24d604447f47971cce11d
  | 2021-09-27T19:11:33.179Z | Sep 27 19:11:33 ip-172-31-44-61 web: 2021-09-27T19:11:33.033Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815264 hash=0x1dd43d65c280abc183069b309216b04dbdcff71ef7c24d604447f47971cce11d
  | 2021-09-27T19:11:36.681Z | Sep 27 19:11:33 ip-172-31-44-61 web: 2021-09-27T19:11:33.035Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815264 hash=0x1dd43d65c280abc183069b309216b04dbdcff71ef7c24d604447f47971cce11d
  | 2021-09-27T19:11:36.681Z | Sep 27 19:11:36 ip-172-31-44-61 web: 2021-09-27T19:11:36.456Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232327720,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:36.681Z | Sep 27 19:11:36 ip-172-31-44-61 web: 2021-09-27T19:11:36.456Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.68181123232772e+15
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:36 ip-172-31-44-61 web: 2021-09-27T19:11:36.456Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232327720,"result":"0xc6ee6"}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.495Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232327722,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.495Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.681811232327722e+15
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.495Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232327722,"result":"0xc6ee6"}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.569Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854883,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x6aeca9a564c210bab9d40bd6c8a41683d8d9cdba","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.569Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854883e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.569Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.569Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854883,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.573Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854885,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x37a09fa7afbbb48537bf94d5609d3e2fe04fa791","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.573Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854885e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.573Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.573Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854885,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.573Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854887,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x7976bc88d6177d65f37a0e1fc55652f928103bd1","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.573Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854887e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.573Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.573Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854887,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854893,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x51d4b51f9251912c85af18af6e526ecb976ad810","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854893e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854893,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854889,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x9005d7e31f165e1dd7f443974340baa3d45c0e55","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854889e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854889,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854891,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x3ed6bef5274f9f5556c5cb30ff75a45d2882bfa6","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854891e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.574Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854891,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854895,"jsonrpc":"2.0","method":"eth_getBalance","params":["0xaf99678f49fbb9c15ce995d6ba6ad0dbee856304","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854895e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854895,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854899,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x2adddfff3f64be2cec1af49cf90c60c8a0f51c20","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854899e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854901,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x2079a994e9bbc88496df03a59a0cfa2c9e2af473","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854901e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854899,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854901,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854897,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x68200aa9f88d9f185e7bb7e0ea20dd3d773d1a3f","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.578Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854897e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.579Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.579Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854897,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.580Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854903,"jsonrpc":"2.0","method":"eth_getBalance","params":["0xf0d6de16e2c14e0598a18c2b43716d7d0672690c","0xc70a0"]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.580Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854903e+14
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.580Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815264 header"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.580Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854903,"error":{"code":-32600,"message":"Error fetching block number 815264 header"}}"
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.640Z [DEBUG] polygon.jsonrpc: handle: request={"id":"7b3c3899-1fea-4439-aa23-371244e373d2","jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:39.683Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.640Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=7b3c3899-1fea-4439-aa23-371244e373d2
  | 2021-09-27T19:11:43.184Z | Sep 27 19:11:39 ip-172-31-44-61 web: 2021-09-27T19:11:39.640Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":"7b3c3899-1fea-4439-aa23-371244e373d2","result":"0xc6ee6"}
  | 2021-09-27T19:11:43.184Z | Sep 27 19:11:43 ip-172-31-44-61 web: 2021-09-27T19:11:43.074Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x number=815265 hash=0xc6c0206d8c31ae98391cfbca5e0f9a61224b71268b7747c3ef5080f4a63dc009
  | 2021-09-27T19:11:43.184Z | Sep 27 19:11:43 ip-172-31-44-61 web: 2021-09-27T19:11:43.097Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW number=815265 hash=0xc6c0206d8c31ae98391cfbca5e0f9a61224b71268b7747c3ef5080f4a63dc009
  | 2021-09-27T19:11:43.184Z | Sep 27 19:11:43 ip-172-31-44-61 web: 2021-09-27T19:11:43.098Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh number=815265 hash=0xc6c0206d8c31ae98391cfbca5e0f9a61224b71268b7747c3ef5080f4a63dc009
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:43 ip-172-31-44-61 web: 2021-09-27T19:11:43.098Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU number=815265 hash=0xc6c0206d8c31ae98391cfbca5e0f9a61224b71268b7747c3ef5080f4a63dc009
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.835Z [DEBUG] polygon.jsonrpc: handle: request={"id":2681811232327724,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.835Z [DEBUG] polygon.dispatcher: request: method=eth_blockNumber id=2.681811232327724e+15
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.835Z [DEBUG] polygon.jsonrpc: handle: response={"jsonrpc":"2.0","id":2681811232327724,"result":"0xc6ee6"}
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.913Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854906,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x6aeca9a564c210bab9d40bd6c8a41683d8d9cdba","0xc70a1"]}
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.913Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854906e+14
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.913Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815265 header"
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.913Z [DEBUG] polygon.jsonrpc: handle: response="{"jsonrpc":"2.0","id":180474746854906,"error":{"code":-32600,"message":"Error fetching block number 815265 header"}}"
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.919Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854910,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x7976bc88d6177d65f37a0e1fc55652f928103bd1","0xc70a1"]}
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.919Z [DEBUG] polygon.jsonrpc: handle: request={"id":180474746854908,"jsonrpc":"2.0","method":"eth_getBalance","params":["0x37a09fa7afbbb48537bf94d5609d3e2fe04fa791","0xc70a1"]}
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.919Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.8047474685491e+14
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.919Z [DEBUG] polygon.dispatcher: request: method=eth_getBalance id=1.80474746854908e+14
  | 2021-09-27T19:11:44.935Z | Sep 27 19:11:44 ip-172-31-44-61 web: 2021-09-27T19:11:44.919Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_getBalance err="Error fetching block number 815265 header"


```

### LINKED ISSUE #169: New node `fail to write block` error when syncing near most recent block
### Description

When a new peer is syncing, it looks like after the last batch sync of blocks, we sometimes get a failure:
```
`[ERROR] polygon.consensus.syncer: failed to write block: err="parent of 0x5dda26ea7e3157baa4fa07746be00c43c2f084a946a2fb171634650f34efbc27 (853608) not found: 0xc2cbd6ac4ed7b7c340f6070bc2e13caef6ec582e14acffca41f49f9ae50760c9"`
```

See larger log snippet:
```
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.442Z [INFO]  polygon.blockchain: write blocks: num=10 from=852347 to=852356 parent=0xcb750c6af46655acc5d8a2ef0ff555da7cace894c761da985a99a3d3862dbeb5
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.479Z [INFO]  polygon.blockchain: new block: number=852347 hash=0x12039ac1d933d9a0c4761ae84ecbb227a7e8232b2b590d0b90965037e6e9fe51 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.480Z [INFO]  polygon.blockchain: new block: number=852348 hash=0xe550e56c73dd0695a218cb509e993b18a0c7229e0a6923b2caee328c76b60029 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.482Z [INFO]  polygon.blockchain: new block: number=852349 hash=0xd1464576099a359200620cfa5e8c468b8efa61affe8843fef3260528a4b9f2c8 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.482Z [INFO]  polygon.blockchain: new block: number=852350 hash=0x36c9b9114dd72fa7c3d6c6c7d78910e2acec6a038e9860c1571ea1592b072e2a txns=0 generation_time_in_sec=10
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.483Z [INFO]  polygon.blockchain: new block: number=852351 hash=0xf1f1e6c70bf3caedb625e2087b5c1df5075bd1550c6cd2c7e914462e9479933e txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.485Z [INFO]  polygon.blockchain: new block: number=852352 hash=0x2a0f4cef8616c30d40d9dcaa9d421e31545fac74d047b758ae95fe07861714f5 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.486Z [INFO]  polygon.blockchain: new block: number=852353 hash=0x7d0b63698c309d5aab3f28d64bd0cd30ce73356c003151509ca9585b03a3c346 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.486Z [INFO]  polygon.blockchain: new block: number=852354 hash=0x1d83f22145427ccf4861da7ebfc5374ebd03ffd004e28f42669e5ba63b481e99 txns=1 generation_time_in_sec=10
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.489Z [INFO]  polygon.blockchain: new block: number=852355 hash=0x2d3147d271012dd927da8d0fc41f9c421594abe9a86c62ddd147fbbcc61f236e txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.490Z [INFO]  polygon.blockchain: new block: number=852356 hash=0x264a473677e736779edb91cc4753b90cf368d04f85395ea913114583599ee7e8 txns=0 generation_time_in_sec=2
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.490Z [INFO]  polygon.blockchain: new head: hash=0x264a473677e736779edb91cc4753b90cf368d04f85395ea913114583599ee7e8 number=852356
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.492Z [INFO]  polygon.blockchain: write block: num=853608 parent=0xc2cbd6ac4ed7b7c340f6070bc2e13caef6ec582e14acffca41f49f9ae50760c9
Sep 29 15:27:04 ip-172-31-25-125 main[72967]: 2021-09-29T15:27:04.496Z [ERROR] polygon.consensus.syncer: failed to write block: err="parent of 0x5dda26ea7e3157baa4fa07746be00c43c2f084a946a2fb171634650f34efbc27 (853608) not found: 0xc2cbd6ac4ed7b7c340f6070bc2e13caef6ec582e14acffca41f49f9ae50760c9"
```

Restarting the node fixes the issue.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `96be904 `
* branch that causes this issue `develop`

### Steps to reproduce

1. Have 4-node validator set writing and validating new blocks
2. Connect 5th peer and observe `polygon.blockchain: new block` output that occurs during syncing
3. When almost synced to the current block, we see the error above

### Expected behaviour

There shouldn't be an error that requires us to restart the node.

### Actual behaviour

An error stops the node from further syncing, requiring a restart.

### PR DESCRIPTION
**Pull request by Kourin1996**
# Description

Relevant issues: https://github.com/0xPolygon/polygon-sdk/issues/162, https://github.com/0xPolygon/polygon-sdk/issues/167, https://github.com/0xPolygon/polygon-sdk/issues/169

This PR fixes that node cannot sync block with peer sometimes. It happens that node cannot join IBFT network.
The fixes consist of following bug fixes:

1. Syncer doesn't have peer list
In IBFT initialization calles `syncer.start()` after `setupSnapshot()` is done. `syncer.start()` start loop to subscribe to connection event to know peer. But `syncer.start()` won't get connection events if `setupSnapshot()` takes much time to finish because establishing connections is done before `syncer.start()` is called. 
This PR fixes order or calls.

2. peer's number is not correct
IBFT can know peer's latest block number when it calles `BestPeer()` in syncer. But this number is zero until syncer receives block from the peer. For that reason, IBFT cannot sync block until some peers send latest block to the node. But syncer can know peer's latest block number on handshaking. So this PR lets syncer initialize peer's number when it adds peer.

3. Close gRPC stream
Node broadcasts to even closed peers and shows error log. This PR lets syncer delete closed peer from peer list after disconnected.

## Updates [4th Oct 2021]

I added some new updates.

1. Peer is sending latest block number as difficulty. Peer's difficulty is used to find best peer in sync process. This bug causes missing best peer. I made peer send correct difficulty at https://github.com/0xPolygon/polygon-sdk/pull/164/commits/5170883f9de116c18ad32640c46af8e9de5f1a84.

2. Node hangs up in WatchSyncWithPeer after disconnected to peer. In WatchSyncWithPeer, node gets peer's block from queue. WatchSyncWithPeer waits until new block is added to queue. If peer has disconnected already, new block will no longer added to queue. That's why node stop any process. I made syncer check connectivity everyloop at https://github.com/0xPolygon/polygon-sdk/pull/164/commits/1ad86eb31f1a045ab3f2583d4a0c0d649b602e2b.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

**Comment by mrwillis** [comment]
@Kourin1996 what is the point of the two statuses here?

This status contains a hash and number

https://github.com/0xPolygon/polygon-sdk/blob/develop/protocol/syncer.go#L29

But there is also a `number` and `hash` with a comment of "current status" right under it.

```go
type syncPeer struct {
	peer   peer.ID
	conn   *grpc.ClientConn
	client proto.V1Client
	status *Status

	// current status ??
	number uint64
	hash   types.Hash
```

What is the difference?

**Comment by Kourin1996** [comment]
Hi, @mrwillis. Thank you for your question. I investigated current implementation and I fixed following points:
(1) Remove `hash` and `number` from `syncPeer` and use `status.Number` always.
(2) syncPeer's `Status` is not updated when syncer receives update message from peer. So let syncer update status in this case.

**Review by lazartravica — APPROVED** [review]

File: protocol/syncer.go [hunk 1]
```diff
@@ -410,8 +456,12 @@ func (s *Syncer) WatchSyncWithPeer(p *syncPeer, handler func(b *types.Block) boo
 
 	// listen and enqueue the messages
 	for {
-		b := p.popBlock()
+		if p.IsClosed() {
+			s.logger.Error("Connection to a peer has closed already", "id", p.peer)
```
Comment (Vuksan) [inline protocol/syncer.go]: Maybe a `Warn` or even `Info` log level would fit better here than the `Error` one.
It is my understanding that this can be normal behavior, so we only inform the node operator that the connection to this peer has been closed - it isn't really an error.

What do you think?

File: protocol/syncer.go [hunk 2]
```diff
@@ -328,13 +365,22 @@ func (s *Syncer) HandleUser(peerID peer.ID, conn *grpc.ClientConn) error {
...
 		client:    clt,
 		status:    status,
 		enqueueCh: make(chan struct{}),
 	}
 	return nil
 }
 
+func (s *Syncer) DeleteUser(peerID peer.ID) error {
+	if p, ok := s.peers[peerID]; ok {
+		p.conn.Close()
```
Comment (Vuksan) [inline protocol/syncer.go]: My IDE is reporting that `Close()` can return an error that we're not handling.
Should we handle it, or is it alright the way it is?

File: protocol/syncer.go [hunk 3]
```diff
@@ -226,10 +251,18 @@ func (s *Syncer) enqueueBlock(peerID peer.ID, b *types.Block) {
 	}
 }
 
+func (s *Syncer) updatePeerStatus(peerID peer.ID, status *Status) {
+	s.logger.Debug("update peer status", "peer", peerID, "number", status.Number, "hash", status.Hash, "difficulty", status.Difficulty)
```
Comment (Vuksan) [inline protocol/syncer.go]: Just a bit more info in the logs:
```suggestion
	s.logger.Debug("update peer status", "peer", peerID, "latest block number", status.Number, "latest block hash", status.Hash, "difficulty", status.Difficulty)
```

**Review by Vuksan — COMMENTED** [review]
Great job @Kourin1996! 🙇 
I left some minor nitpicks

File: protocol/syncer.go (hunk 2 above)
Comment (Kourin1996) [reply protocol/syncer.go]: Thank you! Fixed at https://github.com/0xPolygon/polygon-sdk/pull/164/commits/8cf4b8df41b55552157211259f1b26b272b1f631

File: protocol/syncer.go (hunk 3 above)
Comment (Kourin1996) [reply protocol/syncer.go]: Thank you for good suggestion. Fixed at https://github.com/0xPolygon/polygon-sdk/pull/164/commits/f93af087fb5d9ad4f1e630830d1f989c59657b82

File: protocol/syncer.go (hunk 1 above)
Comment (Kourin1996) [reply protocol/syncer.go]: Yes, you're right. Exiting from this function, but process can continue. So `warn` or `info` is more suitable. I think `warn` is used for notifying some issues when something which is unexpected happens but can continue to process. We're expecting process reach this branch sometimes. So `info` is the best, I think.
Fixed at https://github.com/0xPolygon/polygon-sdk/pull/164/commits/27689680b325deef0775dee8083ce94608069b36

**Review by zivkovicmilos — APPROVED** [review]
Great and clean as always 💯

**Review by Vuksan — APPROVED** [review]
🚀
