### PR TITLE
TxPool gas limit verification + txn error recover

### LINKED ISSUE #174: Tx gasLimit > 100000000 causes gas limit reached error and stuck tx
### Description

It seems that setting a tx gasLimit higher than 100000000 results in a pending tx that will never confirm. Any txs after this from the same account will also get stuck with no way of overwriting them.

https://github.com/0xPolygon/polygon-sdk/blob/335e78199b52c768e9b00c3f955e9a42a3ce5ed4/consensus/ibft/ibft.go#L356

Looking at the code above, a block header is initialized with its gasLimit set to 100000000. All tx gasLimits within that same block must not surpass this limit or else this issue occurs.

Aside from these transactions getting 'stuck', I observed many occurrences of the following log messages:
```
[ERROR] polygon: failed to apply tx: err=\"gas limit reached in the pool\""}

[31mERROR\u001b[0m\tbasichost\tfailed to resolve local interface addresses\t{\"error\": \"route ip+net: netlinkrib: too many open files\"}"}

[ERROR] polygon.network: failed to dial bootnode: err=\"peer rejected; insufficient capacity\""}
```

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `develop`
* branch that causes this issue `96be904`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

1. Send a tx with gasLimit 5,000,000,000
2. Observe the `gas limit reached in the pool` log messages
3. Observe that subsequent txs from the same address cannot be processed
4. Attempting to override the nonce of the stuck tx (with a lower gasLimit but higher gasPrice) had no effect

### Expected behaviour

I expect there to be some sort of threshold that a tx's gasLimit must be under before it can be accepted. This threshold should be well under the hardcoded header gasLimit (aka Transition.gasPool) of 100000000.

### Actual behaviour

A tx with an extremely high gasLimit still gets picked up resulting in indefinite pending txs and error messages.

### PR DESCRIPTION
**Pull request by 0xpanoramix**
# Description

This PR resolves #174 .

It adds two features :

1. A new verification whenever a transaction is submitted to the transaction pool operator.
2. Any detected error while writing transaction to a block is now marked as recoverable or not recoverable, indicating if the transaction has to be discarded or not. 

# Changes include

- [X] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [X] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

File: state/executor.go [hunk 1]
```diff
@@ -349,36 +362,62 @@ func (t *Transition) apply(msg *types.Transaction) (result *runtime.ExecutionRes
...
+			IsRecoverable: true,
+		}
+	}
+
+	// the amount of gas required is lower than the specified block gas limit
+	if msg.Gas > t.gasPool {
+		return nil, &TransactionApplicationError{
+			Err:           ErrBlockLimitExceeded,
+			IsRecoverable: false,
+		}
```
Comment (Kourin1996) [inline state/executor.go]: Just confirm. Why this is not recoverable? This error happens if you can't add this tx to block because block doesn't have enough remaining gas to take this tx. So I thought you could add this tx in next block.

Did you want to check if tx gas doesn't exceed BlockGasLimit?

File: txpool/txpool.go [hunk 2]
```diff
@@ -219,6 +219,16 @@ func (t *TxPool) addImpl(ctx string, tx *types.Transaction) error {
...
 }
 
+// DecreaseAccountNonce resets the nonce attached to an account whenever a transaction produce an error which is not
+// recoverable, meaning the transaction will be discarded.
+//
+// Since any discarded transaction should not affect the world state, the nextNonce should be reset to the value
+// it was set to before the transaction appeared.
+func (t *TxPool) DecreaseAccountNonce(tx *types.Transaction) {
+	txnsQueue := t.accountQueues[tx.From]
+	txnsQueue.nextNonce -= 1
```
Comment (Kourin1996) [inline txpool/txpool.go]: you might want to check if accountQueues has record for tx.From just in case

**Review by Kourin1996 — CHANGES_REQUESTED** [review]
Hi, Thank you for the PR. I've left small comments. I'd appreciate if you could check and fix if need. Thanks.

File: state/executor.go (hunk 1 above)
Comment (0xpanoramix) [reply state/executor.go]: > Did you want to check if tx gas doesn't exceed BlockGasLimit ?

Exactly, if the block has a gas limit of 5, and the gas provided in the message is 6, it will never be able to fit in a block.
This check is a special case of the third check (`the amount of gas required is available in the block`).

Comment (Kourin1996) [reply state/executor.go]: Please note that t.gasPool doesn't equal to BlockGasLimit. If some transactions are processed already, t.gasPool has consumed the total of used gas already.

File: e2e/txpool_test.go [hunk 3]
```diff
@@ -276,3 +277,185 @@ func TestTxPool_TransactionCoalescing(t *testing.T) {
 		"To address balance mismatch after gap transaction",
 	)
 }
+
+func TestInvalidTransactionRecover(t *testing.T) {
```
Comment (zivkovicmilos) [inline e2e/txpool_test.go:281]: Would love to see a description / test scenario above this test 🙏

File: state/executor.go [hunk 4]
```diff
@@ -330,12 +333,22 @@ var (
...
 	ErrNotEnoughFundsForGas  = fmt.Errorf("not enough funds to cover gas costs")
 	ErrBlockLimitReached     = fmt.Errorf("gas limit reached in the pool")
+	ErrBlockLimitExceeded     = fmt.Errorf("specified gas exceed block gas limit")
 	ErrIntrinsicGasOverflow  = fmt.Errorf("overflow in intrinsic gas calculation")
 	ErrNotEnoughIntrinsicGas = fmt.Errorf("not enough gas supplied for intrinsic gas costs")
 	ErrNotEnoughFunds        = fmt.Errorf("not enough funds for transfer with given value")
 )
 
-func (t *Transition) apply(msg *types.Transaction) (result *runtime.ExecutionResult, err error) {
+type TransactionApplicationError struct {
```
Comment (zivkovicmilos) [inline state/executor.go]: What do you think about renaming this to `TransitionApplicationError`, since it applies to state transitions instead of just regular transactions?

@Kourin1996 @lazartravica @Vuksan

File: state/executor.go [hunk 5]
```diff
@@ -330,12 +333,22 @@ var (
 	ErrNonceIncorrect        = fmt.Errorf("incorrect nonce")
 	ErrNotEnoughFundsForGas  = fmt.Errorf("not enough funds to cover gas costs")
 	ErrBlockLimitReached     = fmt.Errorf("gas limit reached in the pool")
+	ErrBlockLimitExceeded     = fmt.Errorf("specified gas exceed block gas limit")
```
Comment (zivkovicmilos) [inline state/executor.go]: Typo here, should be `exceeds`

File: txpool/txpool.go [hunk 6]
```diff
@@ -219,6 +219,18 @@ func (t *TxPool) addImpl(ctx string, tx *types.Transaction) error {
 	return nil
 }
 
+// DecreaseAccountNonce resets the nonce attached to an account whenever a transaction produce an error which is not
+// recoverable, meaning the transaction will be discarded.
+//
+// Since any discarded transaction should not affect the world state, the nextNonce should be reset to the value
+// it was set to before the transaction appeared.
+func (t *TxPool) DecreaseAccountNonce(tx *types.Transaction) {
+	if t.accountQueues[tx.From] != nil {
```
Comment (zivkovicmilos) [inline txpool/txpool.go:228]: Please note that this should be thread safe after we merge PR #178

File: state/executor.go [hunk 7]
```diff
@@ -184,25 +184,28 @@ func (t *Transition) Receipts() []*types.Receipt {
...
 	var err error
 	if txn.From == emptyFrom {
 		// Decrypt the from address
 		txn.From, err = signer.Sender(txn)
 		if err != nil {
-			return err
+			return &TransactionApplicationError{
+				Err:           err,
+				IsRecoverable: false,
+			}
```
Comment (zivkovicmilos) [inline state/executor.go]: I see that we repeat this construction logic a lot of times when returning.

What do you think about separating it out into a small helper function like `generateTransitionErr`, or something along those lines?

**Review by zivkovicmilos — CHANGES_REQUESTED** [review]
Looks alright so far 👍 
Excellent work on the tests 💯 

Left a few comments we should discuss

File: state/executor.go (hunk 4 above)
Comment (Kourin1996) [reply state/executor.go]: Agree with @zivkovicmilos's idea

File: state/executor.go (hunk 1 above)
Comment (0xpanoramix) [reply state/executor.go]: Thank you for reporting the error, I've moved this verification outside the apply function since I don't have access to the block gas limit inside of it.
It is now in the `writeNewBlock` function in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/ecd78d43b1ef64d0357f50ed924f89b926f5f6bc.

File: txpool/txpool.go (hunk 6 above)
Comment (0xpanoramix) [reply txpool/txpool.go:228]: Good to know, thank you !

File: state/executor.go [hunk 8]
```diff
@@ -330,12 +330,29 @@ var (
...
+	ErrBlockLimitExceeded     = fmt.Errorf("specified gas exceeds block gas limit")
 	ErrIntrinsicGasOverflow  = fmt.Errorf("overflow in intrinsic gas calculation")
 	ErrNotEnoughIntrinsicGas = fmt.Errorf("not enough gas supplied for intrinsic gas costs")
 	ErrNotEnoughFunds        = fmt.Errorf("not enough funds for transfer with given value")
 )
 
-func (t *Transition) apply(msg *types.Transaction) (result *runtime.ExecutionResult, err error) {
+type TransitionApplicationError struct {
+	Err				error
+	IsRecoverable	bool // Should the transaction be discarded, or put back in the queue.
```
Comment (Kourin1996) [inline state/executor.go]: I think you can format this parr

File: consensus/ibft/ibft.go [hunk 9]
```diff
@@ -388,11 +388,20 @@ func (i *Ibft) buildBlock(snap *Snapshot, parent *types.Header) (*types.Block, e
 		if txn == nil {
 			break
 		}
-		if err := transition.Write(txn); err != nil {
-			retFn()
-			break
+
+		if txn.ExceedsBlockGasLimit(header.GasLimit) {
+			i.txpool.DecreaseAccountNonce(txn)
```
Comment (Kourin1996) [inline consensus/ibft/ibft.go:393]: Just confirm. You don't need to put tx back in this case?

File: e2e/txpool_test.go (hunk 3 above)
Comment (0xpanoramix) [reply e2e/txpool_test.go:281]: Added in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/041dac89638041f72990dd1db784ba4a74b498cf

File: state/executor.go (hunk 4 above)
Comment (0xpanoramix) [reply state/executor.go]: Added in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/1c2736e2686c3503d22ac12cc23a9206a4c28066

File: state/executor.go (hunk 5 above)
Comment (0xpanoramix) [reply state/executor.go]: Fixed in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/081f3c0feb45ed866bc62681f88479ced7fdc1f0

File: state/executor.go (hunk 7 above)
Comment (0xpanoramix) [reply state/executor.go]: Added in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/1c2736e2686c3503d22ac12cc23a9206a4c28066

**Review by zivkovicmilos — APPROVED** [review]
Thank you for resolving these mini changes 🙏 

Good to go 🚀

File: state/executor.go (hunk 8 above)
Comment (0xpanoramix) [reply state/executor.go]: Fixed in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/56679fcc33ff00437b754ddeeeabab08d1a94787

**Review by Kourin1996 — APPROVED** [review]
LGTM 👏

**Review by lazartravica — APPROVED** [review]
Well done @PtitLuca 

I love this pattern with recoverable/unrecoverable errors an I'm glad the tests are easy to read as well.

🤘
