### PR TITLE
[TxPool] Self pruning stuck transactions

### LINKED ISSUE #226: Txpool pending and queued sets are never pruned, causing eventual overflow or DOS
### Description

There is no mechanism to reduce transactions that might be eventually valid from the pending or queued sets, causing perpetual growth. 

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 6efebc6a92f885082620ed2a8d59e37d4d27074c
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
Create a chain with 4 validators. Create an a premine with a balance of 100 ETH. Submit txns with nonce 0...1000 and submit **them immediately without waiting for receipt**, each sending 1 ETH to some random account. Observe the first ~100 transactions get mined. Now the txn pool `pendingQueue` should contain 900 transactions.

These 900 transactions will constantly be popped then re-pushed back onto the queue because they are thrown with a recoverable error which pushes them back onto the queue

https://github.com/0xPolygon/polygon-sdk/blob/6efebc6a92f885082620ed2a8d59e37d4d27074c/consensus/ibft/ibft.go#L406

```
2021-11-18T16:24:28.038-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
```

* Where the issue is, if you know <br />

* Which commands triggered the issue, if any

`./main server`

### Expected behaviour

Transactions that are invalid for a long time should eventually be dropped. 

### Actual behaviour

Transactions that are invalid are constantly re-pushed onto the queue as most of the errors thrown here are recoverable

https://github.com/0xPolygon/polygon-sdk/blob/6efebc6a92f885082620ed2a8d59e37d4d27074c/state/executor.go#L358

### Logs

`txpool_status` on our testnet validator nodes

```
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 1 } }
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 42 } }
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 329 } }
{ jsonrpc: '2.0', id: null, result: { pending: 3292, queued: 1561 } }
{ jsonrpc: '2.0', id: null, result: { pending: 3968, queued: 22 } }
{ jsonrpc: '2.0', id: null, result: { pending: 1145, queued: 14379 } }
{ jsonrpc: '2.0', id: null, result: { pending: 69, queued: 5711 } }
{ jsonrpc: '2.0', id: null, result: { pending: 109, queued: 5629 } }
{ jsonrpc: '2.0', id: null, result: { pending: 256, queued: 5559 } }
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 42 } }
{ jsonrpc: '2.0', id: null, result: { pending: 60, queued: 5736 } }
{ jsonrpc: '2.0', id: null, result: { pending: 3706, queued: 1641 } }
{ jsonrpc: '2.0', id: null, result: { pending: 3630, queued: 1389 } }
{ jsonrpc: '2.0', id: null, result: { pending: 0, queued: 204 } }
```

```
2021-11-18T16:23:40.026-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:23:48.026-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:23:56.022-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:04.025-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:12.027-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:20.027-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:20.027-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:24:28.038-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:28.038-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:24:36.024-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:36.024-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:24:44.028-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:24:52.026-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:25:00.025-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:25:00.025-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:25:08.024-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
2021-11-18T16:25:08.024-0500 [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=985
2021-11-18T16:25:16.023-0500 [ERROR] polygon: failed to apply tx: err="not enough funds to cover gas costs, recoverable [true]"
```

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

There should be some sort of periodic pool pruning as in geth. Geth has a periodic mechanism:

https://github.com/maticnetwork/bor/blob/a9c71eff578c652ddfe00a73267454bed5957ed0/core/tx_pool.go#L1137

And the algorithms:

https://github.com/maticnetwork/bor/blob/a9c71eff578c652ddfe00a73267454bed5957ed0/core/tx_pool.go#L1377
https://github.com/maticnetwork/bor/blob/a9c71eff578c652ddfe00a73267454bed5957ed0/core/tx_pool.go#L1462

### PR DESCRIPTION
**Pull request by dbrajovic**
# Description

This PR addresses the issue of valid "stuck" transactions. These transactions remain in the pool indefinitely due to being considered recoverable by consensus during block building. 

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [ ] I have tested this code manually

# Additional comments

Fixes EDGE-45

### CODE REVIEW

File: txpool/txpool.go [hunk 1]
```diff
@@ -317,6 +321,9 @@ func (p *TxPool) Pop(tx *types.Transaction) {
 	// pop the top most promoted tx
 	account.promoted.pop()
 
+	//	successfully popping an account reset its demotions count to 0
```
Comment (zivkovicmilos) [inline txpool/txpool.go]: Typo here, should be `resets`

**Review by zivkovicmilos — APPROVED** [review]
Lookin' great 🚀

**Review by Kourin1996 — APPROVED** [review]
Looks good to me

**Review by 0xAleksaOpacic — APPROVED** [review]

**Comment by DarianShawn** [comment]
Good to have this feature. 🙌

Just a little confused because of the method name `TxPool.Drop()`.
`DropAccountByTx()` would make it more clearer?

**Comment by dbrajovic** [comment]
> Good to have this feature. 🙌
> 
> Just a little confused because of the method name `TxPool.Drop()`. `DropAccountByTx()` would make it more clearer?

I do agree the naming is a bit unclear in the TxPool's API, but it was written that way for consistency. The only reason a transaction is needed as an argument is because `address` and `nonce` can be fetched from it.

In a future PR, this naming issue will get tackled.

File: txpool/txpool.go (hunk 1 above)
Comment (dbrajovic) [reply txpool/txpool.go]: [Fixed](https://github.com/0xPolygon/polygon-edge/pull/541/commits/14064c8dbc0780a5ab75a85499bf9127fb6d608b)
