### PR TITLE
Fix hash calculation for proposal for go-ibft's update

### LINKED ISSUE #1169: Upgrade go-ibft package version to 0.1.0
Upgrade go-ibft package version to 0.1.0
## Description
Projects which want to use Polygon Edge to bootstrap their blockchains can't modify the quorum logic because in go-ibft@0.0.0 part of the quorum logic is handled there instead of in the client. This is changed in version 0.1.0.

## Proposed solution
Upgrading the go-ibft version to 0.1.0 will allow for blockchain projects using Polygon Edge to apply changes to the quorum logic when needed (applying staking amount weight for example) without the need to fork and apply changes in the go-ibft package.

### PR DESCRIPTION
**Pull request by Kourin1996**
# Description

As described in https://github.com/0xPolygon/go-ibft/pull/55, hash calculation needs to update for IBFT2.0 consensus.
In particular, IBFT backend must generate hash for IBFT consensus from tuple of `(EthereumBlock, round)`.

This PR changes hash calculation add adds new field for round in IBFT Extra.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [x] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

File: consensus/ibft/signer/extra.go [hunk 1]
```diff
@@ -62,6 +84,12 @@ func (i *IstanbulExtra) MarshalRLPWith(ar *fastrlp.Arena) *fastrlp.Value {
 	// ParentCommittedSeal
 	if i.ParentCommittedSeals != nil {
 		vv.Set(i.ParentCommittedSeals.MarshalRLPWith(ar))
+	} else if i.RoundNumber != nil {
```
Comment (igorcrevar) [inline consensus/ibft/signer/extra.go]: Why is there  `else if i.RoundNumber != nil` and bellow again if with same condition

File: consensus/ibft/signer/extra.go [hunk 2]
```diff
@@ -37,6 +42,23 @@ type Seals interface {
 	UnmarshalRLPFrom(*fastrlp.Parser, *fastrlp.Value) error
 }
 
+func parseRoundNumber(v *fastrlp.Value) (*uint64, error) {
```
Comment (igorcrevar) [inline consensus/ibft/signer/extra.go]: Can we use  `num := binary.LittleEndian.Uint64(array)` or `num := binary.BigEndian.Uint64(array)` here?

File: consensus/ibft/consensus_backend.go [hunk 3]
```diff
@@ -40,12 +40,16 @@ func (i *backendIBFT) BuildProposal(blockNumber uint64) []byte {
 	return block.MarshalRLP()
 }
 
+// TODO: Yoshiki please do this change, we need to make sure that on validating (when syncing) we make sure that
+// the committed seals are verifying against ProposedBlock (structure found in go-ibft/messages/proto/messages.pb.go
+// the ProposedBlock is hashed as proto.Marshal(ProposedBlock) and then keccakk hashed.
```
Comment (vcastellm) [inline consensus/ibft/consensus_backend.go]:
```suggestion
// the ProposedBlock is hashed as proto.Marshal(ProposedBlock) and then keccak hashed.
```

File: consensus/ibft/consensus_backend.go [hunk 4]
```diff
@@ -3,18 +3,18 @@ package ibft
...
+	"github.com/0xPolygon/go-ibft/messages/proto"
 	"github.com/0xPolygon/polygon-edge/consensus"
 	"github.com/0xPolygon/polygon-edge/consensus/ibft/signer"
 	"github.com/0xPolygon/polygon-edge/helper/hex"
 	"github.com/0xPolygon/polygon-edge/state"
 	"github.com/0xPolygon/polygon-edge/types"
 )
 
-func (i *backendIBFT) BuildProposal(blockNumber uint64) []byte {
+func (i *backendIBFT) BuildEthereumBlock(blockNumber uint64) []byte {
```
Comment (vcastellm) [inline consensus/ibft/consensus_backend.go]: I remember that we called it `EthereumBlock` but what's the motivation for this name? why not call it simply `Block`?

Comment (Kourin1996) [reply consensus/ibft/consensus_backend.go]: Renamed to BuildProposal at f3cd3dc5c2a57f3820b5362e50b650689a512c43

File: consensus/ibft/consensus_backend.go (hunk 3 above)
Comment (Kourin1996) [reply consensus/ibft/consensus_backend.go]: This comment has been removed

File: consensus/ibft/signer/extra.go (hunk 2 above)
Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: Not it uses GetUint64, fastrlp provides originally

File: consensus/ibft/signer/extra.go (hunk 1 above)
Comment (Kourin1996) [reply consensus/ibft/signer/extra.go:78]: Fixed 4f5ec060938dfd3d015f7d3631f0ace119caa4a9

Comment (Kourin1996) [reply consensus/ibft/signer/extra.go:78]: Fixed 4f5ec060938dfd3d015f7d3631f0ace119caa4a9

Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: To put RoundNumber in correct position

File: consensus/ibft/verifier.go [hunk 5]
```diff
@@ -184,3 +182,43 @@ func (i *backendIBFT) extractProposer(header *types.Header) (types.Address, erro
 
 	return proposer, nil
 }
+
+func (i *backendIBFT) getProposalHashFromBlockBytes(ethereumBlock []byte, round *uint64) (types.Hash, error) {
```
Comment (b00ris) [inline consensus/ibft/verifier.go]: Attached document about compatibility of this change with checkpointing/slashing for 0.7.x. https://www.notion.so/polygontechnology/Signing-in-goibft-6a3ba4a50deb4efd85c1e2d71f401a6d

Comment (Kourin1996) [reply consensus/ibft/verifier.go]: As discussed yesterday, the hash for Committed Seals is calculated by keccak256(block hash + round bytes) from commit c0d1d00f0dbfd7da255fa6b7756013596660970b

**Review by trimixlover — APPROVED** [review]

**Comment by Stefan-Ethernal** [comment]
Does it make sense to address these errors before the review process?

```go
Error: consensus/ibft/messages.go:27:30: undefined: proto.ProposedBlock
Error: consensus/ibft/messages.go:93:22: undefined: proto.ProposedBlock
Error: consensus/ibft/verifier.go:185:63: undefined: proto.ProposedBlock
Error: consensus/ibft/ibft.go:199:3: cannot use i (variable of type *backendIBFT) as type core.Backend in argument to newIBFT:
```

**Comment by Kourin1996** [comment]
> Does it make sense to address these errors before the review process?

Need a release in go-ibft side because this PR includes a change based on a open PR in go-ibft
https://github.com/0xPolygon/go-ibft/pull/55

**Review by vcastellm — APPROVED** [review]

**Review by igorcrevar — APPROVED** [review]

**Review by b00ris — APPROVED** [review]

File: consensus/ibft/signer/extra.go (hunk 1 above)
Comment (igorcrevar) [reply consensus/ibft/signer/extra.go]: I understand, resolved

File: consensus/ibft/signer/extra.go [hunk 6]
```diff
@@ -62,6 +92,14 @@ func (i *IstanbulExtra) MarshalRLPWith(ar *fastrlp.Arena) *fastrlp.Value {
 	// ParentCommittedSeal
 	if i.ParentCommittedSeals != nil {
 		vv.Set(i.ParentCommittedSeals.MarshalRLPWith(ar))
+	} else if i.RoundNumber != nil {
+		vv.Set(ar.NewNull())
+	}
```
Comment (Stefan-Ethernal) [inline consensus/ibft/signer/extra.go]: Isn't it enough to remove this part (if condition below is anyways going to set round number if it is not nil)?

This way it seems like `ParentCommittedSeals` are in some relation with `RoundNumber`, but I don't see how they relate.

```suggestion
	}
```

File: consensus/ibft/signer/extra.go [hunk 7]
```diff
@@ -242,6 +306,14 @@ func packCommittedSealsIntoExtra(
 			// ParentCommittedSeal
 			if len(oldValues) >= 4 {
 				newArrayValue.Set(oldValues[3])
+			} else if roundNumber != nil {
+				newArrayValue.Set(ar.NewNull())
+			}
```
Comment (Stefan-Ethernal) [inline consensus/ibft/signer/extra.go]: Again not sure why do we need this else if?

File: consensus/ibft/signer/extra.go (hunk 6 above)
Comment (Kourin1996) [reply consensus/ibft/signer/extra.go:97]: Fixed 0fd2657058e238256b737ad5dcafc250f0f4c813

File: consensus/ibft/signer/extra.go [hunk 8]
```diff
@@ -37,6 +42,35 @@ type Seals interface {
 	UnmarshalRLPFrom(*fastrlp.Parser, *fastrlp.Value) error
 }
 
+// parseRoundNumber parses RLP-encoded bytes into round
+// FYI, Extra has 8 bytes space for round in order to distinguish between null and 0
```
Comment (Stefan-Ethernal) [inline consensus/ibft/signer/extra.go]: If I'm correct this comment is now redundant?

```suggestion
```

File: consensus/ibft/signer/extra.go [hunk 9]
```diff
@@ -20,6 +22,8 @@ var (
 	IstanbulExtraSeal = 65
 
 	zeroBytes = make([]byte, 32)
+
+	ErrRoundNumberOverflow = errors.New("round number is out of range for 64bit")
```
Comment (Stefan-Ethernal) [inline consensus/ibft/signer/extra.go]: Should we make this local (unexport it)?

File: consensus/ibft/signer/extra.go [hunk 10]
```diff
@@ -37,6 +42,35 @@ type Seals interface {
...
+		return nil, err
+	}
+
+	if len(roundBytes) == 0 {
+		return nil, nil
+	}
+
+	if len(roundBytes) > 8 {
+		return nil, ErrRoundNumberOverflow
+	}
```
Comment (Stefan-Ethernal) [inline consensus/ibft/signer/extra.go]: Nitpick, maybe just reverse order of these two if statements, so that negative incomes are grouped together. WDYT?

```suggestion
	if len(roundBytes) > 8 {
		return nil, ErrRoundNumberOverflow
	}

	if len(roundBytes) == 0 {
		return nil, nil
	}
```

**Review by Stefan-Ethernal — APPROVED** [review]
LGTM

File: consensus/ibft/signer/extra.go (hunk 8 above)
Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: No

File: consensus/ibft/signer/extra.go (hunk 10 above)
Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: Fixed c2fee48aa934d3210d2de82b9de7d339769ea35e

File: consensus/ibft/signer/extra.go (hunk 9 above)
Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: Fixed c2fee48aa934d3210d2de82b9de7d339769ea35e

File: consensus/ibft/signer/extra.go (hunk 8 above)
Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: @Stefan-Ethernal

Comment (Stefan-Ethernal) [reply consensus/ibft/signer/extra.go]: I was referring that round is not nil and in that case it is 8 bytes length or if it is `nil` it's length is 0. With having that on mind I'm not sure if comment was trying to outline the same thing, because it is a bit confusing to me.

Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: Round in IBFT Extra can be nil in order to support backward compatibility

Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: In case of that Extra has Round, bytes data would have non-zero size always.

Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: Fixed comment 63f4cc01137fd2e71b99d270de89bd232a6b05cd. Is that fine with you @Stefan-Ethernal ?

Comment (Stefan-Ethernal) [reply consensus/ibft/signer/extra.go]: > Round in IBFT Extra can be nil in order to support backward compatibility

Yes aware of it and it is completely fine 👍 . However I was referring that comment is somewhat imprecise, since we would have either 8 bytes or 0 (in case round is `nil`). 

Don't mind keeping it, but just wanted to make this clear.

Comment (Stefan-Ethernal) [reply consensus/ibft/signer/extra.go]: > Fixed comment [63f4cc0](https://github.com/0xPolygon/polygon-edge/commit/63f4cc01137fd2e71b99d270de89bd232a6b05cd). Is that fine with you @Stefan-Ethernal ?

Yep this is better. Tnx 🙏

Comment (Kourin1996) [reply consensus/ibft/signer/extra.go]: @Stefan-Ethernal ping
