### PR TITLE
Exponential round timeouts cause very long delays in recovering lost consesus

### LINKED ISSUE #245: Discussion: Questions on exponentially-increasing IBFT randomTimeout()
### Description

While investigating a chain halt that occurred on our testnet earlier this week, restarting all validators fixed our chain as more messages would be sent in a shorter timespan, allowing nodes to transition out of each round faster (since the required messageQueue length thresholds would be met sooner). This then brought up some internal discussion which led to some questions we had about `randomTimeout()`:

1. Why use exponentially-increasing timeouts in the first place? We realize the original geth fork you've based the SDK on makes use of this calculate as well but we couldn't find out any indication why they didn't use a fixed or linearly-increasing timeout instead (see https://github.com/getamis/go-ethereum/blob/c7547381b2ea8999e423970d619835c662176790/consensus/istanbul/core/core.go#L316-L329). Was this to prevent multiple nodes from changing state at the same time?

2. Could introducing a new flag to cap the timeout to a specified maximum value alleviate the problem? At least if the maximum randomTimeout() was 10 minutes for example, a chain would be able to recover from a halt in the span of hours instead of what could be days (or more). Shouldn't the goal be to recover the chain as quickly as possible if a chain halt were to occur?

Left this open as a discussion - thanks in advance and as always we appreciate the hard work.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK
* branch that causes this issue `develop`

### LINKED ISSUE #248: Consensus failure cycling `AcceptState` -> `ValidateState` -> `RoundChangeState` -> `AcceptState`
### Description

Our testnet at the time was an 8 node cluster. 7 nodes were online. We experienced a consensus failure and nodes could not agree on a shared state and hence produce blocks. Max faulty nodes is thus 4. 

We're unsure why this happens. We're digging more into it, but one thing we can't understand is why are all the round messages reset everytime the node enters the `AcceptState`?

https://github.com/0xPolygon/polygon-sdk/blob/6c91309a4f633c5e359b7b76ae383aca43a51e5c/consensus/ibft/ibft.go#L529

### Your environment

* OS and version AWS Linux 2
* version of the Polygon SDK 7f2e61d19b63bde38f52925dee4eefc47e03ddf5
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Consensus failure should not occur.

### Actual behaviour

Consensus failure occurred and nodes were unable to write blocks. 

### Logs

I have only included the logs from Validators 1-4 here because 5,6,7 were not as verbose, but had identical behaviour. We added custom logging and will continue to do so. The `roundchange state received msg: roundLength=` is counting the number of round change messages received at the particular round. 

Validator 1:

```
2021-11-25T20:02:49.095Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:02:49.095Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214088 round=0
2021-11-25T20:02:49.095Z [DEBUG] polygon.consensus.ibft: local round change: round=1
2021-11-25T20:02:49.096Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:02:49.096Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:02:49.096Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:02:49.097Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:02:49.097Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:02:49.097Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:02:49.097Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:02:49.097Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:02:49.097Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:02:49.097Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214088 round=1
2021-11-25T20:02:49.097Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214088
2021-11-25T20:02:49.097Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:02:49.098Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x96Dba988EE0a4b0921CeF51956e1dD03C9A0DbC6 block=214088
2021-11-25T20:02:49.111Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:02:49.111Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214088 round=1
2021-11-25T20:02:49.125Z [DEBUG] polygon.consensus.ibft: state change: new=CommitState
2021-11-25T20:02:49.126Z [INFO]  polygon.blockchain: write block: num=214088 parent=0x0df9ac1a4a87085abb9131013ea3cdfd09fb1fec2d1eb670eadb92747403a0fd
2021-11-25T20:02:49.129Z [INFO]  polygon.blockchain: new block: number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 txns=0 generation_time_in_sec=10
2021-11-25T20:02:49.129Z [INFO]  polygon.blockchain: new head: hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 number=214088
2021-11-25T20:02:49.129Z [INFO]  polygon.consensus.ibft: block committed: sequence=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 validators=8 rounds=2 committed=5
2021-11-25T20:02:49.130Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmFpTiQcctV2KNpdKm9FehHKFLTUC13oaBGVzvZta7iFMc number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.130Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmFpTiQcctV2KNpdKm9FehHKFLTUC13oaBGVzvZta7iFMc latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.135Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmSYHwzk9AzJXBtiWuAWPLTCQd5qs34FQRCNm8bU5oB7tu number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.135Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmSYHwzk9AzJXBtiWuAWPLTCQd5qs34FQRCNm8bU5oB7tu latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmERLox5fG95J9SRrrv8YQ1oEMF5XxU5L5Ew1VyXa3qrHF number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmERLox5fG95J9SRrrv8YQ1oEMF5XxU5L5Ew1VyXa3qrHF latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.138Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmVNa5jRxiLkDtVRirUTHLZ2CYCbyR1VeFH5eYVdyY4wUF number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.138Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmVNa5jRxiLkDtVRirUTHLZ2CYCbyR1VeFH5eYVdyY4wUF latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.139Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAkuuRvPb6tBUdbMV5gALqnPzgr7EBPFv7hqDB6t4Kiqzvi number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.139Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAkuuRvPb6tBUdbMV5gALqnPzgr7EBPFv7hqDB6t4Kiqzvi latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.139Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmTvfiVHL6v7V9JmLdkM4jHHTWC34mMHqYDdw4HhLoFTYD number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.139Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmTvfiVHL6v7V9JmLdkM4jHHTWC34mMHqYDdw4HhLoFTYD latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:50.463Z [DEBUG] polygon.txpool: add txn: ctx=addTxn hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:02:50.465Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:02:50.466Z [DEBUG] polygon.txpool: add txn: ctx=addTxn hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:02:50.467Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:03:19.360Z [ERROR] polygon.consensus.syncer: failed to notify: err="rpc error: code = Unavailable desc = error reading from server: stream reset"
2021-11-25T20:03:19.361Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:03:19.361Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=0
2021-11-25T20:03:19.361Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:03:19.361Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:03:19.361Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x25BAfc38a950837E0CCb49D10E0E98cce6CC8a44 block=214089
2021-11-25T20:03:19.362Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:03:19.363Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=0
2021-11-25T20:03:19.365Z [INFO]  polygon.network: Peer disconnected: id=16Uiu2HAmQBH6UjrRPrRqKxpxHVKtuh897KMjwhpdNNcZtyVV9EdC
2021-11-25T20:03:19.366Z [ERROR] polygon.network: failed to dial bootnode: err="rpc error: code = Unavailable desc = connection closed before server preface received"
2021-11-25T20:03:24.369Z [DEBUG] polygon.network: dial: local=16Uiu2HAmP2bpgr3sLUUzt61bEzAL7ptdNXnvsfnwcxyrfCMFjxDf addr="{16Uiu2HAmQBH6UjrRPrRqKxpxHVKtuh897KMjwhpdNNcZtyVV9EdC: [/ip4/127.0.0.1/tcp/43659 /ip4/127.0.0.1/tcp/45021 /ip4/127.0.0.1/tcp/39019]}"
2021-11-25T20:03:29.365Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:03:29.365Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=0
2021-11-25T20:03:29.365Z [DEBUG] polygon.consensus.ibft: local round change: round=1
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:03:29.367Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=1
2021-11-25T20:03:29.367Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:03:29.368Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:03:29.368Z [INFO]  polygon.consensus.ibft.acceptState: we are the proposer: block=214089
2021-11-25T20:03:29.369Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:03:29.370Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=1
2021-11-25T20:03:41.388Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:03:41.389Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=1
2021-11-25T20:03:41.389Z [DEBUG] polygon.consensus.ibft: local round change: round=2
2021-11-25T20:03:41.389Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:03:41.389Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=2
2021-11-25T20:03:41.390Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:03:41.390Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:03:41.391Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x38FCBEbc15A6D9091082C369d0734B2FBC7d455C block=214089
2021-11-25T20:03:41.401Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:03:41.401Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=2
2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=2
2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: local round change: round=3
2021-11-25T20:03:55.406Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:03:55.406Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
2021-11-25T20:03:55.407Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:03:55.407Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
2021-11-25T20:03:55.407Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:03:55.407Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
2021-11-25T20:03:55.407Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:03:55.407Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
2021-11-25T20:03:55.407Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:03:55.407Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=3
2021-11-25T20:03:55.407Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:03:55.407Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:03:55.408Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0xC3E0c7fC6543cdf478F15a842FE0c1a2c3b516F6 block=214089
2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:04:13.411Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=3
2021-11-25T20:04:13.411Z [DEBUG] polygon.consensus.ibft: local round change: round=4
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:04:13.412Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=4
2021-11-25T20:04:13.413Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:04:13.413Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:04:13.413Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x97b73C76aF21704Bd3EE2c1DC28F6AA015A203A6 block=214089
2021-11-25T20:04:39.413Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:04:39.414Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=4
2021-11-25T20:04:39.414Z [DEBUG] polygon.consensus.ibft: local round change: round=5
2021-11-25T20:04:39.416Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:04:39.416Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
2021-11-25T20:04:39.416Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:04:39.416Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
2021-11-25T20:04:39.416Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:04:39.417Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
2021-11-25T20:04:39.417Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:04:39.417Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
2021-11-25T20:04:39.417Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:04:39.417Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=5
2021-11-25T20:04:39.417Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:04:39.417Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:04:39.418Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x80359340dE9Ba7F6eEA873CC9600E8f09F9b3E35 block=214089
2021-11-25T20:04:39.426Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:04:39.426Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=5
2021-11-25T20:05:21.431Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:05:21.432Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=5
2021-11-25T20:05:21.432Z [DEBUG] polygon.consensus.ibft: local round change: round=6
2021-11-25T20:05:21.435Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:05:21.435Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
2021-11-25T20:05:21.435Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:05:21.435Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
2021-11-25T20:05:21.439Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:05:21.439Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
2021-11-25T20:05:21.439Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:05:21.440Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
2021-11-25T20:05:21.440Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:05:21.440Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=6
2021-11-25T20:05:21.440Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:05:21.440Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:05:21.440Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x48aC0082F6c1e29fC25144B8d7f4607e36c13b1f block=214089
2021-11-25T20:06:35.441Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:06:35.441Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=6
2021-11-25T20:06:35.441Z [DEBUG] polygon.consensus.ibft: local round change: round=7
2021-11-25T20:06:35.442Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:06:35.442Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
2021-11-25T20:06:35.442Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:06:35.442Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
2021-11-25T20:06:35.443Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:06:35.443Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
2021-11-25T20:06:35.444Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=7
2021-11-25T20:06:35.445Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:06:35.445Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:06:35.445Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x96Dba988EE0a4b0921CeF51956e1dD03C9A0DbC6 block=214089
2021-11-25T20:06:35.451Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:06:35.452Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=7
2021-11-25T20:07:50.491Z [DEBUG] polygon.txpool: add txn: ctx=addTxn hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:07:50.494Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:07:50.495Z [DEBUG] polygon.txpool: add txn: ctx=addTxn hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:07:50.497Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:08:53.459Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:08:53.459Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=7
2021-11-25T20:08:53.459Z [DEBUG] polygon.consensus.ibft: local round change: round=8
2021-11-25T20:08:53.462Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:08:53.462Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
2021-11-25T20:08:53.462Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:08:53.462Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
2021-11-25T20:08:53.466Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:08:53.467Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
2021-11-25T20:08:53.467Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:08:53.467Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
2021-11-25T20:08:53.467Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:08:53.467Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=8
2021-11-25T20:08:53.467Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:08:53.467Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:08:53.468Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x25BAfc38a950837E0CCb49D10E0E98cce6CC8a44 block=214089
2021-11-25T20:08:53.474Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:08:53.478Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=8
2021-11-25T20:08:53.478Z [DEBUG] polygon.consensus.ibft: round change handle err: err="block locked is incorrect"
2021-11-25T20:08:53.478Z [DEBUG] polygon.consensus.ibft: local round change: round=9
2021-11-25T20:08:53.479Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:08:53.479Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
2021-11-25T20:08:53.485Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:08:53.485Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
2021-11-25T20:08:53.485Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:08:53.486Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
2021-11-25T20:08:53.486Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:08:53.486Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
2021-11-25T20:08:53.486Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:08:53.486Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=9
2021-11-25T20:08:53.486Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:08:53.486Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:08:53.486Z [INFO]  polygon.consensus.ibft.acceptState: we are the proposer: block=214089
2021-11-25T20:08:53.488Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:08:53.488Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=9
2021-11-25T20:12:50.522Z [DEBUG] polygon.txpool: add txn: ctx=addTxn hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:12:50.525Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:12:50.526Z [DEBUG] polygon.txpool: add txn: ctx=addTxn hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:12:50.527Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
```

Validator 2:

```
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.109Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.110Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214088 round=0
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.110Z [DEBUG] polygon.consensus.ibft: local round change: round=1
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.111Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.111Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.111Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214088 round=1
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214088
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.112Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.113Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x96Dba988EE0a4b0921CeF51956e1dD03C9A0DbC6 block=214088
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.115Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.115Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214088 round=1
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.127Z [DEBUG] polygon.consensus.ibft: state change: new=CommitState
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.127Z [INFO]  polygon.blockchain: write block: num=214088 parent=0x0df9ac1a4a87085abb9131013ea3cdfd09fb1fec2d1eb670eadb92747403a0fd
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.131Z [INFO]  polygon.blockchain: new block: number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 txns=0 generation_time_in_sec=10
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.131Z [INFO]  polygon.blockchain: new head: hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 number=214088
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.131Z [INFO]  polygon.consensus.ibft: block committed: sequence=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 validators=8 rounds=2 committed=5
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.133Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmSYHwzk9AzJXBtiWuAWPLTCQd5qs34FQRCNm8bU5oB7tu number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.133Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmSYHwzk9AzJXBtiWuAWPLTCQd5qs34FQRCNm8bU5oB7tu latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a946>
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.133Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmP2bpgr3sLUUzt61bEzAL7ptdNXnvsfnwcxyrfCMFjxDf number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.133Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmP2bpgr3sLUUzt61bEzAL7ptdNXnvsfnwcxyrfCMFjxDf latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a946>
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.134Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmERLox5fG95J9SRrrv8YQ1oEMF5XxU5L5Ew1VyXa3qrHF number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.134Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmERLox5fG95J9SRrrv8YQ1oEMF5XxU5L5Ew1VyXa3qrHF latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a946>
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.134Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAkuuRvPb6tBUdbMV5gALqnPzgr7EBPFv7hqDB6t4Kiqzvi number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.134Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAkuuRvPb6tBUdbMV5gALqnPzgr7EBPFv7hqDB6t4Kiqzvi latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a946>
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.135Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmVNa5jRxiLkDtVRirUTHLZ2CYCbyR1VeFH5eYVdyY4wUF number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.135Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmVNa5jRxiLkDtVRirUTHLZ2CYCbyR1VeFH5eYVdyY4wUF latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a946>
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmFpTiQcctV2KNpdKm9FehHKFLTUC13oaBGVzvZta7iFMc number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmFpTiQcctV2KNpdKm9FehHKFLTUC13oaBGVzvZta7iFMc latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a946>
Nov 25 20:02:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:50.466Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:02:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:02:50.468Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.139Z [INFO]  polygon.network: Peer disconnected: id=16Uiu2HAmQBH6UjrRPrRqKxpxHVKtuh897KMjwhpdNNcZtyVV9EdC
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.139Z [ERROR] polygon.consensus.syncer: failed to notify: err="rpc error: code = Unavailable desc = error reading from server: stream reset"
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.139Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.139Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=0
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.139Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.139Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.140Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x25BAfc38a950837E0CCb49D10E0E98cce6CC8a44 block=214089
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.142Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:03:19 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:19.142Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=0
Nov 25 20:03:20 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:20.491Z [DEBUG] polygon.network: dial: local=16Uiu2HAmTvfiVHL6v7V9JmLdkM4jHHTWC34mMHqYDdw4HhLoFTYD addr="{16Uiu2HAmQBH6UjrRPrRqKxpxHVKtuh897KMjwhpdNNcZtyVV9EdC: [/ip4/127.0.0.1/tcp/45021 /ip4/127.0.0.1/tcp/390>
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.370Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.370Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=0
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.370Z [DEBUG] polygon.consensus.ibft: local round change: round=1
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=1
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.371Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.372Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x033a47156DD82CDdb2fD426B80088a9ae6101ac5 block=214089
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.381Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:03:29 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:29.381Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=1
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.388Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.388Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=1
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.388Z [DEBUG] polygon.consensus.ibft: local round change: round=2
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=2
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.390Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.391Z [INFO]  polygon.consensus.ibft.acceptState: we are the proposer: block=214089
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.393Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:03:41 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:41.393Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=2
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.404Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.404Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=2
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.404Z [DEBUG] polygon.consensus.ibft: local round change: round=3
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=3
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.405Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:03:55 ip-172-31-35-244 main[337263]: 2021-11-25T20:03:55.406Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0xC3E0c7fC6543cdf478F15a842FE0c1a2c3b516F6 block=214089
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.406Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.407Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=3
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.407Z [DEBUG] polygon.consensus.ibft: local round change: round=4
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=4
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.408Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.409Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:04:13 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:13.409Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x97b73C76aF21704Bd3EE2c1DC28F6AA015A203A6 block=214089
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.410Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.410Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=4
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.410Z [DEBUG] polygon.consensus.ibft: local round change: round=5
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=5
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.411Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x80359340dE9Ba7F6eEA873CC9600E8f09F9b3E35 block=214089
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.418Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:04:39 ip-172-31-35-244 main[337263]: 2021-11-25T20:04:39.418Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=5
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.430Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.430Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=5
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.430Z [DEBUG] polygon.consensus.ibft: local round change: round=6
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.430Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.430Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.434Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.434Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.434Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.434Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=6
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.437Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.437Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:05:21 ip-172-31-35-244 main[337263]: 2021-11-25T20:05:21.437Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x48aC0082F6c1e29fC25144B8d7f4607e36c13b1f block=214089
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.438Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.438Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=6
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.438Z [DEBUG] polygon.consensus.ibft: local round change: round=7
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.441Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.441Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.441Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.441Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=7
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.445Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.445Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.446Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x96Dba988EE0a4b0921CeF51956e1dD03C9A0DbC6 block=214089
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.451Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:06:35 ip-172-31-35-244 main[337263]: 2021-11-25T20:06:35.451Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=7
Nov 25 20:07:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:07:50.496Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:07:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:07:50.498Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.458Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.458Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=7
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.458Z [DEBUG] polygon.consensus.ibft: local round change: round=8
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.459Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.459Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.461Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.461Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=8
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.465Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.465Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.466Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x25BAfc38a950837E0CCb49D10E0E98cce6CC8a44 block=214089
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.474Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.474Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=8
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.475Z [DEBUG] polygon.consensus.ibft: round change handle err: err="block locked is incorrect"
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.475Z [DEBUG] polygon.consensus.ibft: local round change: round=9
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.475Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.476Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.480Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.480Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.480Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.480Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.483Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.483Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.483Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.483Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=9
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.483Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.483Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.483Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x033a47156DD82CDdb2fD426B80088a9ae6101ac5 block=214089
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.493Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:08:53 ip-172-31-35-244 main[337263]: 2021-11-25T20:08:53.493Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=9
Nov 25 20:12:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:12:50.526Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:12:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:12:50.529Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:17:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:17:50.558Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:17:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:17:50.561Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:18:06 ip-172-31-35-244 main[337263]: 2021-11-25T20:18:06.312Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0x86327376ece3d37dc884f94c6b4a3205ec0a569b850ffe09ab9213c6014e8c03 from=0x2079A994E9BBc88496Df03A59A0CFA2C9E2af473
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.494Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.494Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=9
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.494Z [DEBUG] polygon.consensus.ibft: local round change: round=10
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.498Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.498Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=10
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.508Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.508Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=10
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.508Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.508Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=10
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.509Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.509Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=10
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.509Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.509Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=10
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.512Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.512Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.514Z [INFO]  polygon.consensus.ibft.acceptState: we are the proposer: block=214089
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.516Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:22:01 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:01.516Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=10
Nov 25 20:22:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:50.591Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:22:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:22:50.593Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:27:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:27:50.621Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:27:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:27:50.624Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:32:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:32:50.653Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:32:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:32:50.659Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:37:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:37:50.687Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:37:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:37:50.690Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.619Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.620Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=10
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.620Z [DEBUG] polygon.consensus.ibft: local round change: round=11
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.622Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=11
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=11
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=11
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=11
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=11
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.623Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.624Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.624Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0xC3E0c7fC6543cdf478F15a842FE0c1a2c3b516F6 block=214089
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.624Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.624Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=11
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.624Z [DEBUG] polygon.consensus.ibft: round change handle err: err="block locked is incorrect"
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.624Z [DEBUG] polygon.consensus.ibft: local round change: round=12
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.625Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.625Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=12
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.625Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.625Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=12
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.625Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.626Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=12
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.626Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.626Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=12
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.626Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.626Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=12
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.626Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.626Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:39:15 ip-172-31-35-244 main[337263]: 2021-11-25T20:39:15.626Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x97b73C76aF21704Bd3EE2c1DC28F6AA015A203A6 block=214089
Nov 25 20:42:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:42:50.720Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:42:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:42:50.723Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:47:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:47:50.750Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:47:50 ip-172-31-35-244 main[337263]: 2021-11-25T20:47:50.755Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.628Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.629Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=12
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.629Z [DEBUG] polygon.consensus.ibft: round change handle err: err="block locked is incorrect"
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.629Z [DEBUG] polygon.consensus.ibft: local round change: round=13
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.630Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.630Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=13
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.636Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.636Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=13
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.636Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.636Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=13
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.647Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.647Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=13
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.647Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.647Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=13
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.647Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.648Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.648Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x80359340dE9Ba7F6eEA873CC9600E8f09F9b3E35 block=214089
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.652Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 21:13:33 ip-172-31-35-244 main[337263]: 2021-11-25T21:13:33.652Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=13
```

```Validator 3
-- Logs begin at Tue 2021-11-23 14:04:21 UTC, end at Thu 2021-11-25 21:42:52 UTC. --
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.044Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.044Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214088 round=0
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.044Z [DEBUG] polygon.consensus.ibft: local round change: round=1
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.095Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.095Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214088 round=1
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.095Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214088
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.095Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.096Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x96Dba988EE0a4b0921CeF51956e1dD03C9A0DbC6 block=214088
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.110Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.110Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214088 round=1
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.126Z [DEBUG] polygon.consensus.ibft: state change: new=CommitState
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.126Z [INFO]  polygon.blockchain: write block: num=214088 parent=0x0df9ac1a4a87085abb9131013ea3cdfd09fb1fec2d1eb670eadb92747403a0fd
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.129Z [INFO]  polygon.blockchain: new block: number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 txns=0 generation_time_in_sec=10
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.129Z [INFO]  polygon.blockchain: new head: hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 number=214088
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.129Z [INFO]  polygon.consensus.ibft: block committed: sequence=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 validators=8 rounds=2 committed=5
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.133Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmERLox5fG95J9SRrrv8YQ1oEMF5XxU5L5Ew1VyXa3qrHF number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.133Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmERLox5fG95J9SRrrv8YQ1oEMF5XxU5L5Ew1VyXa3qrHF latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a9468>
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.136Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmTvfiVHL6v7V9JmLdkM4jHHTWC34mMHqYDdw4HhLoFTYD number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.136Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmTvfiVHL6v7V9JmLdkM4jHHTWC34mMHqYDdw4HhLoFTYD latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a9468>
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAkuuRvPb6tBUdbMV5gALqnPzgr7EBPFv7hqDB6t4Kiqzvi number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAkuuRvPb6tBUdbMV5gALqnPzgr7EBPFv7hqDB6t4Kiqzvi latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a9468>
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.140Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmSYHwzk9AzJXBtiWuAWPLTCQd5qs34FQRCNm8bU5oB7tu number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.140Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmSYHwzk9AzJXBtiWuAWPLTCQd5qs34FQRCNm8bU5oB7tu latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a9468>
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.142Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.143Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=0
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.143Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.143Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.143Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x25BAfc38a950837E0CCb49D10E0E98cce6CC8a44 block=214089
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.144Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmP2bpgr3sLUUzt61bEzAL7ptdNXnvsfnwcxyrfCMFjxDf number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.144Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmP2bpgr3sLUUzt61bEzAL7ptdNXnvsfnwcxyrfCMFjxDf latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a9468>
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.146Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmVNa5jRxiLkDtVRirUTHLZ2CYCbyR1VeFH5eYVdyY4wUF number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
Nov 25 20:02:49 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:49.146Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmVNa5jRxiLkDtVRirUTHLZ2CYCbyR1VeFH5eYVdyY4wUF latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a9468>
Nov 25 20:02:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:50.467Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:02:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:50.470Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:02:51 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:51.008Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:02:51 ip-172-31-32-83 main[846896]: 2021-11-25T20:02:51.008Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=0
Nov 25 20:03:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:01.012Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:03:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:01.012Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=0
Nov 25 20:03:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:01.012Z [DEBUG] polygon.consensus.ibft: local round change: round=1
Nov 25 20:03:13 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:13.022Z [DEBUG] polygon.consensus.ibft: round change timeout
Nov 25 20:03:13 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:13.022Z [DEBUG] polygon.consensus.ibft: local round change: round=2
Nov 25 20:03:27 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:27.029Z [DEBUG] polygon.consensus.ibft: round change timeout
Nov 25 20:03:27 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:27.030Z [DEBUG] polygon.consensus.ibft: local round change: round=3
Nov 25 20:03:45 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:45.037Z [DEBUG] polygon.consensus.ibft: round change timeout
Nov 25 20:03:45 ip-172-31-32-83 main[846896]: 2021-11-25T20:03:45.037Z [DEBUG] polygon.consensus.ibft: local round change: round=4
Nov 25 20:04:11 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:11.044Z [DEBUG] polygon.consensus.ibft: round change timeout
Nov 25 20:04:11 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:11.044Z [DEBUG] polygon.consensus.ibft: local round change: round=5
Nov 25 20:04:39 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:39.415Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:04:39 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:39.423Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=5
Nov 25 20:04:39 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:39.424Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:04:39 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:39.424Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:04:39 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:39.424Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x80359340dE9Ba7F6eEA873CC9600E8f09F9b3E35 block=214089
Nov 25 20:04:39 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:39.426Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:04:39 ip-172-31-32-83 main[846896]: 2021-11-25T20:04:39.426Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=5
Nov 25 20:05:21 ip-172-31-32-83 main[846896]: 2021-11-25T20:05:21.442Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:05:21 ip-172-31-32-83 main[846896]: 2021-11-25T20:05:21.442Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=5
Nov 25 20:05:21 ip-172-31-32-83 main[846896]: 2021-11-25T20:05:21.442Z [DEBUG] polygon.consensus.ibft: local round change: round=6
Nov 25 20:05:21 ip-172-31-32-83 main[846896]: 2021-11-25T20:05:21.444Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:05:21 ip-172-31-32-83 main[846896]: 2021-11-25T20:05:21.444Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=6
Nov 25 20:05:21 ip-172-31-32-83 main[846896]: 2021-11-25T20:05:21.444Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:05:21 ip-172-31-32-83 main[846896]: 2021-11-25T20:05:21.444Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:05:21 ip-172-31-32-83 main[846896]: 2021-11-25T20:05:21.445Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x48aC0082F6c1e29fC25144B8d7f4607e36c13b1f block=214089
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.446Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=6
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.446Z [DEBUG] polygon.consensus.ibft: local round change: round=7
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.448Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.448Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=7
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.448Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.448Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.448Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x96Dba988EE0a4b0921CeF51956e1dD03C9A0DbC6 block=214089
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.455Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:06:35 ip-172-31-32-83 main[846896]: 2021-11-25T20:06:35.455Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=7
Nov 25 20:07:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:07:50.497Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:07:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:07:50.499Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.461Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.462Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=7
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.462Z [DEBUG] polygon.consensus.ibft: local round change: round=8
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.468Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.469Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=8
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.469Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.469Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.469Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x25BAfc38a950837E0CCb49D10E0E98cce6CC8a44 block=214089
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.477Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:08:53 ip-172-31-32-83 main[846896]: 2021-11-25T20:08:53.477Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=8
Nov 25 20:12:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:12:50.527Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:12:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:12:50.530Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.483Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.483Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=8
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.483Z [DEBUG] polygon.consensus.ibft: local round change: round=9
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.484Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.484Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=9
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.484Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.484Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.484Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x033a47156DD82CDdb2fD426B80088a9ae6101ac5 block=214089
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.486Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:13:19 ip-172-31-32-83 main[846896]: 2021-11-25T20:13:19.486Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=9
Nov 25 20:17:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:17:50.559Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:17:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:17:50.562Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:18:06 ip-172-31-32-83 main[846896]: 2021-11-25T20:18:06.312Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0x86327376ece3d37dc884f94c6b4a3205ec0a569b850ffe09ab9213c6014e8c03 from=0x2079A994E9BBc88496Df03A59A0CFA2C9E2af473
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.498Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.498Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=9
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.498Z [DEBUG] polygon.consensus.ibft: local round change: round=10
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.541Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.541Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=10
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.541Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.541Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.542Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x38FCBEbc15A6D9091082C369d0734B2FBC7d455C block=214089
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.545Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:22:01 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:01.545Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=10
Nov 25 20:22:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:50.591Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:22:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:22:50.594Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:27:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:27:50.622Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:27:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:27:50.625Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:32:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:32:50.654Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:32:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:32:50.660Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:37:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:37:50.688Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:37:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:37:50.692Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.601Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.601Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=10
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.602Z [DEBUG] polygon.consensus.ibft: local round change: round=11
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.602Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.602Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=11
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.602Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.603Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.603Z [INFO]  polygon.consensus.ibft.acceptState: we are the proposer: block=214089
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.603Z [ERROR] polygon: failed to apply tx: err="incorrect nonce, recoverable [true]"
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.603Z [INFO]  polygon.consensus.ibft: picked out txns from pool: num=0 remaining=3
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.604Z [INFO]  polygon.consensus.ibft: build block: number=214089 txns=0
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.606Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 20:39:15 ip-172-31-32-83 main[846896]: 2021-11-25T20:39:15.606Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=11
Nov 25 20:42:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:42:50.723Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:42:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:42:50.729Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:47:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:47:50.752Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 20:47:50 ip-172-31-32-83 main[846896]: 2021-11-25T20:47:50.755Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.617Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.617Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=11
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.617Z [DEBUG] polygon.consensus.ibft: local round change: round=12
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.618Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.618Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=12
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.618Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.618Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.619Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x97b73C76aF21704Bd3EE2c1DC28F6AA015A203A6 block=214089
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.635Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
Nov 25 21:13:33 ip-172-31-32-83 main[846896]: 2021-11-25T21:13:33.635Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=12
Nov 25 21:30:16 ip-172-31-32-83 main[846896]: 2021-11-25T21:30:16.153Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0x98eb16a0bd5b36ebf93bd0093750e21f3d6fc302d0803e7c24037b66ac1a4464 from=0x72c5520b7dd60A242850cBc93a5EB244264a801e
Nov 25 21:30:20 ip-172-31-32-83 main[846896]: 2021-11-25T21:30:20.593Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0x4e8cfbb35bcdac72985d9f23e4712eff394b1175bd3458d47bcbce67a963c63d from=0x72c5520b7dd60A242850cBc93a5EB244264a801e
```

Validator 4

```
2021-11-25T20:02:49.045Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:02:49.046Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214088 round=0
2021-11-25T20:02:49.046Z [DEBUG] polygon.consensus.ibft: local round change: round=1
2021-11-25T20:02:49.047Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:02:49.047Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:02:49.050Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:02:49.051Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:02:49.051Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:02:49.051Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:02:49.095Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:02:49.095Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:02:49.096Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:02:49.096Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214088 round=1
2021-11-25T20:02:49.096Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214088
2021-11-25T20:02:49.096Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:02:49.096Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x96Dba988EE0a4b0921CeF51956e1dD03C9A0DbC6 block=214088
2021-11-25T20:02:49.111Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:02:49.111Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214088 round=1
2021-11-25T20:02:49.124Z [DEBUG] polygon.consensus.ibft: state change: new=CommitState
2021-11-25T20:02:49.125Z [INFO]  polygon.blockchain: write block: num=214088 parent=0x0df9ac1a4a87085abb9131013ea3cdfd09fb1fec2d1eb670eadb92747403a0fd
2021-11-25T20:02:49.128Z [INFO]  polygon.blockchain: new block: number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 txns=0 generation_time_in_sec=10
2021-11-25T20:02:49.128Z [INFO]  polygon.blockchain: new head: hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 number=214088
2021-11-25T20:02:49.128Z [INFO]  polygon.consensus.ibft: block committed: sequence=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 validators=8 rounds=2 committed=5
2021-11-25T20:02:49.131Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmFpTiQcctV2KNpdKm9FehHKFLTUC13oaBGVzvZta7iFMc number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.131Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmFpTiQcctV2KNpdKm9FehHKFLTUC13oaBGVzvZta7iFMc latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.136Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAkuuRvPb6tBUdbMV5gALqnPzgr7EBPFv7hqDB6t4Kiqzvi number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.136Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAkuuRvPb6tBUdbMV5gALqnPzgr7EBPFv7hqDB6t4Kiqzvi latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmTvfiVHL6v7V9JmLdkM4jHHTWC34mMHqYDdw4HhLoFTYD number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmTvfiVHL6v7V9JmLdkM4jHHTWC34mMHqYDdw4HhLoFTYD latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmP2bpgr3sLUUzt61bEzAL7ptdNXnvsfnwcxyrfCMFjxDf number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.137Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmP2bpgr3sLUUzt61bEzAL7ptdNXnvsfnwcxyrfCMFjxDf latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.141Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmSYHwzk9AzJXBtiWuAWPLTCQd5qs34FQRCNm8bU5oB7tu number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.141Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmSYHwzk9AzJXBtiWuAWPLTCQd5qs34FQRCNm8bU5oB7tu latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:49.142Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:02:49.142Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=0
2021-11-25T20:02:49.142Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:02:49.142Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:02:49.142Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x25BAfc38a950837E0CCb49D10E0E98cce6CC8a44 block=214089
2021-11-25T20:02:49.144Z [DEBUG] polygon.consensus.syncer: enqueue block: peer=16Uiu2HAmVNa5jRxiLkDtVRirUTHLZ2CYCbyR1VeFH5eYVdyY4wUF number=214088 hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539
2021-11-25T20:02:49.144Z [DEBUG] polygon.consensus.syncer: update peer status: peer=16Uiu2HAmVNa5jRxiLkDtVRirUTHLZ2CYCbyR1VeFH5eYVdyY4wUF latest block number=214088 latest block hash=0x045d06884917f5875ee01a7e213f3c9dbc6c3a94685c860cc06e3e30989e5539 difficulty=22916942917
2021-11-25T20:02:50.467Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:02:50.470Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:02:51.007Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:02:51.007Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=0
2021-11-25T20:03:01.011Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:03:01.018Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=0
2021-11-25T20:03:01.018Z [DEBUG] polygon.consensus.ibft: local round change: round=1
2021-11-25T20:03:01.019Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:03:01.020Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:03:01.023Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:03:01.023Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:03:01.023Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:03:01.023Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=1
2021-11-25T20:03:13.024Z [DEBUG] polygon.consensus.ibft: round change timeout
2021-11-25T20:03:13.024Z [DEBUG] polygon.consensus.ibft: local round change: round=2
2021-11-25T20:03:13.025Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:03:13.025Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
2021-11-25T20:03:13.032Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:03:13.032Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
2021-11-25T20:03:13.032Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:03:13.032Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=2
2021-11-25T20:03:27.032Z [DEBUG] polygon.consensus.ibft: round change timeout
2021-11-25T20:03:27.033Z [DEBUG] polygon.consensus.ibft: local round change: round=3
2021-11-25T20:03:27.035Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:03:27.037Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
2021-11-25T20:03:27.037Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:03:27.037Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
2021-11-25T20:03:27.039Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:03:27.039Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=3
2021-11-25T20:03:45.040Z [DEBUG] polygon.consensus.ibft: round change timeout
2021-11-25T20:03:45.040Z [DEBUG] polygon.consensus.ibft: local round change: round=4
2021-11-25T20:03:45.040Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:03:45.040Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
2021-11-25T20:03:45.042Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:03:45.042Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
2021-11-25T20:03:45.043Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:03:45.043Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=4
2021-11-25T20:04:11.044Z [DEBUG] polygon.consensus.ibft: round change timeout
2021-11-25T20:04:11.050Z [DEBUG] polygon.consensus.ibft: local round change: round=5
2021-11-25T20:04:11.051Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:04:11.051Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
2021-11-25T20:04:11.056Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:04:11.056Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
2021-11-25T20:04:11.056Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:04:11.056Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
2021-11-25T20:04:39.414Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:04:39.415Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=5
2021-11-25T20:04:39.415Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:04:39.415Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=5
2021-11-25T20:04:39.415Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:04:39.415Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:04:39.416Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x80359340dE9Ba7F6eEA873CC9600E8f09F9b3E35 block=214089
2021-11-25T20:04:39.421Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:04:39.421Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=5
2021-11-25T20:05:21.430Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:05:21.430Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=5
2021-11-25T20:05:21.430Z [DEBUG] polygon.consensus.ibft: local round change: round=6
2021-11-25T20:05:21.431Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:05:21.431Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=6
2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:05:21.436Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=6
2021-11-25T20:05:21.437Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:05:21.437Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:05:21.437Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x48aC0082F6c1e29fC25144B8d7f4607e36c13b1f block=214089
2021-11-25T20:06:35.438Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:06:35.438Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=6
2021-11-25T20:06:35.438Z [DEBUG] polygon.consensus.ibft: local round change: round=7
2021-11-25T20:06:35.439Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:06:35.439Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
2021-11-25T20:06:35.442Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:06:35.442Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=7
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:06:35.445Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=7
2021-11-25T20:06:35.445Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:06:35.446Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:06:35.446Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x96Dba988EE0a4b0921CeF51956e1dD03C9A0DbC6 block=214089
2021-11-25T20:06:35.450Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:06:35.450Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=7
2021-11-25T20:07:50.496Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:07:50.499Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:08:53.458Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:08:53.458Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=7
2021-11-25T20:08:53.458Z [DEBUG] polygon.consensus.ibft: local round change: round=8
2021-11-25T20:08:53.460Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:08:53.460Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
2021-11-25T20:08:53.465Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:08:53.466Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=8
2021-11-25T20:08:53.466Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:08:53.466Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=8
2021-11-25T20:08:53.466Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:08:53.466Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:08:53.466Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x25BAfc38a950837E0CCb49D10E0E98cce6CC8a44 block=214089
2021-11-25T20:08:53.476Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:08:53.476Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=8
2021-11-25T20:12:50.527Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:12:50.530Z [DEBUG] polygon.txpool: add txn: ctx=gossip hash=0xc31e83e3c26c43aeb77c8dc28bdc0eb941d7870c811b99e03138390a2ed59926 from=0x8b15973e6f557030FE01D02f09A7cF4f36f3b43F
2021-11-25T20:13:19.480Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
2021-11-25T20:13:19.480Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=214089 round=8
2021-11-25T20:13:19.480Z [DEBUG] polygon.consensus.ibft: local round change: round=9
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=1
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=2
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=3
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: roundLength=4
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: dgk - roundchange state received msg: round=9
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
2021-11-25T20:13:19.482Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=214089 round=9
2021-11-25T20:13:19.483Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=214089
2021-11-25T20:13:19.483Z [INFO]  polygon.consensus.ibft: current snapshot: validators=8 votes=0
2021-11-25T20:13:19.483Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x033a47156DD82CDdb2fD426B80088a9ae6101ac5 block=214089
2021-11-25T20:13:19.485Z [DEBUG] polygon.consensus.ibft: state change: new=ValidateState
2021-11-25T20:13:19.485Z [DEBUG] polygon.consensus.ibft: cycle: state=ValidateState sequence=214089 round=9
```

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

### LINKED ISSUE #261: Exponential round timeouts cause very long restart times
### Description

Related: https://github.com/0xPolygon/polygon-sdk/issues/245.

We made some faulty nodes to test the resiliency of the nodes and noticed that the time it takes for the nodes to get back to consensus is very long after 2/3 of the nodes are not byzantine anymore.

It's very possible this was the cause of us thinking our testnet was stuck (https://github.com/0xPolygon/polygon-sdk/issues/232, https://github.com/0xPolygon/polygon-sdk/issues/248) but in reality perhaps there was a network partition / other bug in the node discovery causing it, then this making restarts take a very long time. 

Inspired by 

image

Their implementation here: https://github.com/getamis/go-ethereum/pull/99/

Code here which is a WIP adapted for the SDK:

https://github.com/sx-network/sx-node/pull/2

The main issue here is that if a cluster stops for an hour, say (due to connectivity, etc), it might take 3+ hours for the nodes to recover even if they are all still connected, giving the illusion of a stuck chain. This is not what a chain operator might expect. 

The only way to "fix" it, is to get all the nodes to restart, effectively resetting their round to 1. 

Admittedly, this is technically "working as intended" in the code but not something you would expect.

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 7f2e61d19b63bde38f52925dee4eefc47e03ddf5
* branch that causes this issue `develop` with adapted modes from above

### Steps to reproduce

1. Create a 7 node cluster. Let it produce some blocks. 
2. Make 3 of the nodes byzantine (don't gossip blocks, gossip wrong messages etc) which will push it below the 2/3 threshold. 
3. The cluster should stop producing blocks. 
4. Wait 10 minutes or so. 
5. Replace the byzantine node with a standard node
6. Observe it takes 30m+ to get all nodes to reach the same round and produce blocks again. 

* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

It should not take so long to recover and start producing blocks again.

### Actual behaviour

It takes a very long time for the nodes to reach the same round and produce blocks. 

### Logs

```
2021-11-30T17:37:30.154-0500 [DEBUG] polygon.consensus.ibft: state change: new=CommitState
2021-11-30T17:37:30.154-0500 [INFO]  polygon.blockchain: write block: num=2680 parent=0xa145ad73ef2d8c399ce14712c068af2beba574288f0a991494ac6e9bcd718536
2021-11-30T18:13:28.291-0500 [INFO]  polygon.blockchain: write block: num=2681 parent=0x6a5c7127f8619b017887050065a198f0573eefdb713ffae70bd936558b8415ed
2021-11-30T18:13:38.377-0500 [INFO]  polygon.blockchain: write block: num=2682 parent=0x45d5213d7dcb10c7b62d69fbb4ea0a5b51cc0609da7e2332d5cb6a2c863a046a
```

### Proposed solution

We have some ideas here 

https://github.com/0xPolygon/polygon-sdk/issues/245

### PR DESCRIPTION
**Pull request by brkomir**
# Description

The problem addressed in this PR was that recovering consensus was delayed for a long time which is caused by long timeouts produced by the `randomTimeout()` method in `ibft.go`, which calculated timeout values in seconds as 10 + 2^(round number), so the timeout could grow to be very large. Issues #261, #245 and #248 have all emerged from this essentially.

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

### CODE REVIEW

File: consensus/ibft/ibft.go [hunk 1]
```diff
@@ -1045,6 +1034,7 @@ func (i *Ibft) getNextMessage(timeout time.Duration) (*proto.MessageReq, bool) {
 		// someone closes the stopCh (i.e. timeout for round change)
 		select {
 		case <-timeoutCh:
+			i.logger.Info("unable to read new message form the message queue", "timeout expired", timeout)
```
Comment (zivkovicmilos) [inline consensus/ibft/ibft.go]: Typo here `form`

File: consensus/ibft/ibft.go [hunk 2]
```diff
@@ -495,7 +494,7 @@ func (i *Ibft) writeTransactions(gasLimit uint64, transition transitionInterface
 // If it turns out that the current node is the proposer, it builds a block, and sends preprepare and then prepare messages.
 func (i *Ibft) runAcceptState() { // start new round
 	logger := i.logger.Named("acceptState")
-	logger.Info("Accept state", "sequence", i.state.view.Sequence)
+	logger.Info("Accept state", "sequence", i.state.view.Sequence, "round", i.state.view.Round+1)
```
Comment (zivkovicmilos) [inline consensus/ibft/ibft.go:497]: Why the `+1` here?

**Review by zivkovicmilos — APPROVED** [review]
Looks great 💯 

Thank you for looking into the linked issues and for adding great in-code docs and coverage tests 🙏

File: consensus/ibft/timeout_provider.go [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+const (
+	baseTimeout = 10 * time.Second
+	maxTimeout  = 300 * time.Second
+)
+
+// exponentialTimeout calculates the timeout duration in seconds as exponential function
+// where maximum value returned can't exceed 300 seconds
+// t = 10 + 2^exponent	where exponent > 0
+// t = 10				where exponent = 0
```
Comment (Kourin1996) [inline consensus/ibft/timeout_provider.go]: The second condition looks shifted

**Review by Kourin1996 — APPROVED** [review]

**Review by lazartravica — CHANGES_REQUESTED** [review]
Thanks for linting!

1. Can you elaborate a bit more on the Round num + 1 when printing?
It is zero indexed, if the only thing here is to add more clarity then we can remove +1, as it's clear in the code that the first round will be 0.

2. Please resolve the timeout Milos noticed

3. `_provider` is bugging me. The entire thing where we have a file for an IBFT timeout function is bugging me a bit, can we perhaps have it as `timeout.go` or move the func back to `ibft.go`

File: consensus/ibft/timeout_provider.go (hunk 3 above)
Comment (brkomir) [reply consensus/ibft/timeout_provider.go]: not sure why it looks like this on GH, in IDE looks aligned with the "where" from the line above

File: consensus/ibft/ibft.go (hunk 2 above)
Comment (brkomir) [reply consensus/ibft/ibft.go:497]: this is because we count rounds from 0, but don't print them out as starting from 0, but from 1. I saw @Kourin1996 made the same change on the line 748 so I just added it in all places for consistency.

**Comment by brkomir** [comment]
@lazartravica 


> 1. Can you elaborate a bit more on the Round num + 1 when printing?
>    It is zero indexed, if the only thing here is to add more clarity then we can remove +1, as it's clear in the code that the first round will be 0.

I have left a comment above why i did this. https://github.com/0xPolygon/polygon-sdk/pull/263#discussion_r760192356
If you think this should not be done in such way, I can make the changes.



> 3\. `_provider` is bugging me. The entire thing where we have a file for an IBFT timeout function is bugging me a bit, can we perhaps have it as `timeout.go` or move the func back to `ibft.go`

I agree that file name can be changed to the timeout.go. But I'm not inclined to move this logic back into the ibft.go, since more code lives there than it should, as you can conclude just by observing that file is more than 1000 lines long. I'm not a fan of such design practices where we put so much logic in a single file, because reading, navigating and understanding the responsibilities of the code there becomes hard.

File: consensus/ibft/ibft.go (hunk 1 above)
Comment (brkomir) [reply consensus/ibft/ibft.go]: [fixed](https://github.com/0xPolygon/polygon-sdk/pull/263/commits/3b612395bf20435f5af122f760b6fc990722cf64)

**Comment by mrwillis** [comment]
Just chiming in here and maybe I just need some clarity. Are the exponential timeouts necessary for the lower round nodes to "catch up"? Or is there another catch up mechanism for this in place.

File: consensus/ibft/timeout_provider.go (hunk 3 above)
Comment (lazartravica) [reply consensus/ibft/timeout_provider.go]: can confirm that GitHub on Firefox indents wrong. @Kourin1996 GoLand has GitHub PRs integrated, it's never too late to move from VSCode :)

**Comment by brkomir** [comment]
@mrwillis great question, as always :)

The exponential timeout isn't used as a mechanism for the lower round number nodes to catch up as you asked. It's simply being used for waiting on the response from other nodes. So it basically works like this, the nodes that are running but out of consensus, will be waiting for the other nodes to return, and every time this timeout expires a new round will start.

When the minimal number of nodes to restore consensus is achieved, this timeout will trigger a new round in which all active nodes will participate, the "returning" nodes will receive the reached round number by the previously running nodes, and the block production will continue.

I hope I was clear enough to answer your question.

**Review by lazartravica — APPROVED** [review]
